In [2]:
import openai
import pandas as pd
import tiktoken


from qdrant_client import QdrantClient
from qdrant_client import models
from qdrant_client.models import FieldCondition, MatchAny, Filter
from qdrant_client.models import VectorParams, Distance, SparseVectorParams, Modifier, PayloadSchemaType, PointStruct, Document, Prefetch, FusionQuery

In [3]:
qdrant_client = QdrantClient(url="http://localhost:6333")

In [3]:
qdrant_client.create_collection(
    collection_name="Amazon-reviews-collection-01",
    vectors_config={
        "text-embedding-3-small": VectorParams(size=1536, distance=Distance.COSINE)
    }
)

True

In [4]:
qdrant_client.create_payload_index(
    collection_name="Amazon-reviews-collection-01",
    field_name="parent_asin",
    field_schema=PayloadSchemaType.KEYWORD
)

UpdateResult(operation_id=2, status=<UpdateStatus.COMPLETED: 'completed'>)

In [4]:
def get_embedding(text, model="text-embedding-3-small"):
    response = openai.embeddings.create(
        input=text,
        model=model
    )
    return response.data[0].embedding

In [5]:
def get_embeddings_batch(text_list, model="text-embedding-3-small", batch_size=100):
    
    if len(text_list) <= batch_size:
        response = openai.embeddings.create(input=text_list, model=model)
        return [embedding.embedding for embedding in response.data]
    
    all_embeddings = []
    counter = 1
    for i in range(0, len(text_list), batch_size):
        batch = text_list[i:i + batch_size]
        response = openai.embeddings.create(input=batch, model=model)
        all_embeddings.extend([embedding.embedding for embedding in response.data])
        print(f"Processed {counter * batch_size} of {len(text_list)}")
        counter += 1
    
    return all_embeddings

In [6]:
df_reviews = pd.read_json("../../data/Electronics_with_category_sample_1000.jsonl", lines=True)

In [7]:
df_reviews.head()

,rating,title,text,images,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase
0,3,marginal sound quality,this really deserves 3 stars. its not terribl...,[],B0047T79VS,B0047T79VS,AGCI7FAH4GL5FI65HYLKWTMFZ2CQ,2012-08-08 06:08:03.000,0,True
1,5,Five Stars,Great hard drive for the price! Installed with...,[],B000Q85WOK,B000Q85WOK,AEFKF6R2GUSK2AWPSWRR4ZO36JVQ,2018-07-20 07:34:48.895,0,True
2,3,Too large for any speaker I have in my arsenal,I have 2 JBL and an LG portable Bluetooth spea...,[],B07ZWCTNJH,B07ZWCTNJH,AEVPPTMG43C6GWSR7I2UGRQN7WFQ,2022-02-26 16:04:57.397,0,True
3,1,Junk that doesn’t work,I would give this negative 0 stars if I could....,[],B09KTMJVJW,B09KTMJVJW,AEI4YPQZG6TZOWHDFP7I22S4MQZQ,2021-12-20 21:37:47.719,1,True
4,5,works well,"works very well. Has a very small USB nub, wh...",[],B005HQ5138,B005HQ5138,AFZUK3MTBIBEDQOPAK3OATUOUKLA,2014-09-20 18:03:16.000,0,True

In [8]:
len(df_reviews)

167138

In [10]:
def preprocess_reviews_data(row):
    return f"{row['title']} {row['text']}"

In [16]:
def count_tokens(row):
    encoding = tiktoken.encoding_for_model("text-embedding-3-small")
    return len(encoding.encode(row['preprocessed_data']))

In [14]:
count_tokens("How are you doing today?")

6

In [17]:
df_reviews['preprocessed_data'] =  df_reviews.apply(preprocess_reviews_data, axis=1)
df_reviews['token_count'] = df_reviews.apply(count_tokens, axis=1)

In [18]:
df_reviews.head()

,rating,title,text,images,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase,preprocessed_data,token_count
0,3,marginal sound quality,this really deserves 3 stars. its not terribl...,[],B0047T79VS,B0047T79VS,AGCI7FAH4GL5FI65HYLKWTMFZ2CQ,2012-08-08 06:08:03.000,0,True,marginal sound quality this really deserves 3 ...,63
1,5,Five Stars,Great hard drive for the price! Installed with...,[],B000Q85WOK,B000Q85WOK,AEFKF6R2GUSK2AWPSWRR4ZO36JVQ,2018-07-20 07:34:48.895,0,True,Five Stars Great hard drive for the price! Ins...,24
2,3,Too large for any speaker I have in my arsenal,I have 2 JBL and an LG portable Bluetooth spea...,[],B07ZWCTNJH,B07ZWCTNJH,AEVPPTMG43C6GWSR7I2UGRQN7WFQ,2022-02-26 16:04:57.397,0,True,Too large for any speaker I have in my arsenal...,87
3,1,Junk that doesn’t work,I would give this negative 0 stars if I could....,[],B09KTMJVJW,B09KTMJVJW,AEI4YPQZG6TZOWHDFP7I22S4MQZQ,2021-12-20 21:37:47.719,1,True,Junk that doesn’t work I would give this negat...,36
4,5,works well,"works very well. Has a very small USB nub, wh...",[],B005HQ5138,B005HQ5138,AFZUK3MTBIBEDQOPAK3OATUOUKLA,2014-09-20 18:03:16.000,0,True,works well works very well. Has a very small ...,66

In [19]:
df_reviews = df_reviews[df_reviews['token_count'] < 8192]

In [20]:
len(df_reviews)

167138

In [21]:
total_tokens = df_reviews['token_count'].sum()
total_tokens

np.int64(10018132)

In [23]:
df_reviews_to_embed = df_reviews[['preprocessed_data', 'parent_asin']]

In [24]:
df_reviews_to_embed.head()

                                   preprocessed_data parent_asin
0  marginal sound quality this really deserves 3 ...  B0047T79VS
1  Five Stars Great hard drive for the price! Ins...  B000Q85WOK
2  Too large for any speaker I have in my arsenal...  B07ZWCTNJH
3  Junk that doesn’t work I would give this negat...  B09KTMJVJW
4  works well works very well.  Has a very small ...  B005HQ5138

In [26]:
data_to_embed = df_reviews_to_embed.to_dict(orient="records")
data_to_embed

[{'preprocessed_data': 'marginal sound quality this really deserves 3 stars.  its not terrible, but its not great.  first is sound quality.  its not terrible.  2nd is limited distance.  its not terrible, but not great.<br /><br />I wish I had found a better product.',
  'parent_asin': 'B0047T79VS'},
 {'preprocessed_data': "Five Stars Great hard drive for the price! Installed with no issues in wife's Dell computer: She's very satisfied:",
  'parent_asin': 'B000Q85WOK'},
 {'preprocessed_data': "Too large for any speaker I have in my arsenal I have 2 JBL and an LG portable Bluetooth speaker and this was too large for any of them. One of the JBLs was barely long enough to be held by the straps but I didn't feel confident in how secure it was. The other 2 were just 2 short. I didn't think they were small speakers but apparently they are too small for this Mount",
  'parent_asin': 'B07ZWCTNJH'},
 {'preprocessed_data': 'Junk that doesn’t work I would give this negative 0 stars if I could. Does not work at all. Shame on you for stealing $10 from unsuspecting people.',
  'parent_asin': 'B09KTMJVJW'},
 {'preprocessed_data': "works well works very well.  Has a very small USB nub, which you can store inside the mouse, or leave on your computer.  Says &#34;red&#34;... but it's more like a deep fuschia to me.  It arrived quickly (I have Prime) and in good condition.",
  'parent_asin': 'B005HQ5138'},
 {'preprocessed_data': 'My controller doesn’t work properly I ended up just downloading a free Roku app onto my phone because this is the 2nd faulty controller that I’ve ordered from Amazon. The scroll right button works on and off, and often redirects me to download more apps.. it’s frustrating. Wouldn’t suggest anyone buying this. Save your money',
  'parent_asin': 'B07SPS13MC'},
 {'preprocessed_data': "This little speaker has awesome sound and can be played loud and it's still ... This little speaker has awesome sound and can be played loud and it's still a nice clear sound.  The color changing is a fun addition.<br /><br />I still need to download the app for voice control, but I wanted to leave feedback on how awesome this little speak works!<br /><br />I recommend it!",
  'parent_asin': 'B06Y2M9FNC'},
 {'preprocessed_data': "Easy to Use! This is my 3rd smart watch. I have had a Kate Spade and Michael Kors one. Those both used Wear OS. In comparison to those watches, I like this one better. It did require me to download more apps on my phone such as Galaxy Wearable. This watch is easy to use. There are 2 controls. The Michael Kors one had 2 controls, too, but their location was always accidently getting bumped which sometimes caused it to restart when I didn't want it to. I have never accidently bumped these buttons. The strap that comes with it barely fits my wrist, but there's an extra longer one that comes with it. It comes with a charger. The watch claims to stay charged for days. Well, technically that's true. I find that it lasts for 2 days so every other day I need to recharge it. My former watches both had to be charged every night, so I am pleased that this lasts a little longer. As far as the fitness aspect, this is better than my other ones. The step tracking seems to be more parallel to what I used to get from my Fitbit. The other smart watches were always really low in my step count which frustrated me. It tracks heart rate and stress levels. You can track fitness routines. The messaging feature is good, but I find it a little more difficult to reply to texts than my other watches. It gives you some quick replies, but I don't like the choices as much as the other ones. Also, I find it more difficult to customize my text replies with the actual typing. Overall, I do like this more than the other ones.",
  'parent_asin': 'B08J79T7CQ'},
 {'preprocessed_data': 'Nice brush for wet cleaning albums I needed a record brush for wet cleaning albums it works great for that',
  'parent_asin': 'B000M9H03E'},
 {'preprocessed_data': 'The one I received didn\'t work The one I received didn\'t work, and I returned it for a refund.  Plugging in one good optical source (ON), I noticed the output from each of the channels individually showed up as 2 red dots slightly skewed "oo" instead of one solid red dot "O".  This reduced the signal and probably corrupted it such that the signal could not be processed by my receiver.  This is probably due to an alignment problem within the device I received.',
  'parent_asin': 'B0002MQGR2'},
 {'preprocessed_data': "Works we with 4k monitors My new video card didn't have two HDMI inputs so this worked great for extending my 4 k monitories. good quality cable that works great with my KVM box.",
  'parent_asin': 'B08FBZ6SS3'},
 {'preprocessed_data': 'Nice value 2.1 set of computer speakers Great looking an sound set of computer speakers. A small set that will fit most desks. Nice value set for gaming listening to music. I have connected them to a laptop and also a blue tooth adapter to stream music. Perfect for a dorm room or a smaller work area. Bass is good in the mid rang and treble is crisp. This is a value sound system and work well in that range. It has volume controls with 3..5 jack out.',
  'parent_asin': 'B07PYHVH31'},
 {'preprocessed_data': 'Better and Cheaper than Cable. I bought this just before a hurricane. We still had power but no cable. The picture is BETTER than cable. We are receiving 32 channels. It is great. I am thinking of canceling some of my boxes and using this instead.',
  'parent_asin': 'B00RFLGH5E'},
 {'preprocessed_data': 'It does what it\'s supposed to do Do you have a large "standard" headphone jack where you\'d like to use your small iPod-type headphones?  Then get this.  Just plug it into the standard jack and then plug your headphones into the opening on the back of this converter and you\'re in business.  I bought one and it works as advertised.  It\'s small, light and inexpensive.  What else could you ask for?',
  'parent_asin': 'B00005T3GH'},
 {'preprocessed_data': 'Good Product Good Product',
  'parent_asin': 'B01D5H8N8K'},
 {'preprocessed_data': "Love this watch! Comfortable to wear, great technology, well thought out. Love that it automatically recognizes when I am going for a walk. I set my notifications so I never miss a text since I'm a careerwoman with a family. Its easy to stay in touch and be reminded of important events with this watch.",
  'parent_asin': 'B08J79T7CQ'},
 {'preprocessed_data': 'Nice Little Adapter This is a solid little adapter.  It looks sleek and elegant and does what it is supposed to. I am very happy with it and it serves the need we are having with all the new macbooks and PC tablets not having HDMI anymore.  Love this adapter.',
  'parent_asin': 'B082WCKGD8'},
 {'preprocessed_data': 'Good buy My sons was gifted a laptop so when the search began to look for a charger i wasnt sure. This charger has worked perfectly. No issues with charger over heating nothing. Oh yeah we used this charger for a chrome book mini.',
  'parent_asin': 'B077XVH192'},
 {'preprocessed_data': 'Super Easy Setup Plug and play.<br />1) Take the RCA you have from your older device plug into the RCA converter provided in this kit.<br />2) connect the HDMI cord provided in the kit and use it to connect to your HDTV and the converter provided in this kit.<br />3) use the provided USB power cord, plug it into the converter & use the provided USB power adapter and plug it into your power source.  DONE!',
  'parent_asin': 'B07M8RNRGT'},
 {'preprocessed_data': '4 months later and almost like new weighs 2.6 ounces, tough case, thin profile - winner!',
  'parent_asin': 'B00LIC2FHA'},
 {'preprocessed_data': "Love this Finally one I don't have to worry about losing.",
  'parent_asin': 'B09JWMNF4J'},
 {'preprocessed_data': 'Awesome Great price, son is going to lover the design, plus many more to choose from!',
  'parent_asin': 'B094Z97N4H'},
 {'preprocessed_data': 'Amazing ear buds! Amazing ear buds for less than $50! I had the prior model and loved them but this model is a huge step up. The charging case lasts for days on a single charge and the earbuds never seem to die even with heavy use (I use them 8+ hourse a day listings to music and podcasts) the sound quality is much better with music as well as phone calls. I recommend these to anyone who would like a better alternative to apple air pods',
  'parent_asin': 'B08548M6FF'},
 {'preprocessed_data': "Compact easy to use body cam Perfect for my job. It looks more like my radio mic so it's a bit discreet. The functions are easy to use. Basically you turn it on and press it again to record.  The quality is more than enough for me, while I don't need it to be high resolution. Battery life I've been getting more than a couple days working 12 hour shifts.",
  'parent_asin': 'B07ZM19Y9H'},
 {'preprocessed_data': 'Great Love this product, would buy again!',
  'parent_asin': 'B0753QWL5X'},
 {'preprocessed_data': "GOOD CHOICE! I'M SO HAPPY WITH THIS MOUSE BY LOGITECH, IT'S SMALLER THAN MY OLD ONE AND MUCH MORE SENSITIVE--LIKE POWER STEERING VS. MANUEL. I THOUGHT SOMETHING WAS WRONG WITH MY OLD MOUSE WHEN IT STOPPED ROTATING UP AND DOWN, AND I LOOKED ALL OVER THE NET FOR ANSWERS. FINALLY, I JUST BROKE DOWN AND BOUGHT A NEW ONE--GOOD THING!",
  'parent_asin': 'B005HQ5138'},
 {'preprocessed_data': 'not too curved perfect size perfect curve i love it very crisp',
  'parent_asin': 'B0BDWN4RHW'},
 {'preprocessed_data': "The best case I've seen so far... Received my case today for my new iPad Pro 9.7 inch and I love it. It adds very little bulk to the iPad itself and feels very comfortable in my hands. It protects both the screen and the back of the iPad. Much better quality than I had anticipated and very much worth the price especially with free shipping. I originally ordered the black case and now I've ordered the rose gold one too.",
  'parent_asin': 'B01D1NUDJK'},
 {'preprocessed_data': "Good quality I received a laptop to work from home and it is old with no built in camera so I needed to get one for online meetings.<br />I choose this one because you didn't need to install any external drivers- all you have to do is plug it in and it installs what you need. I also like the picture quality it says that it's 1080P-I can't really confirm if thats true but it's definitely a nice clear picture and so far I've had no issues with people hearing me during meetings.",
  'parent_asin': 'B087986YPY'},
 {'preprocessed_data': 'Missing parts Putting together was missing 4ea.connection plate screws.<br />M5x8mm. I did fine some to fit at local hardware store.',
  'parent_asin': 'B00VMH7PQM'},
 {'preprocessed_data': 'Five Stars great quality',
  'parent_asin': 'B0184IC7VE'},
 {'preprocessed_data': 'A Few Wipes and the Dirt is GONE! Amazing! Well, it finally happened. Thanks to \'having some birthdays \'(my optometrist\'s polite way of saying  I\'m getting older), two months ago I officially joined millions all over the world and became a wearer of eye glasses!  First time ever for me.  I was shocked how quickly the lenses get dirty!  The first time I went to clean them I was about to use a wet paper towel on them when my husband walked into the room, saw what I was doing and screamed, "NO!!!" before grabbing the towel out of my hand.  lol.  (My poor heart...scared the daylights out of me!)  I then had to listen to a lecture about what to use to clean my glasses, along with a demonstration showing me how to clean them! lolol.  He gets a box of eye glass wipes at the store for $5. and they do work well. But they left kind of a sticky residue on my fingers that I didn\'t care for. I did a quick check online and learned microfiber cloths do a fantastic job of cleaning glasses and do so without the use of glass cleaner (liquid) or water. I immediately ordered Fiber Promot microfiber cloths and was (still am) amazed and impressed how well they clean my glasses!  And how easy are they to use? Simply wipe the lenses a few times and PRESTO! Clean glasses! That\'s it. That\'s all it takes to wipe the dirt away!  But I didn\'t stop with my glasses....I then wiped down the TVs, my laptop, my Kindle and my cell phone all with the same fabulous results as my glasses!  These cloths do an amazing job and best of all, they do not scratch items they are used on!  I got the 6x7 cloth size (6 cloths included) and they\'re the perfect size to clean everything I listed above. I put one in my purse as well. They work great, do not cause damage and leave no sticky residue as the other wipes I previously used did.  And they\'re cheap! Incredibly cheap! You\'d think something that works as well as these cloths work and require next to no work to use them would cost  far more than these cost!  These are incredible and do a fantastic job. There is even a 1 year money back guarantee on them, though I doubt the company gets many returns because these are fabulous!  If you wear glasses, you\'re going to want these cloths. And don\'t forget, they clean other items as well!',
  'parent_asin': 'B01JNYQXZY'},
 {'preprocessed_data': 'Convenient Great, and practical gift for grandchild',
  'parent_asin': 'B071WNBH6S'},
 {'preprocessed_data': 'Excellent product Great easy to use mouse',
  'parent_asin': 'B002DPUUL4'},
 {'preprocessed_data': 'LOVE IT! LOVE IT! LOVE IT! [[VIDEOID:4f6190cb754b79591e31b3e81894708f]] So easy to set up and start monitoring. I am nowhere near a technological anything and this was easy for me to set up and start monitoring my home. It has a round base that you screw to the wall and the camera attaches to the base. It is essentially plug n play. Download the app, plug in the camera - the software updates - and you’re pretty much good to go. There are multiple settings to adjust notifications and there’s also a subscription for those who want to keep video clips longer-term. But it’s no cost for short-term video clips. You can watch live and set the motion sensitivity as to what activates it to record a clip. There’s infrared for night video. The picture quality is excellent! I got two cameras, to check out different angles in my house and see what my goofy cats are doing while I’m at work. I LOVE these cameras! See what one of my trouble makers does while I’m gone. Watch the upper-center of the screen.',
  'parent_asin': 'B01C4UY0JK'},
 {'preprocessed_data': "Now have four after getting one for Christmas We got one for Christmas from my son, and liked it so much we ordered three more!  Really simple to set up, you don't have to run wire in your house - just plug in, you don't have to pay for a server - you own the SD card, the viewing picture is clear, the night vision is clear enough, the speaker is a bonus, the iPhone app is easy to navigate, and we have multiple people in the family with access on 4 different phones and two different operating systems. All our cameras are for outside use, except one, and we turn it off from the app when we are home for privacy.  Easiest, cheapest coverage for a basic remote viewing security system you can get.<br /><br />Three out of four had a memory card.",
  'parent_asin': 'B016F3M7OM'},
 {'preprocessed_data': 'Love it Great cable. Love the champagne color and the cord has been very durable so far. I put my cables through the ringer it seems and this one seems to be one that will hold up very well. This is the first braided cable I have tried and as of now, I would get more if/when I need them.',
  'parent_asin': 'B01F9RGSFE'},
 {'preprocessed_data': "Seems to work So far it's working. I only used it once.",
  'parent_asin': 'B071YPQQFF'},
 {'preprocessed_data': 'Returned product It was returned',
  'parent_asin': 'B07JPG6C8V'},
 {'preprocessed_data': "Not so great. Doesn't really do as promised Maybe mine is defective because my iPad won't stay put and just slides right off this thing. I find it a struggle to balance it while I'm trying to sit up and use my pad. I would not recommend this. It's a good idea but something just isn't right .",
  'parent_asin': 'B01BH5TLK6'},
 {'preprocessed_data': 'The best Of course the best',
  'parent_asin': 'B08J79T7CQ'},
 {'preprocessed_data': 'Worked great! Somehow I lost the original one for my Garment rv770. It worked great!',
  'parent_asin': 'B08MQ4MG9D'},
 {'preprocessed_data': "This wireless mouse does the job flawlessly It's affordable and moves up and down the page smoothly. With both a right and a left click button it's everything you'd want in a wireless mouse.",
  'parent_asin': 'B002DPUUL4'},
 {'preprocessed_data': "Loyal customer and PRIME MEMBER don't mean anything. I am writing to people know that if you are going to buy a high dollar item go do it local .This item went down on me the 2 nd day asked for a replacement  got one that had been opened  at the very least or shipped then returned then sent to me as replacement at least this one works but I payed 364.00 plus tax a renewed one was selling for 319.00 so I thought it only fair that I payed  used price for replacement.  The manager said send picture ok then said I had to return the one that is working now. I said no to that already have between phone calls and set up time of both computers about 5 hours into save yourself the time and headache trying to explain all this to someone who can't speak English and even told when I wasn't sending the working one back , you don't send back you have to pay for both. What happened to customer service in this country.",
  'parent_asin': 'B08CSHM6K1'},
 {'preprocessed_data': 'Great little hd antenna All I can say is it works great .easy to install and picks up more channels than I expected.',
  'parent_asin': 'B01FFV8W76'},
 {'preprocessed_data': 'TV Stand Very well made and it worked great. Very well built.',
  'parent_asin': 'B087BW97NJ'},
 {'preprocessed_data': 'EXCELLENT camera I Purchased this for my mothers house who is 95 so that I can watch her in her kitchen, and den as she lives by herself. I had a regular blink camera, which did a good job, but this allows me to look around the room as she does move around a bit, and sometimes out of view of the other camera, I would highly recommend this, as it is easy to use an outstanding clarity',
  'parent_asin': 'B0BDN8VNM2'},
 {'preprocessed_data': 'Loving my "new" iPad Okay, so I was skeptical of a refurbished iPad but changed it. Turned out to be a good move. Love the iPad. Came in VERY good shape with the correct apple cord. Charges great, super fast, screen without scratches...I love it!',
  'parent_asin': 'B07D3DDJ4L'},
 {'preprocessed_data': "Only lasts 1 year This is a good mouse, while it lasts. The left click WILL fail. I've had two. If you want a mouse to last longer than a year, don't get this.",
  'parent_asin': 'B002DPUUL4'},
 {'preprocessed_data': "Great sound for a great price I was actually very surprised at the quality of sound this produces for something so small and inexpensive. I use it regularly, and I love it. It's a rugged little speaker that will get the job done.",
  'parent_asin': 'B081KRJHPM'},
 {'preprocessed_data': "Great antenna! This antenna sucks in over-the-air stations like a Hoover vac getting dirt off of your rug. I've tried plenty of antennas and this is the best.",
  'parent_asin': 'B01FFV8W76'},
 {'preprocessed_data': 'Wow can be mounted in different ways This is Great setup for your home office or at your hard office.  makes a great way to store with easy access when you need to use the headsets.',
  'parent_asin': 'B08X4PNTNV'},
 {'preprocessed_data': 'Works as Advertised Location: Downtown Tampa, facing South.<br />Works OK behind the mounted TV, and even under the couch, but I need to move the &#34;board&#34; for certain stations.',
  'parent_asin': 'B00RFLGH5E'},

In [27]:
len(data_to_embed)

167138

### Embded

In [ ]:
text_to_embed_reviews = [item['preprocessed_data'] for item in data_to_embed]
text_to_embed_reviews

['marginal sound quality this really deserves 3 stars.  its not terrible, but its not great.  first is sound quality.  its not terrible.  2nd is limited distance.  its not terrible, but not great.<br /><br />I wish I had found a better product.',
 "Five Stars Great hard drive for the price! Installed with no issues in wife's Dell computer: She's very satisfied:",
 "Too large for any speaker I have in my arsenal I have 2 JBL and an LG portable Bluetooth speaker and this was too large for any of them. One of the JBLs was barely long enough to be held by the straps but I didn't feel confident in how secure it was. The other 2 were just 2 short. I didn't think they were small speakers but apparently they are too small for this Mount",
 'Junk that doesn’t work I would give this negative 0 stars if I could. Does not work at all. Shame on you for stealing $10 from unsuspecting people.',
 "works well works very well.  Has a very small USB nub, which you can store inside the mouse, or leave on your computer.  Says &#34;red&#34;... but it's more like a deep fuschia to me.  It arrived quickly (I have Prime) and in good condition.",
 'My controller doesn’t work properly I ended up just downloading a free Roku app onto my phone because this is the 2nd faulty controller that I’ve ordered from Amazon. The scroll right button works on and off, and often redirects me to download more apps.. it’s frustrating. Wouldn’t suggest anyone buying this. Save your money',
 "This little speaker has awesome sound and can be played loud and it's still ... This little speaker has awesome sound and can be played loud and it's still a nice clear sound.  The color changing is a fun addition.<br /><br />I still need to download the app for voice control, but I wanted to leave feedback on how awesome this little speak works!<br /><br />I recommend it!",
 "Easy to Use! This is my 3rd smart watch. I have had a Kate Spade and Michael Kors one. Those both used Wear OS. In comparison to those watches, I like this one better. It did require me to download more apps on my phone such as Galaxy Wearable. This watch is easy to use. There are 2 controls. The Michael Kors one had 2 controls, too, but their location was always accidently getting bumped which sometimes caused it to restart when I didn't want it to. I have never accidently bumped these buttons. The strap that comes with it barely fits my wrist, but there's an extra longer one that comes with it. It comes with a charger. The watch claims to stay charged for days. Well, technically that's true. I find that it lasts for 2 days so every other day I need to recharge it. My former watches both had to be charged every night, so I am pleased that this lasts a little longer. As far as the fitness aspect, this is better than my other ones. The step tracking seems to be more parallel to what I used to get from my Fitbit. The other smart watches were always really low in my step count which frustrated me. It tracks heart rate and stress levels. You can track fitness routines. The messaging feature is good, but I find it a little more difficult to reply to texts than my other watches. It gives you some quick replies, but I don't like the choices as much as the other ones. Also, I find it more difficult to customize my text replies with the actual typing. Overall, I do like this more than the other ones.",
 'Nice brush for wet cleaning albums I needed a record brush for wet cleaning albums it works great for that',
 'The one I received didn\'t work The one I received didn\'t work, and I returned it for a refund.  Plugging in one good optical source (ON), I noticed the output from each of the channels individually showed up as 2 red dots slightly skewed "oo" instead of one solid red dot "O".  This reduced the signal and probably corrupted it such that the signal could not be processed by my receiver.  This is probably due to an alignment problem within the device I received.',
 "Works we with 4k monitors My new video card didn't have two HDMI inputs so this worked great for extending my 4 k monitories. good quality cable that works great with my KVM box.",
 'Nice value 2.1 set of computer speakers Great looking an sound set of computer speakers. A small set that will fit most desks. Nice value set for gaming listening to music. I have connected them to a laptop and also a blue tooth adapter to stream music. Perfect for a dorm room or a smaller work area. Bass is good in the mid rang and treble is crisp. This is a value sound system and work well in that range. It has volume controls with 3..5 jack out.',
 'Better and Cheaper than Cable. I bought this just before a hurricane. We still had power but no cable. The picture is BETTER than cable. We are receiving 32 channels. It is great. I am thinking of canceling some of my boxes and using this instead.',
 'It does what it\'s supposed to do Do you have a large "standard" headphone jack where you\'d like to use your small iPod-type headphones?  Then get this.  Just plug it into the standard jack and then plug your headphones into the opening on the back of this converter and you\'re in business.  I bought one and it works as advertised.  It\'s small, light and inexpensive.  What else could you ask for?',
 'Good Product Good Product',
 "Love this watch! Comfortable to wear, great technology, well thought out. Love that it automatically recognizes when I am going for a walk. I set my notifications so I never miss a text since I'm a careerwoman with a family. Its easy to stay in touch and be reminded of important events with this watch.",
 'Nice Little Adapter This is a solid little adapter.  It looks sleek and elegant and does what it is supposed to. I am very happy with it and it serves the need we are having with all the new macbooks and PC tablets not having HDMI anymore.  Love this adapter.',
 'Good buy My sons was gifted a laptop so when the search began to look for a charger i wasnt sure. This charger has worked perfectly. No issues with charger over heating nothing. Oh yeah we used this charger for a chrome book mini.',
 'Super Easy Setup Plug and play.<br />1) Take the RCA you have from your older device plug into the RCA converter provided in this kit.<br />2) connect the HDMI cord provided in the kit and use it to connect to your HDTV and the converter provided in this kit.<br />3) use the provided USB power cord, plug it into the converter & use the provided USB power adapter and plug it into your power source.  DONE!',
 '4 months later and almost like new weighs 2.6 ounces, tough case, thin profile - winner!',
 "Love this Finally one I don't have to worry about losing.",
 'Awesome Great price, son is going to lover the design, plus many more to choose from!',
 'Amazing ear buds! Amazing ear buds for less than $50! I had the prior model and loved them but this model is a huge step up. The charging case lasts for days on a single charge and the earbuds never seem to die even with heavy use (I use them 8+ hourse a day listings to music and podcasts) the sound quality is much better with music as well as phone calls. I recommend these to anyone who would like a better alternative to apple air pods',
 "Compact easy to use body cam Perfect for my job. It looks more like my radio mic so it's a bit discreet. The functions are easy to use. Basically you turn it on and press it again to record.  The quality is more than enough for me, while I don't need it to be high resolution. Battery life I've been getting more than a couple days working 12 hour shifts.",
 'Great Love this product, would buy again!',
 "GOOD CHOICE! I'M SO HAPPY WITH THIS MOUSE BY LOGITECH, IT'S SMALLER THAN MY OLD ONE AND MUCH MORE SENSITIVE--LIKE POWER STEERING VS. MANUEL. I THOUGHT SOMETHING WAS WRONG WITH MY OLD MOUSE WHEN IT STOPPED ROTATING UP AND DOWN, AND I LOOKED ALL OVER THE NET FOR ANSWERS. FINALLY, I JUST BROKE DOWN AND BOUGHT A NEW ONE--GOOD THING!",
 'not too curved perfect size perfect curve i love it very crisp',
 "The best case I've seen so far... Received my case today for my new iPad Pro 9.7 inch and I love it. It adds very little bulk to the iPad itself and feels very comfortable in my hands. It protects both the screen and the back of the iPad. Much better quality than I had anticipated and very much worth the price especially with free shipping. I originally ordered the black case and now I've ordered the rose gold one too.",
 "Good quality I received a laptop to work from home and it is old with no built in camera so I needed to get one for online meetings.<br />I choose this one because you didn't need to install any external drivers- all you have to do is plug it in and it installs what you need. I also like the picture quality it says that it's 1080P-I can't really confirm if thats true but it's definitely a nice clear picture and so far I've had no issues with people hearing me during meetings.",
 'Missing parts Putting together was missing 4ea.connection plate screws.<br />M5x8mm. I did fine some to fit at local hardware store.',
 'Five Stars great quality',
 'A Few Wipes and the Dirt is GONE! Amazing! Well, it finally happened. Thanks to \'having some birthdays \'(my optometrist\'s polite way of saying  I\'m getting older), two months ago I officially joined millions all over the world and became a wearer of eye glasses!  First time ever for me.  I was shocked how quickly the lenses get dirty!  The first time I went to clean them I was about to use a wet paper towel on them when my husband walked into the room, saw what I was doing and screamed, "NO!!!" before grabbing the towel out of my hand.  lol.  (My poor heart...scared the daylights out of me!)  I then had to listen to a lecture about what to use to clean my glasses, along with a demonstration showing me how to clean them! lolol.  He gets a box of eye glass wipes at the store for $5. and they do work well. But they left kind of a sticky residue on my fingers that I didn\'t care for. I did a quick check online and learned microfiber cloths do a fantastic job of cleaning glasses and do so without the use of glass cleaner (liquid) or water. I immediately ordered Fiber Promot microfiber cloths and was (still am) amazed and impressed how well they clean my glasses!  And how easy are they to use? Simply wipe the lenses a few times and PRESTO! Clean glasses! That\'s it. That\'s all it takes to wipe the dirt away!  But I didn\'t stop with my glasses....I then wiped down the TVs, my laptop, my Kindle and my cell phone all with the same fabulous results as my glasses!  These cloths do an amazing job and best of all, they do not scratch items they are used on!  I got the 6x7 cloth size (6 cloths included) and they\'re the perfect size to clean everything I listed above. I put one in my purse as well. They work great, do not cause damage and leave no sticky residue as the other wipes I previously used did.  And they\'re cheap! Incredibly cheap! You\'d think something that works as well as these cloths work and require next to no work to use them would cost  far more than these cost!  These are incredible and do a fantastic job. There is even a 1 year money back guarantee on them, though I doubt the company gets many returns because these are fabulous!  If you wear glasses, you\'re going to want these cloths. And don\'t forget, they clean other items as well!',
 'Convenient Great, and practical gift for grandchild',
 'Excellent product Great easy to use mouse',
 'LOVE IT! LOVE IT! LOVE IT! [[VIDEOID:4f6190cb754b79591e31b3e81894708f]] So easy to set up and start monitoring. I am nowhere near a technological anything and this was easy for me to set up and start monitoring my home. It has a round base that you screw to the wall and the camera attaches to the base. It is essentially plug n play. Download the app, plug in the camera - the software updates - and you’re pretty much good to go. There are multiple settings to adjust notifications and there’s also a subscription for those who want to keep video clips longer-term. But it’s no cost for short-term video clips. You can watch live and set the motion sensitivity as to what activates it to record a clip. There’s infrared for night video. The picture quality is excellent! I got two cameras, to check out different angles in my house and see what my goofy cats are doing while I’m at work. I LOVE these cameras! See what one of my trouble makers does while I’m gone. Watch the upper-center of the screen.',
 "Now have four after getting one for Christmas We got one for Christmas from my son, and liked it so much we ordered three more!  Really simple to set up, you don't have to run wire in your house - just plug in, you don't have to pay for a server - you own the SD card, the viewing picture is clear, the night vision is clear enough, the speaker is a bonus, the iPhone app is easy to navigate, and we have multiple people in the family with access on 4 different phones and two different operating systems. All our cameras are for outside use, except one, and we turn it off from the app when we are home for privacy.  Easiest, cheapest coverage for a basic remote viewing security system you can get.<br /><br />Three out of four had a memory card.",
 'Love it Great cable. Love the champagne color and the cord has been very durable so far. I put my cables through the ringer it seems and this one seems to be one that will hold up very well. This is the first braided cable I have tried and as of now, I would get more if/when I need them.',
 "Seems to work So far it's working. I only used it once.",
 'Returned product It was returned',
 "Not so great. Doesn't really do as promised Maybe mine is defective because my iPad won't stay put and just slides right off this thing. I find it a struggle to balance it while I'm trying to sit up and use my pad. I would not recommend this. It's a good idea but something just isn't right .",
 'The best Of course the best',
 'Worked great! Somehow I lost the original one for my Garment rv770. It worked great!',
 "This wireless mouse does the job flawlessly It's affordable and moves up and down the page smoothly. With both a right and a left click button it's everything you'd want in a wireless mouse.",
 "Loyal customer and PRIME MEMBER don't mean anything. I am writing to people know that if you are going to buy a high dollar item go do it local .This item went down on me the 2 nd day asked for a replacement  got one that had been opened  at the very least or shipped then returned then sent to me as replacement at least this one works but I payed 364.00 plus tax a renewed one was selling for 319.00 so I thought it only fair that I payed  used price for replacement.  The manager said send picture ok then said I had to return the one that is working now. I said no to that already have between phone calls and set up time of both computers about 5 hours into save yourself the time and headache trying to explain all this to someone who can't speak English and even told when I wasn't sending the working one back , you don't send back you have to pay for both. What happened to customer service in this country.",
 'Great little hd antenna All I can say is it works great .easy to install and picks up more channels than I expected.',
 'TV Stand Very well made and it worked great. Very well built.',
 'EXCELLENT camera I Purchased this for my mothers house who is 95 so that I can watch her in her kitchen, and den as she lives by herself. I had a regular blink camera, which did a good job, but this allows me to look around the room as she does move around a bit, and sometimes out of view of the other camera, I would highly recommend this, as it is easy to use an outstanding clarity',
 'Loving my "new" iPad Okay, so I was skeptical of a refurbished iPad but changed it. Turned out to be a good move. Love the iPad. Came in VERY good shape with the correct apple cord. Charges great, super fast, screen without scratches...I love it!',
 "Only lasts 1 year This is a good mouse, while it lasts. The left click WILL fail. I've had two. If you want a mouse to last longer than a year, don't get this.",
 "Great sound for a great price I was actually very surprised at the quality of sound this produces for something so small and inexpensive. I use it regularly, and I love it. It's a rugged little speaker that will get the job done.",
 "Great antenna! This antenna sucks in over-the-air stations like a Hoover vac getting dirt off of your rug. I've tried plenty of antennas and this is the best.",
 'Wow can be mounted in different ways This is Great setup for your home office or at your hard office.  makes a great way to store with easy access when you need to use the headsets.',
 'Works as Advertised Location: Downtown Tampa, facing South.<br />Works OK behind the mounted TV, and even under the couch, but I need to move the &#34;board&#34; for certain stations.',
 "Cannot live without mine Range limitations notwithstanding, this receiver has dramatically expanded the usefulness of my Droid X by allowing me to play my music through my home stereo system, as well as through my friend's [[ASIN:B001DLTDQC Bose SoundDock Series II Digital Music System for iPod (Black)]] (using an [[ASIN:B000068O51 Hosa YRA154 1/8 Male To Dual RCA Female]] to adapt the Belkin to the Sounddock since my Droid will not fit the iPod cradle.)<br /><br />One reason I do not have a problem with the range is I am usually in the room where the stereo is, and sit fairly close to where I have the Belkin receiver located. And, with the Bose rig, that is for taking out to the patio or in the kitchen, so I am in line of sight and pretty close as well.<br /><br />The signal is consistently strong between my Droid X and the receiver, and the sound quality is more than adequate for my old ears. The only thing I would want is for the Belkin receiver to automatically connect with my Droid X in the same manner that the [[ASIN:B003PPGOC0 GOgroove FlexSMART X2 ADVANCED Wireless In-Car Bluetooth FM Transmitter with Charging, Music Control and Hands-Free Calling for ANDROID, iPhone, Blackberry and Windows Smartphones]] I have in my car does. As it stands, I always have to go into my Droid's settings and manually connect the paired Belkin before I can transmit my music stream to it.<br /><br />Overall I am very pleased with this receiver and intend to purchase two more (one for a PA system I own, and a dedicated one for the Bose Sounddock.)",
 'worked great. No problems, worked great.',
 'A good buy Great back pack for your labtop what i don’t agree on is the color it says pink but it looks more red and just a little pink',
 "Sony A6500 e-mount adaptor for all Nikon lenses Bought this to use my older manual Nikkor lenses with newer Sony A6500. Construction and fit are excellent. Optics suffer slightly as they used to with extension tubes on SLR bodies. Some vignetting with Wide manual lenses.  Still trying to find the right mix of manual f-stops/iso/shutter speed and have better success when in 100% manual mode with the A6500. The quality of the e-mount sigma and sony lenses are so amazing... the Nikon manual lens pics are a little disappointing. I have yet to try with large heavy telephoto lenses but would never think about using this without a lens with its own tripod mount. For price... cannot beat this... want to try one of the autofocus mounts before I buy... this is a great piece to carry in your bag... you can always borrow your friends' Nikon lenses.. Will continue to evaluate over time",
 'Works great Free TV :)',
 'Not recommended Very poor imaging with a fish eye result. Objects in the distance were curved and distorted.',

In [29]:
embeddings = get_embeddings_batch(text_to_embed_reviews, batch_size=500)

Processed 500 of 167138
Processed 1000 of 167138
Processed 1500 of 167138
Processed 2000 of 167138
Processed 2500 of 167138
Processed 3000 of 167138
Processed 3500 of 167138
Processed 4000 of 167138
Processed 4500 of 167138
Processed 5000 of 167138
Processed 5500 of 167138
Processed 6000 of 167138
Processed 6500 of 167138
Processed 7000 of 167138
Processed 7500 of 167138
Processed 8000 of 167138
Processed 8500 of 167138
Processed 9000 of 167138
Processed 9500 of 167138
Processed 10000 of 167138
Processed 10500 of 167138
Processed 11000 of 167138
Processed 11500 of 167138
Processed 12000 of 167138
Processed 12500 of 167138
Processed 13000 of 167138
Processed 13500 of 167138
Processed 14000 of 167138
Processed 14500 of 167138
Processed 15000 of 167138
Processed 15500 of 167138
Processed 16000 of 167138
Processed 16500 of 167138
Processed 17000 of 167138
Processed 17500 of 167138
Processed 18000 of 167138
Processed 18500 of 167138
Processed 19000 of 167138
Processed 19500 of 167138
Processed 20000 of 167138
Processed 20500 of 167138
Processed 21000 of 167138
Processed 21500 of 167138
Processed 22000 of 167138
Processed 22500 of 167138
Processed 23000 of 167138
Processed 23500 of 167138
Processed 24000 of 167138
Processed 24500 of 167138
Processed 25000 of 167138
Processed 25500 of 167138
Processed 26000 of 167138
Processed 26500 of 167138
Processed 27000 of 167138
Processed 27500 of 167138
Processed 28000 of 167138
Processed 28500 of 167138
Processed 29000 of 167138
Processed 29500 of 167138
Processed 30000 of 167138
Processed 30500 of 167138
Processed 31000 of 167138
Processed 31500 of 167138
Processed 32000 of 167138
Processed 32500 of 167138
Processed 33000 of 167138
Processed 33500 of 167138
Processed 34000 of 167138
Processed 34500 of 167138
Processed 35000 of 167138
Processed 35500 of 167138
Processed 36000 of 167138
Processed 36500 of 167138
Processed 37000 of 167138
Processed 37500 of 167138
Processed 38000 of 167138
Processed 38500 of 167138
Processed 39000 of 167138
Processed 39500 of 167138
Processed 40000 of 167138
Processed 40500 of 167138
Processed 41000 of 167138
Processed 41500 of 167138
Processed 42000 of 167138
Processed 42500 of 167138
Processed 43000 of 167138
Processed 43500 of 167138
Processed 44000 of 167138
Processed 44500 of 167138
Processed 45000 of 167138
Processed 45500 of 167138
Processed 46000 of 167138
Processed 46500 of 167138
Processed 47000 of 167138
Processed 47500 of 167138
Processed 48000 of 167138
Processed 48500 of 167138
Processed 49000 of 167138
Processed 49500 of 167138
Processed 50000 of 167138
Processed 50500 of 167138
Processed 51000 of 167138
Processed 51500 of 167138
Processed 52000 of 167138
Processed 52500 of 167138
Processed 53000 of 167138
Processed 53500 of 167138
Processed 54000 of 167138
Processed 54500 of 167138
Processed 55000 of 167138
Processed 55500 of 167138
Processed 56000 of 167138
Processed 56500 of 167138
Processed 57000 of 167138
Processed 57500 of 167138
Processed 58000 of 167138
Processed 58500 of 167138
Processed 59000 of 167138
Processed 59500 of 167138
Processed 60000 of 167138
Processed 60500 of 167138
Processed 61000 of 167138
Processed 61500 of 167138
Processed 62000 of 167138
Processed 62500 of 167138
Processed 63000 of 167138
Processed 63500 of 167138
Processed 64000 of 167138
Processed 64500 of 167138
Processed 65000 of 167138
Processed 65500 of 167138
Processed 66000 of 167138
Processed 66500 of 167138
Processed 67000 of 167138
Processed 67500 of 167138
Processed 68000 of 167138
Processed 68500 of 167138
Processed 69000 of 167138
Processed 69500 of 167138
Processed 70000 of 167138
Processed 70500 of 167138
Processed 71000 of 167138
Processed 71500 of 167138
Processed 72000 of 167138
Processed 72500 of 167138
Processed 73000 of 167138
Processed 73500 of 167138
Processed 74000 of 167138
Processed 74500 of 167138
Processed 75000 of 167138
Processed 75500 of 167138
Processed 76000 of 167138
Processed 76500 of 167138
Processed 77000 of 167138
Processed 77500 of 167138
Processed 78000 of 167138
Processed 78500 of 167138
Processed 79000 of 167138
Processed 79500 of 167138
Processed 80000 of 167138
Processed 80500 of 167138
Processed 81000 of 167138
Processed 81500 of 167138
Processed 82000 of 167138
Processed 82500 of 167138
Processed 83000 of 167138
Processed 83500 of 167138
Processed 84000 of 167138
Processed 84500 of 167138
Processed 85000 of 167138
Processed 85500 of 167138
Processed 86000 of 167138
Processed 86500 of 167138
Processed 87000 of 167138
Processed 87500 of 167138
Processed 88000 of 167138
Processed 88500 of 167138
Processed 89000 of 167138
Processed 89500 of 167138
Processed 90000 of 167138
Processed 90500 of 167138
Processed 91000 of 167138
Processed 91500 of 167138
Processed 92000 of 167138
Processed 92500 of 167138
Processed 93000 of 167138
Processed 93500 of 167138
Processed 94000 of 167138
Processed 94500 of 167138
Processed 95000 of 167138
Processed 95500 of 167138
Processed 96000 of 167138
Processed 96500 of 167138
Processed 97000 of 167138
Processed 97500 of 167138
Processed 98000 of 167138
Processed 98500 of 167138
Processed 99000 of 167138
Processed 99500 of 167138
Processed 100000 of 167138
Processed 100500 of 167138
Processed 101000 of 167138
Processed 101500 of 167138
Processed 102000 of 167138
Processed 102500 of 167138
Processed 103000 of 167138
Processed 103500 of 167138
Processed 104000 of 167138
Processed 104500 of 167138
Processed 105000 of 167138
Processed 105500 of 167138
Processed 106000 of 167138
Processed 106500 of 167138
Processed 107000 of 167138
Processed 107500 of 167138
Processed 108000 of 167138
Processed 108500 of 167138
Processed 109000 of 167138
Processed 109500 of 167138
Processed 110000 of 167138
Processed 110500 of 167138
Processed 111000 of 167138
Processed 111500 of 167138
Processed 112000 of 167138
Processed 112500 of 167138
Processed 113000 of 167138
Processed 113500 of 167138
Processed 114000 of 167138
Processed 114500 of 167138
Processed 115000 of 167138
Processed 115500 of 167138
Processed 116000 of 167138
Processed 116500 of 167138
Processed 117000 of 167138
Processed 117500 of 167138
Processed 118000 of 167138
Processed 118500 of 167138
Processed 119000 of 167138
Processed 119500 of 167138
Processed 120000 of 167138
Processed 120500 of 167138
Processed 121000 of 167138
Processed 121500 of 167138
Processed 122000 of 167138
Processed 122500 of 167138
Processed 123000 of 167138
Processed 123500 of 167138
Processed 124000 of 167138
Processed 124500 of 167138
Processed 125000 of 167138
Processed 125500 of 167138
Processed 126000 of 167138
Processed 126500 of 167138
Processed 127000 of 167138
Processed 127500 of 167138
Processed 128000 of 167138
Processed 128500 of 167138
Processed 129000 of 167138
Processed 129500 of 167138
Processed 130000 of 167138
Processed 130500 of 167138
Processed 131000 of 167138
Processed 131500 of 167138
Processed 132000 of 167138
Processed 132500 of 167138
Processed 133000 of 167138
Processed 133500 of 167138
Processed 134000 of 167138
Processed 134500 of 167138
Processed 135000 of 167138
Processed 135500 of 167138
Processed 136000 of 167138
Processed 136500 of 167138
Processed 137000 of 167138
Processed 137500 of 167138
Processed 138000 of 167138
Processed 138500 of 167138
Processed 139000 of 167138
Processed 139500 of 167138
Processed 140000 of 167138
Processed 140500 of 167138
Processed 141000 of 167138
Processed 141500 of 167138
Processed 142000 of 167138
Processed 142500 of 167138
Processed 143000 of 167138
Processed 143500 of 167138
Processed 144000 of 167138
Processed 144500 of 167138
Processed 145000 of 167138
Processed 145500 of 167138
Processed 146000 of 167138
Processed 146500 of 167138
Processed 147000 of 167138
Processed 147500 of 167138
Processed 148000 of 167138
Processed 148500 of 167138
Processed 149000 of 167138
Processed 149500 of 167138
Processed 150000 of 167138
Processed 150500 of 167138
Processed 151000 of 167138
Processed 151500 of 167138
Processed 152000 of 167138
Processed 152500 of 167138
Processed 153000 of 167138
Processed 153500 of 167138
Processed 154000 of 167138
Processed 154500 of 167138
Processed 155000 of 167138
Processed 155500 of 167138
Processed 156000 of 167138
Processed 156500 of 167138
Processed 157000 of 167138
Processed 157500 of 167138
Processed 158000 of 167138
Processed 158500 of 167138
Processed 159000 of 167138
Processed 159500 of 167138
Processed 160000 of 167138
Processed 160500 of 167138
Processed 161000 of 167138
Processed 161500 of 167138
Processed 162000 of 167138
Processed 162500 of 167138
Processed 163000 of 167138
Processed 163500 of 167138
Processed 164000 of 167138
Processed 164500 of 167138
Processed 165000 of 167138
Processed 165500 of 167138
Processed 166000 of 167138
Processed 166500 of 167138
Processed 167000 of 167138
Processed 167500 of 167138

In [30]:
len(embeddings)

167138

In [32]:
from typing import Any


pointstructs = []
i=1
for embedding, data in zip(embeddings, data_to_embed):
    pointstructs.append(
        PointStruct(
            id=i,
            vector={
                "text-embedding-3-small": embedding
            },
            payload=data
        )
    )
    i += 1

In [33]:
pointstructs[0].vector

{'text-embedding-3-small': [0.0029163360595703125,
  0.0262298583984375,
  -0.006984710693359375,
  -0.0176239013671875,
  -0.047576904296875,
  -0.042144775390625,
  0.036956787109375,
  -0.017059326171875,
  0.026397705078125,
  0.016845703125,
  -0.02752685546875,
  -0.03546142578125,
  -0.06414794921875,
  0.0679931640625,
  0.00897216796875,
  0.0244598388671875,
  -0.033416748046875,
  -0.038482666015625,
  -0.0024356842041015625,
  0.0247955322265625,
  -0.005519866943359375,
  0.056854248046875,
  0.0007410049438476562,
  -0.0034427642822265625,
  0.0160980224609375,
  -0.0170745849609375,
  0.033111572265625,
  0.0187530517578125,
  0.032440185546875,
  0.0025844573974609375,
  -0.016937255859375,
  -0.03582763671875,
  -0.0018634796142578125,
  -0.052764892578125,
  -0.006114959716796875,
  0.0090789794921875,
  -0.0027179718017578125,
  -0.02593994140625,
  0.0159759521484375,
  -0.042449951171875,
  -0.0106658935546875,
  0.07763671875,
  0.0017871856689453125,
  -0.00304412841796875,
  0.01412200927734375,
  -0.030487060546875,
  0.01360321044921875,
  0.033935546875,
  -0.025054931640625,
  -0.028289794921875,
  -0.01091766357421875,
  0.03179931640625,
  0.003337860107421875,
  -0.01026153564453125,
  0.0200042724609375,
  -0.0328369140625,
  -0.00183868408203125,
  0.006122589111328125,
  0.0037899017333984375,
  -0.05657958984375,
  0.008453369140625,
  -0.017852783203125,
  0.0221405029296875,
  -0.0081329345703125,
  -0.001155853271484375,
  -0.04840087890625,
  0.0325927734375,
  -0.04669189453125,
  0.00479888916015625,
  -0.01081085205078125,
  -0.01073455810546875,
  -0.0254058837890625,
  -0.059906005859375,
  0.0005221366882324219,
  -0.0300140380859375,
  0.04693603515625,
  0.0091094970703125,
  -0.03680419921875,
  0.005985260009765625,
  0.03045654296875,
  -0.0275115966796875,
  0.0128173828125,
  -0.052215576171875,
  0.034088134765625,
  -0.045928955078125,
  -0.0237884521484375,
  -0.030517578125,
  -0.01351165771484375,
  -0.0167388916015625,
  -0.035888671875,
  -0.0643310546875,
  0.00554656982421875,
  0.0516357421875,
  0.0106964111328125,
  -0.049957275390625,
  -0.002994537353515625,
  -0.005908966064453125,
  0.031646728515625,
  0.00505828857421875,
  -0.033172607421875,
  -0.01136016845703125,
  0.00787353515625,
  0.001316070556640625,
  -0.038360595703125,
  0.0196990966796875,
  -0.06890869140625,
  0.005817413330078125,
  0.016754150390625,
  0.0165863037109375,
  0.026397705078125,
  -0.024749755859375,
  0.0311431884765625,
  -0.023651123046875,
  0.0772705078125,
  -0.0313720703125,
  -0.0167388916015625,
  0.0214691162109375,
  0.03717041015625,
  -0.048553466796875,
  0.015716552734375,
  0.00131988525390625,
  0.007556915283203125,
  -0.01153564453125,
  0.048004150390625,
  0.06671142578125,
  -0.022857666015625,
  0.06536865234375,
  -0.01139068603515625,
  -0.0021514892578125,
  -0.0125579833984375,
  0.025054931640625,
  0.024658203125,
  0.01514434814453125,
  -0.0028705596923828125,
  -0.052947998046875,
  0.015869140625,
  -0.031768798828125,
  -0.0239105224609375,
  0.006618499755859375,
  -0.024810791015625,
  -0.041961669921875,
  -0.04388427734375,
  0.02044677734375,
  -0.0167388916015625,
  0.03765869140625,
  0.01129150390625,
  0.01507568359375,
  0.0015106201171875,
  0.002346038818359375,
  0.031982421875,
  -0.0253143310546875,
  -0.00623321533203125,
  -0.048736572265625,
  -0.0517578125,
  -0.0165252685546875,
  -0.02978515625,
  0.01406097412109375,
  0.04541015625,
  0.0009684562683105469,
  -0.00714111328125,
  0.002410888671875,
  0.00899505615234375,
  -0.0013427734375,
  -0.0203094482421875,
  0.0250396728515625,
  0.031463623046875,
  -0.0161895751953125,
  0.00640869140625,
  -0.036773681640625,
  -0.01062774658203125,
  0.0160980224609375,
  0.01421356201171875,
  -0.01131439208984375,
  -0.03411865234375,
  0.006244659423828125,
  -0.048980712890625,
  0.01995849609375,
  -0.046356201171875,
  -0.021636962890625,
  0.004291534423828125,
  0.023101806640625,
  0.011474609375,
  0.05096435546875,
  0.0016679763793945312,
  -0.0133514404296875,
  0.047637939453125,
  -0.0248565673828125,
  0.0106353759765625,
  0.0025539398193359375,
  -0.011260986328125,
  -0.0176544189453125,
  0.0035610198974609375,
  0.0195159912109375,
  0.0279388427734375,
  -0.01174163818359375,
  0.003612518310546875,
  -0.002132415771484375,
  -0.0038356781005859375,
  -0.04168701171875,
  -0.0239105224609375,
  0.01473236083984375,
  -0.030517578125,
  0.07421875,
  0.0120391845703125,
  -0.024658203125,
  -0.034759521484375,
  -0.0035247802734375,
  0.005550384521484375,
  -0.034912109375,
  -0.0004165172576904297,
  0.0022869110107421875,
  -0.0189208984375,
  -0.01453399658203125,
  -0.01216888427734375,
  0.007396697998046875,
  0.0164642333984375,
  -0.00724029541015625,
  0.051727294921875,
  0.013580322265625,
  0.0218963623046875,
  0.01139068603515625,
  -0.0026073455810546875,
  -0.0225372314453125,
  -0.002086639404296875,
  -0.0277557373046875,
  0.01363372802734375,
  -0.00160980224609375,
  -0.0218658447265625,
  0.0357666015625,
  -0.016510009765625,
  -0.0099029541015625,
  0.0221710205078125,
  -0.04718017578125,
  0.0191497802734375,
  0.0176239013671875,
  0.038604736328125,
  -0.00583648681640625,
  0.009765625,
  0.004993438720703125,
  -0.0299224853515625,
  0.0211029052734375,
  -0.03936767578125,
  0.038055419921875,
  0.033843994140625,
  0.02545166015625,
  -0.017120361328125,
  0.012725830078125,
  -0.017913818359375,
  0.00988006591796875,
  -0.03369140625,
  0.02734375,
  0.05322265625,
  0.05126953125,
  0.0065155029296875,
  0.025299072265625,
  0.0265960693359375,
  -0.03436279296875,
  0.040771484375,
  -0.0098419189453125,
  -0.04498291015625,
  -0.0311431884765625,
  -0.0021648406982421875,
  -0.005809783935546875,
  0.01441192626953125,
  -0.040191650390625,
  -0.012237548828125,
  0.0289306640625,
  0.00547027587890625,
  0.033660888671875,
  -0.0003352165222167969,
  -0.042327880859375,
  -0.021820068359375,
  -0.004962921142578125,
  0.0174407958984375,
  0.017852783203125,
  0.0199737548828125,
  -0.018524169921875,
  0.01947021484375,
  -0.00470733642578125,
  0.05035400390625,
  0.007549285888671875,
  0.01641845703125,
  -0.048614501953125,
  -0.0169830322265625,
  0.0182037353515625,
  0.00914764404296875,
  0.05810546875,
  -0.015228271484375,
  0.0144805908203125,
  0.00998687744140625,
  -0.0089569091796875,
  -0.0283355712890625,
  0.0247650146484375,
  -0.0244140625,
  -0.052459716796875,
  0.01001739501953125,
  0.0249481201171875,
  0.0212249755859375,
  -0.0292510986328125,
  -0.0012798309326171875,
  0.052642822265625,
  0.032867431640625,
  -0.0006103515625,
  0.0192413330078125,
  0.0033702850341796875,
  0.0552978515625,
  0.04034423828125,
  -0.030029296875,
  -0.0638427734375,
  -0.01806640625,
  0.022003173828125,
  0.060516357421875,
  0.01348114013671875,
  -0.014129638671875,
  0.01287841796875,
  -0.032012939453125,
  0.0268402099609375,
  -0.080078125,
  -0.00524139404296875,
  -0.03326416015625,
  0.004413604736328125,
  -0.05621337890625,
  0.01056671142578125,
  -0.0196380615234375,
  0.022918701171875,
  -0.03167724609375,
  0.01148223876953125,
  0.005107879638671875,
  -0.032958984375,
  -0.053955078125,
  -0.05035400390625,
  -0.00841522216796875,
  -0.016021728515625,
  0.0211944580078125,
  -0.0206451416015625,
  0.0045013427734375,
  0.02728271484375,
  0.00785064697265625,
  -0.07330322265625,
  -0.024871826171875,
  0.0027523040771484375,
  -0.03564453125,
  -0.017730712890625,
  0.0275726318359375,
  0.0213623046875,
  -0.025238037109375,
  0.0003540515899658203,
  0.0030803680419921875,
  0.0288848876953125,
  -0.0174407958984375,
  -0.050048828125,
  -0.03350830078125,
  -0.0018062591552734375,
  -0.01399993896484375,
  0.075927734375,
  -0.003658294677734375,
  -0.00469207763671875,
  -0.0102386474609375,
  -0.033111572265625,
  -0.0026035308837890625,
  0.00952911376953125,
  7.331371307373047e-05,
  -0.040435791015625,
  -0.0169830322265625,
  -0.039337158203125,
  -0.00431060791015625,
  -0.01250457763671875,
  -0.00711822509765625,
  -0.0259246826171875,
  0.0191192626953125,
  -0.0011749267578125,
  0.023284912109375,
  0.013763427734375,
  0.022705078125,
  -0.058441162109375,
  0.0216064453125,
  0.0197906494140625,
  -0.01537322998046875,
  -0.056976318359375,
  0.0035762786865234375,
  0.0159912109375,
  -0.0299224853515625,
  -0.01015472412109375,
  -0.00891876220703125,
  0.01120758056640625,
  0.0396728515625,
  -0.0167236328125,
  0.030120849609375,
  -0.044769287109375,
  -0.00516510009765625,
  0.00461578369140625,
  -0.0024890899658203125,
  -0.01812744140625,
  -0.025909423828125,
  0.0235137939453125,
  -0.004711151123046875,
  0.005565643310546875,
  0.0291900634765625,
  -0.002025604248046875,
  0.0423583984375,
  0.0150146484375,
  -0.047210693359375,
  -0.06646728515625,
  0.06903076171875,
  -0.00696563720703125,
  -0.01053619384765625,
  -0.0208587646484375,
  0.013519287109375,
  0.043243408203125,
  -0.00180816650390625,
  0.00814056396484375,
  -0.05487060546875,
  0.029632568359375,
  0.006488800048828125,
  0.00415802001953125,
  0.0298309326171875,
  0.01300811767578125,
  0.01922607421875,
  0.07135009765625,
  0.009552001953125,
  0.035247802734375,
  -0.0162353515625,
  -0.0103302001953125,
  0.035308837890625,
  0.0121307373046875,
  0.039215087890625,
  -0.047882080078125,
  -0.0004127025604248047,
  0.01555633544921875,
  -0.060028076171875,
  -0.059326171875,
  0.0063934326171875,
  0.002475738525390625,
  0.01380157470703125,
  -0.008331298828125,
  0.0044403076171875,
  -0.105224609375,
  0.0294189453125,
  -0.0254364013671875,
  -0.00962066650390625,
  0.00923919677734375,
  -0.0390625,
  -0.036224365234375,
  -0.05340576171875,
  -0.047119140625,
  0.0240325927734375,
  0.02880859375,
  0.051971435546875,
  0.041839599609375,
  -0.0015344619750976562,
  -0.057647705078125,
  -0.054107666015625,
  -0.0911865234375,
  0.024444580078125,
  -0.0029277801513671875,
  0.0164794921875,
  0.03521728515625,
  -0.005626678466796875,
  -0.0880126953125,
  -0.0199432373046875,
  -0.040863037109375,
  -0.00318145751953125,
  0.00865936279296875,
  0.01416778564453125,
  0.00511932373046875,
  0.032958984375,
  0.004917144775390625,
  0.0257415771484375,
  -0.0279693603515625,
  0.01552581787109375,
  -0.0027713775634765625,
  -0.0254669189453125,
  0.021270751953125,
  0.00628662109375,
  -0.0005846023559570312,
  -0.00362396240234375,
  0.0264434814453125,
  -0.0030918121337890625,
  0.02777099609375,
  -0.04290771484375,
  -0.0303497314453125,
  0.04180908203125,
  -0.0251312255859375,
  0.045013427734375,
  0.00814056396484375,
  0.0217742919921875,
  0.02227783203125,
  0.0045623779296875,
  -0.09027099609375,
  -0.04779052734375,
  0.0091552734375,
  -0.022308349609375,
  0.0394287109375,
  -0.0161285400390625,
  0.0024566650390625,
  0.04119873046875,
  0.0004794597625732422,
  0.01424407958984375,
  0.00687408447265625,
  0.03289794921875,
  -0.033721923828125,
  0.005222320556640625,
  0.01416778564453125,
  0.0731201171875,
  0.01152801513671875,
  0.033966064453125,
  -0.009613037109375,
  -0.0191802978515625,
  0.0020427703857421875,
  -0.0197601318359375,
  -0.0199127197265625,
  0.0523681640625,
  -0.0298919677734375,
  0.01155853271484375,
  0.0118255615234375,
  -0.00872039794921875,
  0.0311126708984375,
  0.04681396484375,
  -0.022003173828125,
  0.01287841796875,
  0.016998291015625,
  -0.01413726806640625,
  0.02276611328125,
  0.00919342041015625,
  -0.0219879150390625,
  0.00189971923828125,
  -0.0204620361328125,
  0.006061553955078125,
  -0.032806396484375,
  -0.056182861328125,
  -0.002590179443359375,
  0.0095672607421875,
  -0.040252685546875,
  0.0129241943359375,
  -0.0184326171875,
  -0.034942626953125,
  0.0272369384765625,
  -0.01104736328125,
  -0.02728271484375,
  -0.00995635986328125,
  0.0182037353515625,
  0.00188446044921875,
  -0.007598876953125,
  -0.0013456344604492188,
  -0.006816864013671875,
  -0.0130767822265625,
  -0.005893707275390625,
  0.0013265609741210938,
  -0.0014619827270507812,
  0.03851318359375,
  -0.01318359375,
  -0.0235748291015625,
  0.0416259765625,
  0.01020050048828125,
  0.0048065185546875,
  -0.0243682861328125,
  0.031494140625,
  0.0192413330078125,
  -0.016815185546875,
  -0.0006937980651855469,
  0.005825042724609375,
  -0.01202392578125,
  0.018524169921875,
  0.034149169921875,
  0.028961181640625,
  0.0238800048828125,
  -0.007663726806640625,
  0.00464630126953125,
  -0.00846099853515625,
  0.003513336181640625,
  -0.009857177734375,
  0.00476837158203125,
  -0.006504058837890625,
  0.0208587646484375,
  0.0110321044921875,
  0.025146484375,
  0.07147216796875,
  -0.04364013671875,
  0.00948333740234375,
  0.00923919677734375,
  -0.00891876220703125,
  -0.041961669921875,
  0.0176849365234375,
  0.0251922607421875,
  -0.00548553466796875,
  -0.017242431640625,
  0.0011491775512695312,
  -0.03289794921875,
  0.032470703125,
  0.0230560302734375,
  5.030632019042969e-05,
  -0.006031036376953125,
  -0.01044464111328125,
  -0.0210418701171875,
  -0.003204345703125,
  0.0098114013671875,
  0.007373809814453125,
  -0.005840301513671875,
  0.05029296875,
  0.01407623291015625,
  0.005611419677734375,
  0.0129547119140625,
  -0.01239776611328125,
  -0.0231475830078125,
  -0.011383056640625,
  0.042236328125,
  -0.0182952880859375,
  -0.00391387939453125,
  0.0241546630859375,
  -0.0142059326171875,
  0.01085662841796875,
  0.00537872314453125,
  -0.0081787109375,
  0.0137176513671875,
  -0.039398193359375,
  -0.0036945343017578125,
  0.0068359375,
  -0.00510406494140625,
  0.0157470703125,
  -0.00823211669921875,
  -0.050994873046875,
  -0.017730712890625,
  0.016571044921875,
  0.027191162109375,
  -0.0105133056640625,
  0.0797119140625,
  0.00958251953125,
  -0.060760498046875,
  0.043243408203125,
  0.0017995834350585938,
  0.0325927734375,
  0.0511474609375,
  0.01038360595703125,
  -0.01161956787109375,
  -0.0029087066650390625,
  -0.020782470703125,
  -0.0083160400390625,
  0.016143798828125,
  -0.022613525390625,
  -0.005321502685546875,
  -0.01430511474609375,
  0.04473876953125,
  0.017608642578125,
  -0.042236328125,
  0.0092620849609375,
  -0.041778564453125,
  0.00989532470703125,
  0.0009484291076660156,
  -0.0214996337890625,
  -0.045867919921875,
  0.00962066650390625,
  -0.00740814208984375,
  0.04254150390625,
  -0.01386260986328125,
  -0.0011806488037109375,
  0.06011962890625,
  -0.015899658203125,
  0.042877197265625,
  -0.01120758056640625,
  -0.033966064453125,
  -0.00742340087890625,
  0.053985595703125,
  0.0019664764404296875,
  0.0083160400390625,
  0.01462554931640625,
  0.0186309814453125,
  0.0195159912109375,
  -0.0263824462890625,
  0.023223876953125,
  -0.00992584228515625,
  0.034088134765625,
  -0.05010986328125,
  -0.032989501953125,
  -0.03546142578125,
  0.048095703125,
  -0.028778076171875,
  0.01500701904296875,
  -0.0313720703125,
  -0.004390716552734375,
  0.0257110595703125,
  0.00992584228515625,
  -0.0007443428039550781,
  -0.017852783203125,
  -0.0206146240234375,
  -0.042327880859375,
  0.04669189453125,
  0.00980377197265625,
  0.01788330078125,
  -0.00864410400390625,
  0.023681640625,
  0.0003657341003417969,
  0.0119171142578125,
  0.027099609375,
  0.0017852783203125,
  0.03143310546875,
  0.01230621337890625,
  0.0189666748046875,
  -0.056304931640625,
  0.020233154296875,
  0.03814697265625,
  -0.00946044921875,
  -0.002231597900390625,
  0.006168365478515625,
  0.005401611328125,
  -0.0156707763671875,
  -0.01036834716796875,
  -0.0167694091796875,
  0.0023708343505859375,
  0.032745361328125,
  -0.00959014892578125,
  -0.0005950927734375,
  -0.018768310546875,
  -0.003124237060546875,
  0.032440185546875,
  0.05255126953125,
  -0.0189666748046875,
  0.02191162109375,
  0.00557708740234375,
  0.006938934326171875,
  -0.006160736083984375,
  0.029632568359375,
  0.03265380859375,
  0.005290985107421875,
  0.012908935546875,
  -0.018829345703125,
  0.01265716552734375,
  -0.0260772705078125,
  -0.022552490234375,
  -0.000377655029296875,
  -0.010650634765625,
  0.0169219970703125,
  -0.019073486328125,
  -0.055389404296875,
  -0.0015544891357421875,
  -0.0225372314453125,
  -0.002712249755859375,
  0.023223876953125,
  0.005519866943359375,
  0.006427764892578125,
  0.006740570068359375,
  0.034332275390625,
  0.0355224609375,
  0.01241302490234375,
  -0.00856781005859375,
  0.01103973388671875,
  -0.024200439453125,
  0.0257110595703125,
  -0.006328582763671875,
  -0.0020236968994140625,
  -0.052001953125,
  0.01282501220703125,
  0.0131988525390625,
  0.01160430908203125,
  0.003543853759765625,
  0.0123748779296875,
  -0.0301513671875,
  0.0179901123046875,
  -0.0232696533203125,
  0.023101806640625,
  -0.015594482421875,
  0.005023956298828125,
  0.019317626953125,
  -0.0027523040771484375,
  -0.0244903564453125,
  0.0214385986328125,
  0.01000213623046875,
  -0.03826904296875,
  -0.0204315185546875,
  -0.00833892822265625,
  0.035186767578125,
  0.024932861328125,
  -0.021820068359375,
  -0.032135009765625,
  0.01332855224609375,
  -0.0024318695068359375,
  6.73532485961914e-05,
  0.0122222900390625,
  -0.013641357421875,
  -0.0009145736694335938,
  0.00390625,
  0.01328277587890625,
  -0.017913818359375,
  -0.01715087890625,
  0.01788330078125,
  -0.01000213623046875,
  -0.01363372802734375,
  -0.031494140625,
  0.01381683349609375,
  -0.0157470703125,
  -0.018768310546875,
  -0.030426025390625,
  -0.01357269287109375,
  -0.00479888916015625,
  0.032806396484375,
  -0.0164794921875,
  0.0138092041015625,
  0.01593017578125,
  -0.058441162109375,
  -0.01189422607421875,
  0.00630950927734375,
  -0.033111572265625,
  -0.0016260147094726562,
  0.039947509765625,
  0.0005478858947753906,
  -0.038116455078125,
  -0.0234222412109375,
  0.003326416015625,
  -0.01171112060546875,
  -0.0166168212890625,
  -0.00862884521484375,
  0.016693115234375,
  0.01163482666015625,
  -0.004673004150390625,
  -0.01739501953125,
  0.0196533203125,
  0.0384521484375,
  0.021270751953125,
  0.0006337165832519531,
  0.0191192626953125,
  0.00627899169921875,
  -0.0384521484375,
  -0.0069427490234375,
  0.0172119140625,
  -0.0203704833984375,
  0.0251007080078125,
  -0.018341064453125,
  -0.02386474609375,
  0.0261993408203125,
  0.035003662109375,
  -0.04705810546875,
  0.01678466796875,
  0.002788543701171875,
  -0.048095703125,
  -0.016754150390625,
  -0.022674560546875,
  0.00469970703125,
  -0.004150390625,
  0.0085601806640625,
  -0.0033016204833984375,
  -0.03265380859375,
  0.0416259765625,
  0.0004911422729492188,
  -0.0601806640625,
  0.0133819580078125,
  -0.0004334449768066406,
  0.03564453125,
  -0.0292205810546875,
  0.0269317626953125,
  -0.01067352294921875,
  -0.00695037841796875,
  0.0010433197021484375,
  -0.010345458984375,
  0.00010061264038085938,
  0.007503509521484375,
  0.0222015380859375,
  0.01212310791015625,
  0.005924224853515625,
  -0.00833892822265625,
  0.0031108856201171875,
  0.01019287109375,
  -0.0247039794921875,
  -0.01058197021484375,
  -0.025604248046875,
  0.0008893013000488281,
  0.00336456298828125,
  -0.0058746337890625,
  0.0035610198974609375,
  -0.01459503173828125,
  0.00861358642578125,
  -0.02447509765625,
  0.00833892822265625,
  0.0182342529296875,
  -0.0020809173583984375,
  0.03765869140625,
  0.0012664794921875,
  -0.007694244384765625,
  0.027984619140625,
  -0.003993988037109375,
  0.01154327392578125,
  -0.00514984130859375,
  -0.005886077880859375,
  -0.00151824951171875,
  0.016998291015625,
  -0.006603240966796875,
  0.010894775390625,
  0.0298919677734375,
  0.0218963623046875,
  0.02978515625,
  0.007381439208984375,
  0.011260986328125,
  -0.0194091796875,
  -0.07586669921875,
  0.01459503173828125,
  -0.0008635520935058594,
  -0.050140380859375,
  -0.00626373291015625,
  0.0077972412109375,
  0.05352783203125,
  0.0270538330078125,
  -0.033935546875,
  -0.0193939208984375,

In [34]:
batch_size_qdrant = 100
counter = 1
for i in range(0, len(pointstructs), batch_size_qdrant):
    batch = pointstructs[i:i + batch_size_qdrant]
    qdrant_client.upsert(
        collection_name="Amazon-reviews-collection-01",
        points=batch,
        wait=True
    )
    print(f"Processed {counter * batch_size_qdrant} of {len(pointstructs)}")
    counter += 1

Processed 100 of 167138
Processed 200 of 167138
Processed 300 of 167138
Processed 400 of 167138
Processed 500 of 167138
Processed 600 of 167138
Processed 700 of 167138
Processed 800 of 167138
Processed 900 of 167138
Processed 1000 of 167138
Processed 1100 of 167138
Processed 1200 of 167138
Processed 1300 of 167138
Processed 1400 of 167138
Processed 1500 of 167138
Processed 1600 of 167138
Processed 1700 of 167138
Processed 1800 of 167138
Processed 1900 of 167138
Processed 2000 of 167138
Processed 2100 of 167138
Processed 2200 of 167138
Processed 2300 of 167138
Processed 2400 of 167138
Processed 2500 of 167138
Processed 2600 of 167138
Processed 2700 of 167138
Processed 2800 of 167138
Processed 2900 of 167138
Processed 3000 of 167138
Processed 3100 of 167138
Processed 3200 of 167138
Processed 3300 of 167138
Processed 3400 of 167138
Processed 3500 of 167138
Processed 3600 of 167138
Processed 3700 of 167138
Processed 3800 of 167138
Processed 3900 of 167138
Processed 4000 of 167138
Processed 4100 of 167138
Processed 4200 of 167138
Processed 4300 of 167138
Processed 4400 of 167138
Processed 4500 of 167138
Processed 4600 of 167138
Processed 4700 of 167138
Processed 4800 of 167138
Processed 4900 of 167138
Processed 5000 of 167138
Processed 5100 of 167138
Processed 5200 of 167138
Processed 5300 of 167138
Processed 5400 of 167138
Processed 5500 of 167138
Processed 5600 of 167138
Processed 5700 of 167138
Processed 5800 of 167138
Processed 5900 of 167138
Processed 6000 of 167138
Processed 6100 of 167138
Processed 6200 of 167138
Processed 6300 of 167138
Processed 6400 of 167138
Processed 6500 of 167138
Processed 6600 of 167138
Processed 6700 of 167138
Processed 6800 of 167138
Processed 6900 of 167138
Processed 7000 of 167138
Processed 7100 of 167138
Processed 7200 of 167138
Processed 7300 of 167138
Processed 7400 of 167138
Processed 7500 of 167138
Processed 7600 of 167138
Processed 7700 of 167138
Processed 7800 of 167138
Processed 7900 of 167138
Processed 8000 of 167138
Processed 8100 of 167138
Processed 8200 of 167138
Processed 8300 of 167138
Processed 8400 of 167138
Processed 8500 of 167138
Processed 8600 of 167138
Processed 8700 of 167138
Processed 8800 of 167138
Processed 8900 of 167138
Processed 9000 of 167138
Processed 9100 of 167138
Processed 9200 of 167138
Processed 9300 of 167138
Processed 9400 of 167138
Processed 9500 of 167138
Processed 9600 of 167138
Processed 9700 of 167138
Processed 9800 of 167138
Processed 9900 of 167138
Processed 10000 of 167138
Processed 10100 of 167138
Processed 10200 of 167138
Processed 10300 of 167138
Processed 10400 of 167138
Processed 10500 of 167138
Processed 10600 of 167138
Processed 10700 of 167138
Processed 10800 of 167138
Processed 10900 of 167138
Processed 11000 of 167138
Processed 11100 of 167138
Processed 11200 of 167138
Processed 11300 of 167138
Processed 11400 of 167138
Processed 11500 of 167138
Processed 11600 of 167138
Processed 11700 of 167138
Processed 11800 of 167138
Processed 11900 of 167138
Processed 12000 of 167138
Processed 12100 of 167138
Processed 12200 of 167138
Processed 12300 of 167138
Processed 12400 of 167138
Processed 12500 of 167138
Processed 12600 of 167138
Processed 12700 of 167138
Processed 12800 of 167138
Processed 12900 of 167138
Processed 13000 of 167138
Processed 13100 of 167138
Processed 13200 of 167138
Processed 13300 of 167138
Processed 13400 of 167138
Processed 13500 of 167138
Processed 13600 of 167138
Processed 13700 of 167138
Processed 13800 of 167138
Processed 13900 of 167138
Processed 14000 of 167138
Processed 14100 of 167138
Processed 14200 of 167138
Processed 14300 of 167138
Processed 14400 of 167138
Processed 14500 of 167138
Processed 14600 of 167138
Processed 14700 of 167138
Processed 14800 of 167138
Processed 14900 of 167138
Processed 15000 of 167138
Processed 15100 of 167138
Processed 15200 of 167138
Processed 15300 of 167138
Processed 15400 of 167138
Processed 15500 of 167138
Processed 15600 of 167138
Processed 15700 of 167138
Processed 15800 of 167138
Processed 15900 of 167138
Processed 16000 of 167138
Processed 16100 of 167138
Processed 16200 of 167138
Processed 16300 of 167138
Processed 16400 of 167138
Processed 16500 of 167138
Processed 16600 of 167138
Processed 16700 of 167138
Processed 16800 of 167138
Processed 16900 of 167138
Processed 17000 of 167138
Processed 17100 of 167138
Processed 17200 of 167138
Processed 17300 of 167138
Processed 17400 of 167138
Processed 17500 of 167138
Processed 17600 of 167138
Processed 17700 of 167138
Processed 17800 of 167138
Processed 17900 of 167138
Processed 18000 of 167138
Processed 18100 of 167138
Processed 18200 of 167138
Processed 18300 of 167138
Processed 18400 of 167138
Processed 18500 of 167138
Processed 18600 of 167138
Processed 18700 of 167138
Processed 18800 of 167138
Processed 18900 of 167138
Processed 19000 of 167138
Processed 19100 of 167138
Processed 19200 of 167138
Processed 19300 of 167138
Processed 19400 of 167138
Processed 19500 of 167138
Processed 19600 of 167138
Processed 19700 of 167138
Processed 19800 of 167138
Processed 19900 of 167138
Processed 20000 of 167138
Processed 20100 of 167138
Processed 20200 of 167138
Processed 20300 of 167138
Processed 20400 of 167138
Processed 20500 of 167138
Processed 20600 of 167138
Processed 20700 of 167138
Processed 20800 of 167138
Processed 20900 of 167138
Processed 21000 of 167138
Processed 21100 of 167138
Processed 21200 of 167138
Processed 21300 of 167138
Processed 21400 of 167138
Processed 21500 of 167138
Processed 21600 of 167138
Processed 21700 of 167138
Processed 21800 of 167138
Processed 21900 of 167138
Processed 22000 of 167138
Processed 22100 of 167138
Processed 22200 of 167138
Processed 22300 of 167138
Processed 22400 of 167138
Processed 22500 of 167138
Processed 22600 of 167138
Processed 22700 of 167138
Processed 22800 of 167138
Processed 22900 of 167138
Processed 23000 of 167138
Processed 23100 of 167138
Processed 23200 of 167138
Processed 23300 of 167138
Processed 23400 of 167138
Processed 23500 of 167138
Processed 23600 of 167138
Processed 23700 of 167138
Processed 23800 of 167138
Processed 23900 of 167138
Processed 24000 of 167138
Processed 24100 of 167138
Processed 24200 of 167138
Processed 24300 of 167138
Processed 24400 of 167138
Processed 24500 of 167138
Processed 24600 of 167138
Processed 24700 of 167138
Processed 24800 of 167138
Processed 24900 of 167138
Processed 25000 of 167138
Processed 25100 of 167138
Processed 25200 of 167138
Processed 25300 of 167138
Processed 25400 of 167138
Processed 25500 of 167138
Processed 25600 of 167138
Processed 25700 of 167138
Processed 25800 of 167138
Processed 25900 of 167138
Processed 26000 of 167138
Processed 26100 of 167138
Processed 26200 of 167138
Processed 26300 of 167138
Processed 26400 of 167138
Processed 26500 of 167138
Processed 26600 of 167138
Processed 26700 of 167138
Processed 26800 of 167138
Processed 26900 of 167138
Processed 27000 of 167138
Processed 27100 of 167138
Processed 27200 of 167138
Processed 27300 of 167138
Processed 27400 of 167138
Processed 27500 of 167138
Processed 27600 of 167138
Processed 27700 of 167138
Processed 27800 of 167138
Processed 27900 of 167138
Processed 28000 of 167138
Processed 28100 of 167138
Processed 28200 of 167138
Processed 28300 of 167138
Processed 28400 of 167138
Processed 28500 of 167138
Processed 28600 of 167138
Processed 28700 of 167138
Processed 28800 of 167138
Processed 28900 of 167138
Processed 29000 of 167138
Processed 29100 of 167138
Processed 29200 of 167138
Processed 29300 of 167138
Processed 29400 of 167138
Processed 29500 of 167138
Processed 29600 of 167138
Processed 29700 of 167138
Processed 29800 of 167138
Processed 29900 of 167138
Processed 30000 of 167138
Processed 30100 of 167138
Processed 30200 of 167138
Processed 30300 of 167138
Processed 30400 of 167138
Processed 30500 of 167138
Processed 30600 of 167138
Processed 30700 of 167138
Processed 30800 of 167138
Processed 30900 of 167138
Processed 31000 of 167138
Processed 31100 of 167138
Processed 31200 of 167138
Processed 31300 of 167138
Processed 31400 of 167138
Processed 31500 of 167138
Processed 31600 of 167138
Processed 31700 of 167138
Processed 31800 of 167138
Processed 31900 of 167138
Processed 32000 of 167138
Processed 32100 of 167138
Processed 32200 of 167138
Processed 32300 of 167138
Processed 32400 of 167138
Processed 32500 of 167138
Processed 32600 of 167138
Processed 32700 of 167138
Processed 32800 of 167138
Processed 32900 of 167138
Processed 33000 of 167138
Processed 33100 of 167138
Processed 33200 of 167138
Processed 33300 of 167138
Processed 33400 of 167138
Processed 33500 of 167138
Processed 33600 of 167138
Processed 33700 of 167138
Processed 33800 of 167138
Processed 33900 of 167138
Processed 34000 of 167138
Processed 34100 of 167138
Processed 34200 of 167138
Processed 34300 of 167138
Processed 34400 of 167138
Processed 34500 of 167138
Processed 34600 of 167138
Processed 34700 of 167138
Processed 34800 of 167138
Processed 34900 of 167138
Processed 35000 of 167138
Processed 35100 of 167138
Processed 35200 of 167138
Processed 35300 of 167138
Processed 35400 of 167138
Processed 35500 of 167138
Processed 35600 of 167138
Processed 35700 of 167138
Processed 35800 of 167138
Processed 35900 of 167138
Processed 36000 of 167138
Processed 36100 of 167138
Processed 36200 of 167138
Processed 36300 of 167138
Processed 36400 of 167138
Processed 36500 of 167138
Processed 36600 of 167138
Processed 36700 of 167138
Processed 36800 of 167138
Processed 36900 of 167138
Processed 37000 of 167138
Processed 37100 of 167138
Processed 37200 of 167138
Processed 37300 of 167138
Processed 37400 of 167138
Processed 37500 of 167138
Processed 37600 of 167138
Processed 37700 of 167138
Processed 37800 of 167138
Processed 37900 of 167138
Processed 38000 of 167138
Processed 38100 of 167138
Processed 38200 of 167138
Processed 38300 of 167138
Processed 38400 of 167138
Processed 38500 of 167138
Processed 38600 of 167138
Processed 38700 of 167138
Processed 38800 of 167138
Processed 38900 of 167138
Processed 39000 of 167138
Processed 39100 of 167138
Processed 39200 of 167138
Processed 39300 of 167138
Processed 39400 of 167138
Processed 39500 of 167138
Processed 39600 of 167138
Processed 39700 of 167138
Processed 39800 of 167138
Processed 39900 of 167138
Processed 40000 of 167138
Processed 40100 of 167138
Processed 40200 of 167138
Processed 40300 of 167138
Processed 40400 of 167138
Processed 40500 of 167138
Processed 40600 of 167138
Processed 40700 of 167138
Processed 40800 of 167138
Processed 40900 of 167138
Processed 41000 of 167138
Processed 41100 of 167138
Processed 41200 of 167138
Processed 41300 of 167138
Processed 41400 of 167138
Processed 41500 of 167138
Processed 41600 of 167138
Processed 41700 of 167138
Processed 41800 of 167138
Processed 41900 of 167138
Processed 42000 of 167138
Processed 42100 of 167138
Processed 42200 of 167138
Processed 42300 of 167138
Processed 42400 of 167138
Processed 42500 of 167138
Processed 42600 of 167138
Processed 42700 of 167138
Processed 42800 of 167138
Processed 42900 of 167138
Processed 43000 of 167138
Processed 43100 of 167138
Processed 43200 of 167138
Processed 43300 of 167138
Processed 43400 of 167138
Processed 43500 of 167138
Processed 43600 of 167138
Processed 43700 of 167138
Processed 43800 of 167138
Processed 43900 of 167138
Processed 44000 of 167138
Processed 44100 of 167138
Processed 44200 of 167138
Processed 44300 of 167138
Processed 44400 of 167138
Processed 44500 of 167138
Processed 44600 of 167138
Processed 44700 of 167138
Processed 44800 of 167138
Processed 44900 of 167138
Processed 45000 of 167138
Processed 45100 of 167138
Processed 45200 of 167138
Processed 45300 of 167138
Processed 45400 of 167138
Processed 45500 of 167138
Processed 45600 of 167138
Processed 45700 of 167138
Processed 45800 of 167138
Processed 45900 of 167138
Processed 46000 of 167138
Processed 46100 of 167138
Processed 46200 of 167138
Processed 46300 of 167138
Processed 46400 of 167138
Processed 46500 of 167138
Processed 46600 of 167138
Processed 46700 of 167138
Processed 46800 of 167138
Processed 46900 of 167138
Processed 47000 of 167138
Processed 47100 of 167138
Processed 47200 of 167138
Processed 47300 of 167138
Processed 47400 of 167138
Processed 47500 of 167138
Processed 47600 of 167138
Processed 47700 of 167138
Processed 47800 of 167138
Processed 47900 of 167138
Processed 48000 of 167138
Processed 48100 of 167138
Processed 48200 of 167138
Processed 48300 of 167138
Processed 48400 of 167138
Processed 48500 of 167138
Processed 48600 of 167138
Processed 48700 of 167138
Processed 48800 of 167138
Processed 48900 of 167138
Processed 49000 of 167138
Processed 49100 of 167138
Processed 49200 of 167138
Processed 49300 of 167138
Processed 49400 of 167138
Processed 49500 of 167138
Processed 49600 of 167138
Processed 49700 of 167138
Processed 49800 of 167138
Processed 49900 of 167138
Processed 50000 of 167138
Processed 50100 of 167138
Processed 50200 of 167138
Processed 50300 of 167138
Processed 50400 of 167138
Processed 50500 of 167138
Processed 50600 of 167138
Processed 50700 of 167138
Processed 50800 of 167138
Processed 50900 of 167138
Processed 51000 of 167138
Processed 51100 of 167138
Processed 51200 of 167138
Processed 51300 of 167138
Processed 51400 of 167138
Processed 51500 of 167138
Processed 51600 of 167138
Processed 51700 of 167138
Processed 51800 of 167138
Processed 51900 of 167138
Processed 52000 of 167138
Processed 52100 of 167138
Processed 52200 of 167138
Processed 52300 of 167138
Processed 52400 of 167138
Processed 52500 of 167138
Processed 52600 of 167138
Processed 52700 of 167138
Processed 52800 of 167138
Processed 52900 of 167138
Processed 53000 of 167138
Processed 53100 of 167138
Processed 53200 of 167138
Processed 53300 of 167138
Processed 53400 of 167138
Processed 53500 of 167138
Processed 53600 of 167138
Processed 53700 of 167138
Processed 53800 of 167138
Processed 53900 of 167138
Processed 54000 of 167138
Processed 54100 of 167138
Processed 54200 of 167138
Processed 54300 of 167138
Processed 54400 of 167138
Processed 54500 of 167138
Processed 54600 of 167138
Processed 54700 of 167138
Processed 54800 of 167138
Processed 54900 of 167138
Processed 55000 of 167138
Processed 55100 of 167138
Processed 55200 of 167138
Processed 55300 of 167138
Processed 55400 of 167138
Processed 55500 of 167138
Processed 55600 of 167138
Processed 55700 of 167138
Processed 55800 of 167138
Processed 55900 of 167138
Processed 56000 of 167138
Processed 56100 of 167138
Processed 56200 of 167138
Processed 56300 of 167138
Processed 56400 of 167138
Processed 56500 of 167138
Processed 56600 of 167138
Processed 56700 of 167138
Processed 56800 of 167138
Processed 56900 of 167138
Processed 57000 of 167138
Processed 57100 of 167138
Processed 57200 of 167138
Processed 57300 of 167138
Processed 57400 of 167138
Processed 57500 of 167138
Processed 57600 of 167138
Processed 57700 of 167138
Processed 57800 of 167138
Processed 57900 of 167138
Processed 58000 of 167138
Processed 58100 of 167138
Processed 58200 of 167138
Processed 58300 of 167138
Processed 58400 of 167138
Processed 58500 of 167138
Processed 58600 of 167138
Processed 58700 of 167138
Processed 58800 of 167138
Processed 58900 of 167138
Processed 59000 of 167138
Processed 59100 of 167138
Processed 59200 of 167138
Processed 59300 of 167138
Processed 59400 of 167138
Processed 59500 of 167138
Processed 59600 of 167138
Processed 59700 of 167138
Processed 59800 of 167138
Processed 59900 of 167138
Processed 60000 of 167138
Processed 60100 of 167138
Processed 60200 of 167138
Processed 60300 of 167138
Processed 60400 of 167138
Processed 60500 of 167138
Processed 60600 of 167138
Processed 60700 of 167138
Processed 60800 of 167138
Processed 60900 of 167138
Processed 61000 of 167138
Processed 61100 of 167138
Processed 61200 of 167138
Processed 61300 of 167138
Processed 61400 of 167138
Processed 61500 of 167138
Processed 61600 of 167138
Processed 61700 of 167138
Processed 61800 of 167138
Processed 61900 of 167138
Processed 62000 of 167138
Processed 62100 of 167138
Processed 62200 of 167138
Processed 62300 of 167138
Processed 62400 of 167138
Processed 62500 of 167138
Processed 62600 of 167138
Processed 62700 of 167138
Processed 62800 of 167138
Processed 62900 of 167138
Processed 63000 of 167138
Processed 63100 of 167138
Processed 63200 of 167138
Processed 63300 of 167138
Processed 63400 of 167138
Processed 63500 of 167138
Processed 63600 of 167138
Processed 63700 of 167138
Processed 63800 of 167138
Processed 63900 of 167138
Processed 64000 of 167138
Processed 64100 of 167138
Processed 64200 of 167138
Processed 64300 of 167138
Processed 64400 of 167138
Processed 64500 of 167138
Processed 64600 of 167138
Processed 64700 of 167138
Processed 64800 of 167138
Processed 64900 of 167138
Processed 65000 of 167138
Processed 65100 of 167138
Processed 65200 of 167138
Processed 65300 of 167138
Processed 65400 of 167138
Processed 65500 of 167138
Processed 65600 of 167138
Processed 65700 of 167138
Processed 65800 of 167138
Processed 65900 of 167138
Processed 66000 of 167138
Processed 66100 of 167138
Processed 66200 of 167138
Processed 66300 of 167138
Processed 66400 of 167138
Processed 66500 of 167138
Processed 66600 of 167138
Processed 66700 of 167138
Processed 66800 of 167138
Processed 66900 of 167138
Processed 67000 of 167138
Processed 67100 of 167138
Processed 67200 of 167138
Processed 67300 of 167138
Processed 67400 of 167138
Processed 67500 of 167138
Processed 67600 of 167138
Processed 67700 of 167138
Processed 67800 of 167138
Processed 67900 of 167138
Processed 68000 of 167138
Processed 68100 of 167138
Processed 68200 of 167138
Processed 68300 of 167138
Processed 68400 of 167138
Processed 68500 of 167138
Processed 68600 of 167138
Processed 68700 of 167138
Processed 68800 of 167138
Processed 68900 of 167138
Processed 69000 of 167138
Processed 69100 of 167138
Processed 69200 of 167138
Processed 69300 of 167138
Processed 69400 of 167138
Processed 69500 of 167138
Processed 69600 of 167138
Processed 69700 of 167138
Processed 69800 of 167138
Processed 69900 of 167138
Processed 70000 of 167138
Processed 70100 of 167138
Processed 70200 of 167138
Processed 70300 of 167138
Processed 70400 of 167138
Processed 70500 of 167138
Processed 70600 of 167138
Processed 70700 of 167138
Processed 70800 of 167138
Processed 70900 of 167138
Processed 71000 of 167138
Processed 71100 of 167138
Processed 71200 of 167138
Processed 71300 of 167138
Processed 71400 of 167138
Processed 71500 of 167138
Processed 71600 of 167138
Processed 71700 of 167138
Processed 71800 of 167138
Processed 71900 of 167138
Processed 72000 of 167138
Processed 72100 of 167138
Processed 72200 of 167138
Processed 72300 of 167138
Processed 72400 of 167138
Processed 72500 of 167138
Processed 72600 of 167138
Processed 72700 of 167138
Processed 72800 of 167138
Processed 72900 of 167138
Processed 73000 of 167138
Processed 73100 of 167138
Processed 73200 of 167138
Processed 73300 of 167138
Processed 73400 of 167138
Processed 73500 of 167138
Processed 73600 of 167138
Processed 73700 of 167138
Processed 73800 of 167138
Processed 73900 of 167138
Processed 74000 of 167138
Processed 74100 of 167138
Processed 74200 of 167138
Processed 74300 of 167138
Processed 74400 of 167138
Processed 74500 of 167138
Processed 74600 of 167138
Processed 74700 of 167138
Processed 74800 of 167138
Processed 74900 of 167138
Processed 75000 of 167138
Processed 75100 of 167138
Processed 75200 of 167138
Processed 75300 of 167138
Processed 75400 of 167138
Processed 75500 of 167138
Processed 75600 of 167138
Processed 75700 of 167138
Processed 75800 of 167138
Processed 75900 of 167138
Processed 76000 of 167138
Processed 76100 of 167138
Processed 76200 of 167138
Processed 76300 of 167138
Processed 76400 of 167138
Processed 76500 of 167138
Processed 76600 of 167138
Processed 76700 of 167138
Processed 76800 of 167138
Processed 76900 of 167138
Processed 77000 of 167138
Processed 77100 of 167138
Processed 77200 of 167138
Processed 77300 of 167138

### A function to run search against reviews on a prefiltered set of product IDs

In [35]:
def retrieve_prefiltered_reviews_data(query, parent_asins, k=5):

    query_embedding = get_embedding(query)

    results = qdrant_client.query_points(
        collection_name="Amazon-reviews-collection-01",
        prefetch=[
            Prefetch(
                query=query_embedding,
                using="text-embedding-3-small",
                filter=Filter(
                    must=[
                        FieldCondition(
                            key="parent_asin",
                            match=MatchAny(
                                any=parent_asins
                            )
                        )
                    ]
                ),
                limit=20
            )
        ],
        query=FusionQuery(fusion="rrf"),
        limit=k
    )
    
    return results

In [40]:
reviews = retrieve_prefiltered_reviews_data("bad_quality", ["B0047T79VS"])
reviews

QueryResponse(points=[ScoredPoint(id=3362, version=36, score=0.5, payload={'preprocessed_data': 'Very poor sound quality ! Very poor sound quality !', 'parent_asin': 'B0047T79VS'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=3963, version=42, score=0.33333334, payload={'preprocessed_data': 'the quality its not very good the quality its not bad but its good<br /><br />i try it with iphone and playbook (no any problem)<br /><br />with banasonic sterio (no any problem)', 'parent_asin': 'B0047T79VS'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=3286, version=35, score=0.25, payload={'preprocessed_data': "Very Low Quality Avoid this. Doesn't work. Good manufacturer, bad nonfunctional product. The sound quality is poor and this product's ability to use the Bluetooth protocol is limited.", 'parent_asin': 'B0047T79VS'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=4680, version=49, score=0.2, payload={'preprocessed_data': 'One Star Sound Quality very BAD !!!', 'parent_asin': 'B0047T79VS'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=4561, version=48, score=0.16666667, payload={'preprocessed_data': "bad Makes the sound quality sound funky. I've leaned my lesson, don't buy cheap its not all eqaul.", 'parent_asin': 'B0047T79VS'}, vector=None, shard_key=None, order_value=None)])

In [42]:
reviews.points

[ScoredPoint(id=3362, version=36, score=0.5, payload={'preprocessed_data': 'Very poor sound quality ! Very poor sound quality !', 'parent_asin': 'B0047T79VS'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=3099, version=33, score=0.33333334, payload={'preprocessed_data': 'Low quality sound Low quality sound! This is the worse quality you can get, is staticky. I used it for my laptop to play in my home theater and it sucks because it take away sound, base, quality & volumen. Do not buy if you are looking to use it for music', 'parent_asin': 'B0047T79VS'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=4548, version=48, score=0.25, payload={'preprocessed_data': "Bad quality sound. Don't waste your money.  Sound quality is bad.  It degrades the already compressed mp3 and sounds like AM radio.", 'parent_asin': 'B0047T79VS'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=3286, version=35, score=0.2, payload={'preprocessed_data': "Very Low Quality Avoid this. Doesn't work. Good manufacturer, bad nonfunctional product. The sound quality is poor and this product's ability to use the Bluetooth protocol is limited.", 'parent_asin': 'B0047T79VS'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=3307, version=36, score=0.16666667, payload={'preprocessed_data': 'Poor Sound Quality Not worth the money, and has....poor sound quality and is really degraded.  Not happy with the purchase, and will be looking for another product that is better quality!', 'parent_asin': 'B0047T79VS'}, vector=None, shard_key=None, order_value=None)]

In [41]:
reviews = retrieve_prefiltered_reviews_data("bad quality", ["B0047T79VS"])
reviews

QueryResponse(points=[ScoredPoint(id=3362, version=36, score=0.5, payload={'preprocessed_data': 'Very poor sound quality ! Very poor sound quality !', 'parent_asin': 'B0047T79VS'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=3099, version=33, score=0.33333334, payload={'preprocessed_data': 'Low quality sound Low quality sound! This is the worse quality you can get, is staticky. I used it for my laptop to play in my home theater and it sucks because it take away sound, base, quality & volumen. Do not buy if you are looking to use it for music', 'parent_asin': 'B0047T79VS'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=4548, version=48, score=0.25, payload={'preprocessed_data': "Bad quality sound. Don't waste your money.  Sound quality is bad.  It degrades the already compressed mp3 and sounds like AM radio.", 'parent_asin': 'B0047T79VS'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=3286, version=35, score=0.2, payload={'preprocessed_data': "Very Low Quality Avoid this. Doesn't work. Good manufacturer, bad nonfunctional product. The sound quality is poor and this product's ability to use the Bluetooth protocol is limited.", 'parent_asin': 'B0047T79VS'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=3307, version=36, score=0.16666667, payload={'preprocessed_data': 'Poor Sound Quality Not worth the money, and has....poor sound quality and is really degraded.  Not happy with the purchase, and will be looking for another product that is better quality!', 'parent_asin': 'B0047T79VS'}, vector=None, shard_key=None, order_value=None)])

In [43]:
reviews.points

[ScoredPoint(id=3362, version=36, score=0.5, payload={'preprocessed_data': 'Very poor sound quality ! Very poor sound quality !', 'parent_asin': 'B0047T79VS'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=3099, version=33, score=0.33333334, payload={'preprocessed_data': 'Low quality sound Low quality sound! This is the worse quality you can get, is staticky. I used it for my laptop to play in my home theater and it sucks because it take away sound, base, quality & volumen. Do not buy if you are looking to use it for music', 'parent_asin': 'B0047T79VS'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=4548, version=48, score=0.25, payload={'preprocessed_data': "Bad quality sound. Don't waste your money.  Sound quality is bad.  It degrades the already compressed mp3 and sounds like AM radio.", 'parent_asin': 'B0047T79VS'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=3286, version=35, score=0.2, payload={'preprocessed_data': "Very Low Quality Avoid this. Doesn't work. Good manufacturer, bad nonfunctional product. The sound quality is poor and this product's ability to use the Bluetooth protocol is limited.", 'parent_asin': 'B0047T79VS'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=3307, version=36, score=0.16666667, payload={'preprocessed_data': 'Poor Sound Quality Not worth the money, and has....poor sound quality and is really degraded.  Not happy with the purchase, and will be looking for another product that is better quality!', 'parent_asin': 'B0047T79VS'}, vector=None, shard_key=None, order_value=None)]

### Define the reviews retrieval tool

In [45]:
def get_embedding(text, model="text-embedding-3-small"):
    response = openai.embeddings.create(
        input=text,
        model=model
    )

    return response.data[0].embedding


def retrieve_prefiltered_reviews_data(query, parent_asins, k=5):

    query_embedding = get_embedding(query)

    qdrant_client = QdrantClient(url="http://localhost:6333")

    results = qdrant_client.query_points(
        collection_name="Amazon-reviews-collection-01",
        prefetch=[
            Prefetch(
                query=query_embedding,
                using="text-embedding-3-small",
                filter=Filter(
                    must=[
                        FieldCondition(
                            key="parent_asin",
                            match=MatchAny(
                                any=parent_asins
                            )
                        )
                    ]
                ),
                limit=20
            )
        ],
        query=FusionQuery(fusion="rrf"),
        limit=k
    )

    retrieved_context_ids = []
    retrieved_context = []
    similarity_scores = []

    for result in results.points:
        retrieved_context_ids.append(result.payload["parent_asin"])
        retrieved_context.append(result.payload["preprocessed_data"])
        similarity_scores.append(result.score)

    return {
        "retrieved_context_ids": retrieved_context_ids,
        "retrieved_context": retrieved_context,
        "similarity_scores": similarity_scores,
    }


def process_reviews_context(context):

    formatted_context = ""

    for id, chunk in zip(context["retrieved_context_ids"], context["retrieved_context"]):
        formatted_context += f"- ID: {id}, user review: {chunk}\n"

    return formatted_context


def get_formatted_reviews_context(query: str, parent_asins: list[str], top_k: int = 5) -> str:

    """Get the top k reviews matching a query for a list of prefiltered items.
    
    Args:
        query: The query to get the top k reviews for
        item_list: The list of item IDs to prefilter for before running the query
        top_k: The number of reviews to retrieve, this should be at least 20 if multipple items are prefiltered
    
    Returns:
        A string of the top k context chunks with IDs prepending each chunk, each representing a review for a given inventory item for a given query.
    """

    retrieved_context = retrieve_prefiltered_reviews_data(
        query,
        parent_asins,
        top_k
    )
    formatted_context = process_reviews_context(retrieved_context)

    return formatted_context

In [47]:
result = get_formatted_reviews_context("bad quality", ["B0047T79VS", "B0047T79VS"])
result

"- ID: B0047T79VS, user review: Very poor sound quality ! Very poor sound quality !\n- ID: B0047T79VS, user review: Low quality sound Low quality sound! This is the worse quality you can get, is staticky. I used it for my laptop to play in my home theater and it sucks because it take away sound, base, quality & volumen. Do not buy if you are looking to use it for music\n- ID: B0047T79VS, user review: Bad quality sound. Don't waste your money.  Sound quality is bad.  It degrades the already compressed mp3 and sounds like AM radio.\n- ID: B0047T79VS, user review: Very Low Quality Avoid this. Doesn't work. Good manufacturer, bad nonfunctional product. The sound quality is poor and this product's ability to use the Bluetooth protocol is limited.\n- ID: B0047T79VS, user review: Poor Sound Quality Not worth the money, and has....poor sound quality and is really degraded.  Not happy with the purchase, and will be looking for another product that is better quality!\n"