In [ ]:
import openai 
import instructor
from pydantic import BaseModel, Field
import pandas as pd

from qdrant_client import QdrantClient
from qdrant_client import models
from qdrant_client.models import VectorParams, Filter, FieldCondition, MatchValue, Distance, SparseVectorParams, Modifier, PayloadSchemaType, PointStruct, Document, Prefetch, FusionQuery

## Qdrant collection for hybrid search

In [3]:
qdrant_client = QdrantClient(url="http://localhost:6333")

In [9]:
collection_name="Amazon-shopping-collection-01-hybrid-search"
qdrant_client.create_collection(
    collection_name = collection_name,
    vectors_config={
        "text-embedding-3-small": VectorParams(size=1536, distance= Distance.COSINE)
    },
    sparse_vectors_config={
        "bm25": SparseVectorParams(modifier=Modifier.IDF)
    }
)

True

In [11]:
qdrant_client.create_payload_index(
    collection_name=collection_name,
    field_name="parent_asin",
    field_schema=PayloadSchemaType.KEYWORD
    )

UpdateResult(operation_id=2, status=<UpdateStatus.COMPLETED: 'completed'>)

### Embedding Function

In [12]:
def get_embedding(text, model="text-embedding-3-small"):
    response = openai.embeddings.create(input=text, model=model)
    return response.data[0].embedding

### Embeddings for batch

In [14]:
def get_embeddings_batch(text_list, model="text-embedding-3-small", batch_size=100):
    if len(text_list) <= batch_size:
        response = openai.embeddings.create(input=text_list, model = model)
        return [embedding.embedding for embedding in response.data]

    all_embeddings = []
    counter = 1
    for i in range(0, len(text_list), batch_size):
        batch = text_list[i: i + batch_size]
        response = openai.embeddings.create(input=batch, model = model)
        all_embeddings.extend([embedding.embedding for embedding in response.data])
        print(f"Processed {counter * batch_size} of {len(text_list)}")
        counter += 1
    return all_embeddings

In [15]:
df_items = pd.read_json("../../data/meta_Electronics_with_category_sample_1000.jsonl",lines=True)

In [16]:
df_items.head()

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together,subtitle,author
0,All Electronics,"FENIFOX Bluetooth Mouse, Slim Mini Portable Fl...",4.1,2434,[【LIGHT and ULTRA-THIN】: Slim and light design...,[],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'Good for travelers but not for reg...,FENIFOX,"[Electronics, Computers & Accessories, Compute...",{'Product Dimensions': '4.52 x 1.97 x 0.55 inc...,B06ZZJ6C3P,NaN,NaN,None
1,Computers,Macally USB Wired Keyboard and Mouse Combo wit...,4.4,1468,"[Low-profile keys give you a quiet, responsive...","[Wired Keyboard and Mouse Combo, The Macally M...",NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'Full Size USB Keyboard and Optical...,Macally,"[Electronics, Computers & Accessories, Compute...","{'Number of USB 2.0 Ports': '2', 'Brand': 'Mac...",B072VHJN54,NaN,NaN,None
2,Computers,AiSMei Case for 9.7-Inch iPad 5th (2017)/ iPad...,4.2,331,"[Specially designed for ipad A1458, A1459, A14...",[Product Description Size: Classical Rotating ...,NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],AiSMei,"[Electronics, Computers & Accessories, Tablet ...","{'Standing screen display size': '9.7 Inches',...",B013R9SBOC,NaN,NaN,None
3,Camera & Photo,Fujifilm Instax Mini Instant Film Black (10 Sh...,4.7,837,[Express your creativity with this exclusive P...,"[This single pack of, FUJIFILM INSTAX Mini Bla...",NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'Ive been buying this film for 4 ye...,Fujifilm,"[Electronics, Camera & Photo, Film Photography...",{'Package Dimensions': '7.01 x 4.41 x 1.38 inc...,B07WHHYHC8,NaN,NaN,None
4,Computers,KVAGO Keyboard Case for HD 10 and HD 10 Plus T...,4.4,308,[],[],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'Bluetooth Keyboard for Fire HD 10 ...,KVAGO,"[Electronics, Computers & Accessories, Tablet ...",{'Package Dimensions': '11.02 x 7.91 x 1.18 in...,B09MM4S4XR,NaN,NaN,None

In [17]:
def preprocess_description(row):
    return f"{row['title']}{' '.join(row['features']) }"

In [18]:
def extract_first_large_image(row):
    images = row['images']
    if not images:  # handles None, NaN, and empty list
        return ""
    return images[0].get("large", "")

In [21]:
df_items['preprocessed_description'] = df_items.apply(preprocess_description, axis = 1)
df_items['image'] = df_items.apply(extract_first_large_image, axis = 1)
df_items

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together,subtitle,author,preprocessed_description,image
0,All Electronics,"FENIFOX Bluetooth Mouse, Slim Mini Portable Fl...",4.1,2434,[【LIGHT and ULTRA-THIN】: Slim and light design...,[],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'Good for travelers but not for reg...,FENIFOX,"[Electronics, Computers & Accessories, Compute...",{'Product Dimensions': '4.52 x 1.97 x 0.55 inc...,B06ZZJ6C3P,NaN,NaN,None,"FENIFOX Bluetooth Mouse, Slim Mini Portable Fl...",https://m.media-amazon.com/images/I/31Gg2-xED7...
1,Computers,Macally USB Wired Keyboard and Mouse Combo wit...,4.4,1468,"[Low-profile keys give you a quiet, responsive...","[Wired Keyboard and Mouse Combo, The Macally M...",NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'Full Size USB Keyboard and Optical...,Macally,"[Electronics, Computers & Accessories, Compute...","{'Number of USB 2.0 Ports': '2', 'Brand': 'Mac...",B072VHJN54,NaN,NaN,None,Macally USB Wired Keyboard and Mouse Combo wit...,https://m.media-amazon.com/images/I/41JBmHw+U8...
2,Computers,AiSMei Case for 9.7-Inch iPad 5th (2017)/ iPad...,4.2,331,"[Specially designed for ipad A1458, A1459, A14...",[Product Description Size: Classical Rotating ...,NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],AiSMei,"[Electronics, Computers & Accessories, Tablet ...","{'Standing screen display size': '9.7 Inches',...",B013R9SBOC,NaN,NaN,None,AiSMei Case for 9.7-Inch iPad 5th (2017)/ iPad...,https://m.media-amazon.com/images/I/51IamUJo78...
3,Camera & Photo,Fujifilm Instax Mini Instant Film Black (10 Sh...,4.7,837,[Express your creativity with this exclusive P...,"[This single pack of, FUJIFILM INSTAX Mini Bla...",NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'Ive been buying this film for 4 ye...,Fujifilm,"[Electronics, Camera & Photo, Film Photography...",{'Package Dimensions': '7.01 x 4.41 x 1.38 inc...,B07WHHYHC8,NaN,NaN,None,Fujifilm Instax Mini Instant Film Black (10 Sh...,https://m.media-amazon.com/images/I/41TFHj6hlM...
4,Computers,KVAGO Keyboard Case for HD 10 and HD 10 Plus T...,4.4,308,[],[],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'Bluetooth Keyboard for Fire HD 10 ...,KVAGO,"[Electronics, Computers & Accessories, Tablet ...",{'Package Dimensions': '11.02 x 7.91 x 1.18 in...,B09MM4S4XR,NaN,NaN,None,KVAGO Keyboard Case for HD 10 and HD 10 Plus T...,https://m.media-amazon.com/images/I/51+EfwT0MR...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,Camera & Photo,Powerextra 2 Pack Replacement Batteries and Ch...,4.6,223,[Includes 2 batteries and 1 charger for the Pa...,[],49.99,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'Budget Friendly Dual Batteries And...,Powerextra,"[Electronics, Camera & Photo, Accessories, Bat...",{'Package Dimensions': '6.18 x 4.41 x 1.89 inc...,B01IMSOJAI,NaN,NaN,None,Powerextra 2 Pack Replacement Batteries and Ch...,https://m.media-amazon.com/images/I/41OT5XDQ-h...
996,All Electronics,"Aux Cord for iPhone, [Apple Mfi Certified] 3-i...",4.0,867,[【Built-in Advanced Certified Chip】 The premiu...,[],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],Autynie,"[Electronics, Headphones, Earbuds & Accessorie...","{'Brand': 'Autynie', 'Connector Type': 'Auxili...",B07QXX8713,NaN,NaN,None,"Aux Cord for iPhone, [Apple Mfi Certified] 3-i...",https://m.media-amazon.com/images/I/51yO8ckPni...
997,All Electronics,Cable Raceways - Floor Cord Protector Cable Sh...,4.3,725,[1) Multipurpose Not only a protector on the f...,[Cable Raceways - Floor Cord Protector Cable S...,NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],Tenkful,"[Electronics, Accessories & Supplies, Cord Man...",{'Product Dimensions': '60 x 1.19 x 0.45 inche...,B081YTQZSK,NaN,NaN,None,Cable Raceways - Floor Cord Protector Cable Sh...,https://m.media-amazon.com/images/I/51QcMO5k6P...
998,Computers,LifeProof NUUD iPad Mini 1 Waterproof Case - R...,4.3,326,[This product is designed for iPad mini 1 and ...,"[The Maximum Mini Experience, Get LifeProof nü...",NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],LifeProof,"[Electronics, Computers & Accessories, Tablet ...","{'Standing screen display size': '7.9 Inches',...",B00H2AHACC,NaN,NaN,None,LifeProof NUUD iPad Mini 1 Waterproof Case - R...,https://m.media-amazon.com/images/I/51VXxMSNpi...
999,AMAZON FASHION,"Bose Frames, Audio Sunglasses with Open Ear He...",4.5,839,"[Plastic lens, Non-Polarized, Blocks up to 99%...",[],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],Bose,"[Electronics, Wearable Technology, Glasses]",{},B07PC7JKSB,NaN,NaN,None,"Bose Frames, Audio Sunglasses with Open Ear He...",https://m.media-amazon.com/images/I/31lR4nwzLA...

In [23]:
list(df_items["preprocessed_description"].items())[0]

(0,
 'FENIFOX Bluetooth Mouse, Slim Mini Portable Flat Travel Wireless Mouse Rechargeable Quiet Ultra-Thin Mice Compatible with Laptop,Tablet,Notebook,PC (Silver and White)【LIGHT and ULTRA-THIN】: Slim and light design, only 0.6 in thick, 0.1 lbs weight. Made of ABS+PC material, it doesn’t occupy USB port when used. The lightweight and portable designing is the first choice for travel. 【LOW DECIBEL BUTTON】: Low decibel left and right mouse buttons, Suitable for libraries, conference rooms, coffee shops and other occasions. 【ENERGE SAVING and ENVIRONMENT-FRIENDLY】: The mouse has its own power switch and enter sleep mode automatically. It is the most safe and stable lithium polymer battery, work over 3 weeks after one fully charge , can be charged more than hundred times. 【WIDE COMPATIBILITY】: Compatible with the devices,that have 3.0 Version Bluetooth or higher.Like PC,laptop,tablet.But Not compatible with iphone or ipad. 【EASY to OPERATE】: There just need three steps to connect devices that support bluetooth mouse.And more clear indicator.There has power signal light, pairing signal light, DPI signal light, low battery signal light and charging signal light. Finally, this mouse can be used normally when it charging.')

In [24]:
data_to_embed = df_items[["preprocessed_description", "image", "rating_number", "price", "average_rating", "parent_asin"]]
data_to_embed

,preprocessed_description,image,rating_number,price,average_rating,parent_asin
0,"FENIFOX Bluetooth Mouse, Slim Mini Portable Fl...",https://m.media-amazon.com/images/I/31Gg2-xED7...,2434,NaN,4.1,B06ZZJ6C3P
1,Macally USB Wired Keyboard and Mouse Combo wit...,https://m.media-amazon.com/images/I/41JBmHw+U8...,1468,NaN,4.4,B072VHJN54
2,AiSMei Case for 9.7-Inch iPad 5th (2017)/ iPad...,https://m.media-amazon.com/images/I/51IamUJo78...,331,NaN,4.2,B013R9SBOC
3,Fujifilm Instax Mini Instant Film Black (10 Sh...,https://m.media-amazon.com/images/I/41TFHj6hlM...,837,NaN,4.7,B07WHHYHC8
4,KVAGO Keyboard Case for HD 10 and HD 10 Plus T...,https://m.media-amazon.com/images/I/51+EfwT0MR...,308,NaN,4.4,B09MM4S4XR
...,...,...,...,...,...,...
995,Powerextra 2 Pack Replacement Batteries and Ch...,https://m.media-amazon.com/images/I/41OT5XDQ-h...,223,49.99,4.6,B01IMSOJAI
996,"Aux Cord for iPhone, [Apple Mfi Certified] 3-i...",https://m.media-amazon.com/images/I/51yO8ckPni...,867,NaN,4.0,B07QXX8713
997,Cable Raceways - Floor Cord Protector Cable Sh...,https://m.media-amazon.com/images/I/51QcMO5k6P...,725,NaN,4.3,B081YTQZSK
998,LifeProof NUUD iPad Mini 1 Waterproof Case - R...,https://m.media-amazon.com/images/I/51VXxMSNpi...,326,NaN,4.3,B00H2AHACC
999,"Bose Frames, Audio Sunglasses with Open Ear He...",https://m.media-amazon.com/images/I/31lR4nwzLA...,839,NaN,4.5,B07PC7JKSB

In [25]:
data_to_embed_dict  = data_to_embed.to_dict(orient="records")
data_to_embed_dict

[{'preprocessed_description': 'FENIFOX Bluetooth Mouse, Slim Mini Portable Flat Travel Wireless Mouse Rechargeable Quiet Ultra-Thin Mice Compatible with Laptop,Tablet,Notebook,PC (Silver and White)【LIGHT and ULTRA-THIN】: Slim and light design, only 0.6 in thick, 0.1 lbs weight. Made of ABS+PC material, it doesn’t occupy USB port when used. The lightweight and portable designing is the first choice for travel. 【LOW DECIBEL BUTTON】: Low decibel left and right mouse buttons, Suitable for libraries, conference rooms, coffee shops and other occasions. 【ENERGE SAVING and ENVIRONMENT-FRIENDLY】: The mouse has its own power switch and enter sleep mode automatically. It is the most safe and stable lithium polymer battery, work over 3 weeks after one fully charge , can be charged more than hundred times. 【WIDE COMPATIBILITY】: Compatible with the devices,that have 3.0 Version Bluetooth or higher.Like PC,laptop,tablet.But Not compatible with iphone or ipad. 【EASY to OPERATE】: There just need three steps to connect devices that support bluetooth mouse.And more clear indicator.There has power signal light, pairing signal light, DPI signal light, low battery signal light and charging signal light. Finally, this mouse can be used normally when it charging.',
  'image': 'https://m.media-amazon.com/images/I/31Gg2-xED7L._AC_.jpg',
  'rating_number': 2434,
  'price': nan,
  'average_rating': 4.1,
  'parent_asin': 'B06ZZJ6C3P'},
 {'preprocessed_description': 'Macally USB Wired Keyboard and Mouse Combo with 2 Port USB Hub & Apple Shortcut Keys for Mac and Windows PC (MKEYXU2COMBO)Low-profile keys give you a quiet, responsive, and comfortable typing experience 2 port hub allows you to easily connect your mice, access your Flash drives, sync your phone, or use any other Low powered USB devices The mouse is a 3 button USB wired mouse with a precise scroll wheel, which is perfectly positioned to roll smoothly under your finger. Simply Plug both the keyboard and mouse into USB Ports and start using with No drivers required Backed with a 1 year Warranty',
  'image': 'https://m.media-amazon.com/images/I/41JBmHw+U8L._AC_.jpg',
  'rating_number': 1468,
  'price': nan,
  'average_rating': 4.4,
  'parent_asin': 'B072VHJN54'},
 {'preprocessed_description': 'AiSMei Case for 9.7-Inch iPad 5th (2017)/ iPad 6th (2018)/ iPad Air (2015), Rotating Protective Case Cover w/Auto Wake/Sleep Function,PurpleSpecially designed for ipad A1458, A1459, A1460. Also work on ipad A1403, A1416, A1430 & ipad A1395, A1396, A1397.Please check your iPad model number (printed on the back, begins with letter A). Rotates 360 degrees in the case for flexible landscape and portrait viewing. Built-in magnetic strip provides sleep/wake feature. Premium synthetic leather exterior perfectly protects the device against scratches. Elastic band holds iPad closed securely while on the go.',
  'image': 'https://m.media-amazon.com/images/I/51IamUJo78L._AC_.jpg',
  'rating_number': 331,
  'price': nan,
  'average_rating': 4.2,
  'parent_asin': 'B013R9SBOC'},
 {'preprocessed_description': 'Fujifilm Instax Mini Instant Film Black (10 Sheets) + Fujifilm Mini Instant Film Sky Blue (10 Sheets)Express your creativity with this exclusive Photo4less Fujifilm Instax Mini Film bundle. These Fuji instax polaroid style film bundle is the perfect gift you or a loved one, putting smiles on faces of all ages. Take your instant photography to the next level with these black framed Fuji instant mini film kit. Credit card-sized prints, glossy surface, with vibrant colors, and natural skin tones compatible with all instax mini series cameras and printers. Compatible with all Fuji Instax mini series cameras and printers, hi-speed ISO 800, superb grain quality, vibrant colors, and natural skin tones, will ensure beautiful results every shot.',
  'image': 'https://m.media-amazon.com/images/I/41TFHj6hlML._AC_.jpg',
  'rating_number': 837,
  'price': nan,
  'average_rating': 4.7,
  'parent_asin': 'B07WHHYHC8'},
 {'preprocessed_description': 'KVAGO Keyboard Case for HD 10 and HD 10 Plus Tablet (11th Generation) 2021 10.1 inch, Detachable Bluetooth Keyboard with 7 Colors Backlit, PU Leather Protective Smart Folio Cover, Rose Gold',
  'image': 'https://m.media-amazon.com/images/I/51+EfwT0MRL._AC_.jpg',
  'rating_number': 308,
  'price': nan,
  'average_rating': 4.4,
  'parent_asin': 'B09MM4S4XR'},
 {'preprocessed_description': 'Star Projector, Night Light Projector 4 in 1 Galaxy Projector 85° Rotating，with Bluetooth Music Speaker Phone App Remote Control for Baby Kids Bedroom/Game Rooms/Home Theater/Birthday/Party /Wedding',
  'image': 'https://m.media-amazon.com/images/I/51HLgRAdy-L._AC_.jpg',
  'rating_number': 483,
  'price': nan,
  'average_rating': 4.5,
  'parent_asin': 'B09F3F8LKH'},
 {'preprocessed_description': 'BAGSMART Laptop Bag for Women, 15.6 Inch Laptop Case,Slim Computer Bag,15 Inch Water-Repellent Messenger Shoulder Bag,Office Bag Work Bag,Laptop Briefcase for Business Office Travel,Light PinkSPECIFICATIONS- 16.1"L x 12"H x 2.6"W; weight: 1.4 lbs; can be used as a slim laptop bag for women, computer bag, laptop case LAPTOP PROTECTION- The dedicated laptop compartment is fully padded with EVA foam for optimal 15.6 inch laptop protection TSA FRIENDLY- A separate DIGI SMART compartment can hold 15.6 inch Laptop as well as 15 inch, 14 inch Macbook, 9.7 inch iPad, and tech accessories like charger for quick TSA checkpoint when traveling CONVENIENTE DESIGN- Inner hidden pocket for value items, durable leather handles, adjustable padded shoulder strap and luggage strap can be attached to different suitcases LONG-LASTING MATERIAL- Constructed with durable, water-resistant polyester and RPET (recyclable material); simplicity look can serve as a briefcase for women as well as lightweight laptop carrying case',
  'image': 'https://m.media-amazon.com/images/I/41ZRP7o46BL._AC_.jpg',
  'rating_number': 354,
  'price': 16.99,
  'average_rating': 4.6,
  'parent_asin': 'B09GLQPQFF'},
 {'preprocessed_description': "ViewTV 50 Mile Digital TV Antenna Flat Indoor Amplified HDTV - UHF/VHF 1080P Channels w/Detachable Signal Amplifier - 12ft Coax Cable - Black📡 LONG RANGE: 60 Mile Range | ATSC Compatible TV Satellite Antennas | 📶 Receive free digital broadcast High Definition TV 📺 signals. 📡 INDOOR: Detachable Signal Amplifier | 100% copper cable improves signal tremendously | Most other antennas on the market use the much cheaper Copper Clad Steel. 📡 HIGH DEFINITION: Full HDTV Support: 720p, 1080i, 1080p 📶 Super Thin design allows you to place it almost anywhere (Table, Window, Wall). - Watch Your Favorite Channels For Free Including Events Such As The FIFA World Cup, Olympic Games & Much More. 📡 EXTRA SIGNAL STRENGTH: Frequency Range: 470-862MHz | Amplifier Frequency Range: VHF: 47-230MHz / UHF: 470-862MHz. ⭐⭐⭐⭐⭐ Customer Support: We, at ViewTV, Offer Not Only Top Grade-A Quality Products But Also Provide Top of The Line Customer Service Along With Our 1-Year No Questions Asked Warranty Policy Which You Won't Get With Other Brands.",
  'image': 'https://m.media-amazon.com/images/I/41Z6SHIc9kL._AC_.jpg',
  'rating_number': 1190,
  'price': nan,
  'average_rating': 3.8,
  'parent_asin': 'B0158SZZOY'},
 {'preprocessed_description': 'MSI Graphics Card NVIDIA GEFORCE GT 1030 2GHD4 LP OC - BlackAPI Supported: DirectX 12 API Supported: OpenGL 4.5 Number of Monitors Supported: 2 Chipset Manufacturer: NVIDIA Chipset Line: GeForce',
  'image': 'https://m.media-amazon.com/images/I/41GZ2IUUGPL._AC_.jpg',
  'rating_number': 331,
  'price': 100.71,
  'average_rating': 4.3,
  'parent_asin': 'B07CMH5F9R'},
 {'preprocessed_description': 'TOPESEL USB 3.0 Flash Drive 128GB Ultra Sleek Metal Thumb Drive Designed with Key Ring Extreme Portable Jump Drive Exclusive UDP-Tech Waterproof USB Memory Stick High Speed Compact Pen Drive SilverLarge capacity. Save all your data into this compact USB flash drive featuring slim styling yet with 128GB large capacity. It can hold approx. 81,920 images, 30,720 MP3 files, 2.4 million+ pages of Word documents, or 40,960 minutes of video, perfect Ready to use. This USB 3.0 flash drive with backwards compatibility of USB 2.0/USB 1.1 works seamlessly with all mainstream OS involving Windows, Mac, Android, and Linux. Plug and play on PC and Mac, laptop, printer, projector, car audio, smart TV, etc. Waterproof & Durable. Exclusive UDP package technology together with all-metal enclosure offers exceptional durability to resist on water, magnets, shock, temperature changes, and X-rays. Continue to work after drying out if dropped into the water. Extreme portable. Minimalist-style thumb drive is extremely small to fit in pocket or pouch, and designed with a sizable key ring letting you easily connect it to your laptop or your car keys to keep your data close by. High performance. With USB 3.0 technology support, this 128GB USB 3.0 pen drive store and transfer large files 10x faster than standard USB 2.0 flash drives, enabling you to store, access and share media more quickly with up to 70MB/s read speed and 20MB/s write speed.',
  'image': 'https://m.media-amazon.com/images/I/31Dn9Al0i8L._AC_.jpg',
  'rating_number': 548,
  'price': 15.99,
  'average_rating': 4.4,
  'parent_asin': 'B09KNGS9LZ'},
 {'preprocessed_description': 'USB 3.0 to HDMI 1080P Adapter, Topoint USB to HDMI External Video Monitor Adaptor Converter for Windows 7/8/10 Computer ONLY(not support Mac OS)',
  'image': 'https://m.media-amazon.com/images/I/41Ujy9j14BL._AC_.jpg',
  'rating_number': 214,
  'price': nan,
  'average_rating': 3.7,
  'parent_asin': 'B01KJS1W1I'},
 {'preprocessed_description': 'Slim Fitted Standing Case for Amazon Fire HD 7, PinkSlim, lightweight, and form-fitted case protects your Fire HD 7 (4th Generation) Automatically wake your Fire HD 7 or put it to sleep by simply opening or closing the case Built-in stand positions your Fire HD 7 in landscape orientation for hands-free viewing Built from durable polyurethane with a microfiber interior',
  'image': 'https://m.media-amazon.com/images/I/41NL4Q47iVL._AC_.jpg',
  'rating_number': 479,
  'price': nan,
  'average_rating': 4.2,
  'parent_asin': 'B00M0SBUPO'},
 {'preprocessed_description': 'TCL 40FS4610R 40-Inch 1080p Smart LED TV (Roku TV) (2014 Model)Refresh Rate: 60Hz (Native), Clear Motion Rate 120 (Effective) Backlight: LED (Full Array) Smart Functionality: Yes - Roku-integrated Dimensions (W x H x D): TV without stand: 36.5" x 21.4" x 2" , TV with stand: 36.5" x 23" x 7" Inputs: 3 HDMI, 1 USB, RF, Composite, Headphone Jack, Optical Audio Out Accessories Included: Remote w/ batteries, detachable power cord',
  'image': 'https://m.media-amazon.com/images/I/41iZ+3NkxiL._AC_.jpg',
  'rating_number': 768,
  'price': nan,
  'average_rating': 4.4,
  'parent_asin': 'B00K7NCS9G'},
 {'preprocessed_description': "3-Cup Action Camera Suction Cup Mount Motion Camcorder Car Windshield Hood Door Trunk Lid Holder/w Ball Head Compatible with GoPro Sony DJI OSMO Action Akaso Apeman YI Sports DV Cam Vehicle Mounts【Tips & 100% SATISFACTION】: 100% quality and customer satisfied guarantee. If our product doesn't arrive in a great condition or meet your expectation? CONTACT US, we will make full refund or send a replacement. Upgrade 2th Generation universal suction mount with quick release plate, make of high strength ABS material, lightweight but sturdy. Easily assemble and disassemble 【STABILITY AND SECURITY】: Unique tri-cup suction design with 3 vacuum super suction bases, It can be firmly adsorbed on any smooth surface, and keep in place even in the high-speed movement. ATTENTION: For DSLR， we suggest using it in slow-moving or non-moving condition. 【Multiple Angle 】Include 1/4” ball head screw adapter, compatible with any camera with 1/4” screw hole, such as sports camera, camcorder, waterproof cameras and DSLR cameras. 360 degree rotation ballhead design ensures multiple shooting perspective. TIPS: If you have any problem when get this item, such as do not know how to use or mount the suction cup mount, or lack any small part, please just contact us freely directly as soon as possible. we will try to help and guide you out, thank you ! 【WIDE APPLICATION】: Attached to any smooth surfaces firmly with super suction power, such as ceramic surfaces, car windscreen/windshield, plate glass door, car window, car top roof, car hood, trunck lid, car door and wall also metal placeetc. 【Wide Range Compatibility 】Included GoPro Adapter for all GoPro-Like Action Cameras, such as: DJI OSMO ACTION/GoPro Hero 11 10 9 8 7 6 / 5 Black / Session / Hero 4 / Session / Hero+/ Hero+ LCD / Hero3+ / Hero3 SJCAM SJ4000 SJ4000WIFI SJ5000 Xiaomi YI Yi 4K DBPOWER GEEKPRO Lightdow LD4000 LD6000WIFI ASX ActionPro Canany QUMOX ICEFOX Vic Tsing Topjoy KIPTOP MAOZUA TomTom Bandit + Cameras like Canon / Nikon / Olympus / Fujifilm / VTech Kidizoom Kids Camera SONY Actioncams / Samsung Gear 360.",
  'image': 'https://m.media-amazon.com/images/I/21c4KCYUO6L._AC_.jpg',
  'rating_number': 413,
  'price': 14.91,
  'average_rating': 3.8,
  'parent_asin': 'B0BHW4HYTD'},
 {'preprocessed_description': 'PA5024U-1BRS Battery for Toshiba Satellite S75 P75-A7200 P75-A7100 S855-S5378 S855D-S5148 C75D C875 C850 L800 C55T-A C55-A5220 C55-A5300 C55-A5302 C55-A5390 P875 PA5026U-1BRS - 12 Month WarrantySpecifications: Model Name: PA5024U-1BRS PABAS260 Battery, Battery Type: Li-ion Voltage: 10.8V Capacity: 5200mAh/56Wh Cells: 6-cell Color: Black, Packages includes: 1x PA5024U-1BRS Laptop Battery, 1x Instruction for Laptop Battery Compatible for Toshiba Satellite C55 C55-A5100 C55-A5220 C55-A5242 C55-A5281 C55-A5285 C55-A5286 C55-A5300 C55-A5302 C55-A5308 C55-A5310 C55-A5347 C55T C55T-A5123 C55T-A5218 C55T-A5222 C55DT C55T-A5102 C55T-A5123 C55T-A5314 C55T-A5218 C55T-A5222 C55DT-A5244 C55DT-A5305 C55DT-A5306 L875D-S733 L45t-A423 Toshiba Satellite Pro C800 L800 M800 P800 S800 C800 P855D P870 P875D C55-A PA5024U-1BRS for Toshiba Satellite S75-A7221 S75-B7394 C75D-B7100 C75D-B7215 C55-A5242 C55-A5245 C55-A5302 C55-A5393 C55A-A5310 C55-A5038 C55-AF195 C55T-A L855 C850 C855-S5194 C875-S7303; PA5023U-1BRS PA5024U-1BRS PA5025U-1BRS PA5026U-1BRS PA5027U-1BRS PABAS260 PABAS261 PABAS262 PABAS263 100% New from Manufacturer.Every battery has passed factory testing, Grade A cells ensure fast charges and low power consumption. Overheat, Short-circuit and overload protections. Warranty: Don’t worry yourself with Amazon return windows or refund policies. Within 30 days of purchase, we offer a no-questions-asked full money back guarantee. Additionally, for 12 months from the date of purchase, we will exchange your product free of charge should it become defective.How to contact us. Please enter into the product page, click Noborty at the bottom of the cart.then ask a question.',
  'image': 'https://m.media-amazon.com/images/I/41f7fnuEsjL._AC_.jpg',
  'rating_number': 485,
  'price': 28.99,
  'average_rating': 4.4,
  'parent_asin': 'B0CBLSRD4X'},
 {'preprocessed_description': 'CableCreation Headset Splitter Cable, 3.5mm Female to 2 Dual 3.5mm Male Audio Y Splitter Cable with 3.5mm Audio Jack CTIA to OMTP Adapter,Black and White/ 0.2 M[Superb Performance]: Premium metallic housing which makes it easily survive everyday usage and gives it a more stylish and elegant appearance that goes great with your expensive gadgetsInner enameled wire + TPE durable material to make this cable durable enough and soft handle. Unique step-down design accommodates most mobile devices in a case with a snug and secure connection. [Headset splitter mic and audio]：Slim and flexible 20cm headset to PC adapter, connect your newer headsets (audio & microphone) to a PC or Laptop for use with VOIP applications, such as Skype or chat programs, MSN Mesenger, Yahoo, Google Voice etc (NOT for Apple Earphones or BEATS headset). [Strong Braided Exterior]：With soft cotton braided for maximum protection，anti-slip grab design, yet gentle touch feeling. The jack itself has additional insulation which helps in the durability of the product during multiple plug-in and plug-out maneuvers and keeps the interference from other electrical devices in the car to minimum. [Universal Compatibility]: Universal 3.5mm CTIA to OMTP Earphone jack adapter. Solve the problem of incompatible cell phone headset. Compatible with any PC computer with 3.5mm (1/8") jacks - Works with Blackberry/Droid 3.5mm stereo headset. [What You Get]：CableCreation Headset Splitter Adapter x 1pack with 2-years of warranty and lifetime friendly customer service.',
  'image': 'https://m.media-amazon.com/images/I/41nwC9DoxWL._AC_.jpg',
  'rating_number': 966,
  'price': 11.75,
  'average_rating': 4.4,
  'parent_asin': 'B06XPFXF8B'},
 {'preprocessed_description': "Soundcore Wireless Earbuds, Anker Liberty Lite Bluetooth 5.0 True Wireless Earbuds, Easy-Pair Sports Sweatproof Mini Bluetooth Headphones with Graphene-Enhanced Drivers, Stereo Calls and Built-in MicBreathtaking Sound: Exceptional clarity delivered via Graphene drivers with deep, resonant bass. Smaller & Lighter: Incredible comfort and seamless sound that sits effortlessly in your ears. 12-Hour Playtime: Get 3.5 hours' playtime from a single charge and 9 extra hours in the compact charging case. Ultra-Fast Pairing: PUSH AND GO Technology simplifies the setup process so the last-paired device automatically connects on startup. IPX5 Protection: Resists liquids for workouts in the sun or songs in the rain.",
  'image': 'https://m.media-amazon.com/images/I/41rn8AHHL5L._AC_.jpg',
  'rating_number': 706,
  'price': nan,
  'average_rating': 3.9,
  'parent_asin': 'B07JMLGMNL'},
 {'preprocessed_description': 'Phanteks Universal Extension Cables Kit - PH-CB-CMBO_WG,White/GreyConductive resistance: 0.01 Ωmax. Type: 24pin ATX, 8pin (4+4) eps, 8pin (6+2) PCI-e extension. Color: white/grey. Sleeve tube: pp material Connector: 24(2x12) pin/male to 24(2x12) pin/female, 4(2x2) + 4(2x2)/male to 8(2x4) pin/female , 2(2x1) + 6(2x3)/male to 8(2x4)pin/female Construction AWG: 18awg, ø2.1mm (Rohs). Cable length: 19.68 Inch (500mm)',
  'image': 'https://m.media-amazon.com/images/I/41xugefJ5PL._AC_.jpg',
  'rating_number': 1167,
  'price': 41.93,
  'average_rating': 4.6,
  'parent_asin': 'B01HBN9TLO'},
 {'preprocessed_description': "XO Vision IR630P Universal IR Wireless Foldable Headphones - Pink Wireless Bluetooth-Enabled Lightweight Portable for iPhone, Car, Kids Wireless Headphones for Universal Car Entertainment SystemEasy pair - Compatible with most in car infrared transmitters. Gain instant access to your vehicles DVD player system and connect for wireless audio playback. Easy to use - User friendly on and off switch as well as volume control that is easily accessible on the headphones for personalized control and comfort. Perfect for kids to use on any length trip! Custom fit comfort - enjoy your movie while listening in comfort with the extra foam cushioning and adjustable headband that provides a completely custom and comfortable fit while wearing for kids and adults. Easy to store - the convenient foldable ear cup design provides effortless storage options. Keep your vehicle clutter free when they're not being used and pack them away! Connectivity technology: Wired",
  'image': 'https://m.media-amazon.com/images/I/31ZkjZPKGPL._AC_.jpg',
  'rating_number': 457,
  'price': 14.99,
  'average_rating': 4.1,
  'parent_asin': 'B006U8D51C'},

In [26]:
len(data_to_embed_dict)

1000

In [30]:
text_to_embed  = [item["preprocessed_description"] for item in data_to_embed_dict]
text_to_embed

['FENIFOX Bluetooth Mouse, Slim Mini Portable Flat Travel Wireless Mouse Rechargeable Quiet Ultra-Thin Mice Compatible with Laptop,Tablet,Notebook,PC (Silver and White)【LIGHT and ULTRA-THIN】: Slim and light design, only 0.6 in thick, 0.1 lbs weight. Made of ABS+PC material, it doesn’t occupy USB port when used. The lightweight and portable designing is the first choice for travel. 【LOW DECIBEL BUTTON】: Low decibel left and right mouse buttons, Suitable for libraries, conference rooms, coffee shops and other occasions. 【ENERGE SAVING and ENVIRONMENT-FRIENDLY】: The mouse has its own power switch and enter sleep mode automatically. It is the most safe and stable lithium polymer battery, work over 3 weeks after one fully charge , can be charged more than hundred times. 【WIDE COMPATIBILITY】: Compatible with the devices,that have 3.0 Version Bluetooth or higher.Like PC,laptop,tablet.But Not compatible with iphone or ipad. 【EASY to OPERATE】: There just need three steps to connect devices that support bluetooth mouse.And more clear indicator.There has power signal light, pairing signal light, DPI signal light, low battery signal light and charging signal light. Finally, this mouse can be used normally when it charging.',
 'Macally USB Wired Keyboard and Mouse Combo with 2 Port USB Hub & Apple Shortcut Keys for Mac and Windows PC (MKEYXU2COMBO)Low-profile keys give you a quiet, responsive, and comfortable typing experience 2 port hub allows you to easily connect your mice, access your Flash drives, sync your phone, or use any other Low powered USB devices The mouse is a 3 button USB wired mouse with a precise scroll wheel, which is perfectly positioned to roll smoothly under your finger. Simply Plug both the keyboard and mouse into USB Ports and start using with No drivers required Backed with a 1 year Warranty',
 'AiSMei Case for 9.7-Inch iPad 5th (2017)/ iPad 6th (2018)/ iPad Air (2015), Rotating Protective Case Cover w/Auto Wake/Sleep Function,PurpleSpecially designed for ipad A1458, A1459, A1460. Also work on ipad A1403, A1416, A1430 & ipad A1395, A1396, A1397.Please check your iPad model number (printed on the back, begins with letter A). Rotates 360 degrees in the case for flexible landscape and portrait viewing. Built-in magnetic strip provides sleep/wake feature. Premium synthetic leather exterior perfectly protects the device against scratches. Elastic band holds iPad closed securely while on the go.',
 'Fujifilm Instax Mini Instant Film Black (10 Sheets) + Fujifilm Mini Instant Film Sky Blue (10 Sheets)Express your creativity with this exclusive Photo4less Fujifilm Instax Mini Film bundle. These Fuji instax polaroid style film bundle is the perfect gift you or a loved one, putting smiles on faces of all ages. Take your instant photography to the next level with these black framed Fuji instant mini film kit. Credit card-sized prints, glossy surface, with vibrant colors, and natural skin tones compatible with all instax mini series cameras and printers. Compatible with all Fuji Instax mini series cameras and printers, hi-speed ISO 800, superb grain quality, vibrant colors, and natural skin tones, will ensure beautiful results every shot.',
 'KVAGO Keyboard Case for HD 10 and HD 10 Plus Tablet (11th Generation) 2021 10.1 inch, Detachable Bluetooth Keyboard with 7 Colors Backlit, PU Leather Protective Smart Folio Cover, Rose Gold',
 'Star Projector, Night Light Projector 4 in 1 Galaxy Projector 85° Rotating，with Bluetooth Music Speaker Phone App Remote Control for Baby Kids Bedroom/Game Rooms/Home Theater/Birthday/Party /Wedding',
 'BAGSMART Laptop Bag for Women, 15.6 Inch Laptop Case,Slim Computer Bag,15 Inch Water-Repellent Messenger Shoulder Bag,Office Bag Work Bag,Laptop Briefcase for Business Office Travel,Light PinkSPECIFICATIONS- 16.1"L x 12"H x 2.6"W; weight: 1.4 lbs; can be used as a slim laptop bag for women, computer bag, laptop case LAPTOP PROTECTION- The dedicated laptop compartment is fully padded with EVA foam for optimal 15.6 inch laptop protection TSA FRIENDLY- A separate DIGI SMART compartment can hold 15.6 inch Laptop as well as 15 inch, 14 inch Macbook, 9.7 inch iPad, and tech accessories like charger for quick TSA checkpoint when traveling CONVENIENTE DESIGN- Inner hidden pocket for value items, durable leather handles, adjustable padded shoulder strap and luggage strap can be attached to different suitcases LONG-LASTING MATERIAL- Constructed with durable, water-resistant polyester and RPET (recyclable material); simplicity look can serve as a briefcase for women as well as lightweight laptop carrying case',
 "ViewTV 50 Mile Digital TV Antenna Flat Indoor Amplified HDTV - UHF/VHF 1080P Channels w/Detachable Signal Amplifier - 12ft Coax Cable - Black📡 LONG RANGE: 60 Mile Range | ATSC Compatible TV Satellite Antennas | 📶 Receive free digital broadcast High Definition TV 📺 signals. 📡 INDOOR: Detachable Signal Amplifier | 100% copper cable improves signal tremendously | Most other antennas on the market use the much cheaper Copper Clad Steel. 📡 HIGH DEFINITION: Full HDTV Support: 720p, 1080i, 1080p 📶 Super Thin design allows you to place it almost anywhere (Table, Window, Wall). - Watch Your Favorite Channels For Free Including Events Such As The FIFA World Cup, Olympic Games & Much More. 📡 EXTRA SIGNAL STRENGTH: Frequency Range: 470-862MHz | Amplifier Frequency Range: VHF: 47-230MHz / UHF: 470-862MHz. ⭐⭐⭐⭐⭐ Customer Support: We, at ViewTV, Offer Not Only Top Grade-A Quality Products But Also Provide Top of The Line Customer Service Along With Our 1-Year No Questions Asked Warranty Policy Which You Won't Get With Other Brands.",
 'MSI Graphics Card NVIDIA GEFORCE GT 1030 2GHD4 LP OC - BlackAPI Supported: DirectX 12 API Supported: OpenGL 4.5 Number of Monitors Supported: 2 Chipset Manufacturer: NVIDIA Chipset Line: GeForce',
 'TOPESEL USB 3.0 Flash Drive 128GB Ultra Sleek Metal Thumb Drive Designed with Key Ring Extreme Portable Jump Drive Exclusive UDP-Tech Waterproof USB Memory Stick High Speed Compact Pen Drive SilverLarge capacity. Save all your data into this compact USB flash drive featuring slim styling yet with 128GB large capacity. It can hold approx. 81,920 images, 30,720 MP3 files, 2.4 million+ pages of Word documents, or 40,960 minutes of video, perfect Ready to use. This USB 3.0 flash drive with backwards compatibility of USB 2.0/USB 1.1 works seamlessly with all mainstream OS involving Windows, Mac, Android, and Linux. Plug and play on PC and Mac, laptop, printer, projector, car audio, smart TV, etc. Waterproof & Durable. Exclusive UDP package technology together with all-metal enclosure offers exceptional durability to resist on water, magnets, shock, temperature changes, and X-rays. Continue to work after drying out if dropped into the water. Extreme portable. Minimalist-style thumb drive is extremely small to fit in pocket or pouch, and designed with a sizable key ring letting you easily connect it to your laptop or your car keys to keep your data close by. High performance. With USB 3.0 technology support, this 128GB USB 3.0 pen drive store and transfer large files 10x faster than standard USB 2.0 flash drives, enabling you to store, access and share media more quickly with up to 70MB/s read speed and 20MB/s write speed.',
 'USB 3.0 to HDMI 1080P Adapter, Topoint USB to HDMI External Video Monitor Adaptor Converter for Windows 7/8/10 Computer ONLY(not support Mac OS)',
 'Slim Fitted Standing Case for Amazon Fire HD 7, PinkSlim, lightweight, and form-fitted case protects your Fire HD 7 (4th Generation) Automatically wake your Fire HD 7 or put it to sleep by simply opening or closing the case Built-in stand positions your Fire HD 7 in landscape orientation for hands-free viewing Built from durable polyurethane with a microfiber interior',
 'TCL 40FS4610R 40-Inch 1080p Smart LED TV (Roku TV) (2014 Model)Refresh Rate: 60Hz (Native), Clear Motion Rate 120 (Effective) Backlight: LED (Full Array) Smart Functionality: Yes - Roku-integrated Dimensions (W x H x D): TV without stand: 36.5" x 21.4" x 2" , TV with stand: 36.5" x 23" x 7" Inputs: 3 HDMI, 1 USB, RF, Composite, Headphone Jack, Optical Audio Out Accessories Included: Remote w/ batteries, detachable power cord',
 "3-Cup Action Camera Suction Cup Mount Motion Camcorder Car Windshield Hood Door Trunk Lid Holder/w Ball Head Compatible with GoPro Sony DJI OSMO Action Akaso Apeman YI Sports DV Cam Vehicle Mounts【Tips & 100% SATISFACTION】: 100% quality and customer satisfied guarantee. If our product doesn't arrive in a great condition or meet your expectation? CONTACT US, we will make full refund or send a replacement. Upgrade 2th Generation universal suction mount with quick release plate, make of high strength ABS material, lightweight but sturdy. Easily assemble and disassemble 【STABILITY AND SECURITY】: Unique tri-cup suction design with 3 vacuum super suction bases, It can be firmly adsorbed on any smooth surface, and keep in place even in the high-speed movement. ATTENTION: For DSLR， we suggest using it in slow-moving or non-moving condition. 【Multiple Angle 】Include 1/4” ball head screw adapter, compatible with any camera with 1/4” screw hole, such as sports camera, camcorder, waterproof cameras and DSLR cameras. 360 degree rotation ballhead design ensures multiple shooting perspective. TIPS: If you have any problem when get this item, such as do not know how to use or mount the suction cup mount, or lack any small part, please just contact us freely directly as soon as possible. we will try to help and guide you out, thank you ! 【WIDE APPLICATION】: Attached to any smooth surfaces firmly with super suction power, such as ceramic surfaces, car windscreen/windshield, plate glass door, car window, car top roof, car hood, trunck lid, car door and wall also metal placeetc. 【Wide Range Compatibility 】Included GoPro Adapter for all GoPro-Like Action Cameras, such as: DJI OSMO ACTION/GoPro Hero 11 10 9 8 7 6 / 5 Black / Session / Hero 4 / Session / Hero+/ Hero+ LCD / Hero3+ / Hero3 SJCAM SJ4000 SJ4000WIFI SJ5000 Xiaomi YI Yi 4K DBPOWER GEEKPRO Lightdow LD4000 LD6000WIFI ASX ActionPro Canany QUMOX ICEFOX Vic Tsing Topjoy KIPTOP MAOZUA TomTom Bandit + Cameras like Canon / Nikon / Olympus / Fujifilm / VTech Kidizoom Kids Camera SONY Actioncams / Samsung Gear 360.",
 'PA5024U-1BRS Battery for Toshiba Satellite S75 P75-A7200 P75-A7100 S855-S5378 S855D-S5148 C75D C875 C850 L800 C55T-A C55-A5220 C55-A5300 C55-A5302 C55-A5390 P875 PA5026U-1BRS - 12 Month WarrantySpecifications: Model Name: PA5024U-1BRS PABAS260 Battery, Battery Type: Li-ion Voltage: 10.8V Capacity: 5200mAh/56Wh Cells: 6-cell Color: Black, Packages includes: 1x PA5024U-1BRS Laptop Battery, 1x Instruction for Laptop Battery Compatible for Toshiba Satellite C55 C55-A5100 C55-A5220 C55-A5242 C55-A5281 C55-A5285 C55-A5286 C55-A5300 C55-A5302 C55-A5308 C55-A5310 C55-A5347 C55T C55T-A5123 C55T-A5218 C55T-A5222 C55DT C55T-A5102 C55T-A5123 C55T-A5314 C55T-A5218 C55T-A5222 C55DT-A5244 C55DT-A5305 C55DT-A5306 L875D-S733 L45t-A423 Toshiba Satellite Pro C800 L800 M800 P800 S800 C800 P855D P870 P875D C55-A PA5024U-1BRS for Toshiba Satellite S75-A7221 S75-B7394 C75D-B7100 C75D-B7215 C55-A5242 C55-A5245 C55-A5302 C55-A5393 C55A-A5310 C55-A5038 C55-AF195 C55T-A L855 C850 C855-S5194 C875-S7303; PA5023U-1BRS PA5024U-1BRS PA5025U-1BRS PA5026U-1BRS PA5027U-1BRS PABAS260 PABAS261 PABAS262 PABAS263 100% New from Manufacturer.Every battery has passed factory testing, Grade A cells ensure fast charges and low power consumption. Overheat, Short-circuit and overload protections. Warranty: Don’t worry yourself with Amazon return windows or refund policies. Within 30 days of purchase, we offer a no-questions-asked full money back guarantee. Additionally, for 12 months from the date of purchase, we will exchange your product free of charge should it become defective.How to contact us. Please enter into the product page, click Noborty at the bottom of the cart.then ask a question.',
 'CableCreation Headset Splitter Cable, 3.5mm Female to 2 Dual 3.5mm Male Audio Y Splitter Cable with 3.5mm Audio Jack CTIA to OMTP Adapter,Black and White/ 0.2 M[Superb Performance]: Premium metallic housing which makes it easily survive everyday usage and gives it a more stylish and elegant appearance that goes great with your expensive gadgetsInner enameled wire + TPE durable material to make this cable durable enough and soft handle. Unique step-down design accommodates most mobile devices in a case with a snug and secure connection. [Headset splitter mic and audio]：Slim and flexible 20cm headset to PC adapter, connect your newer headsets (audio & microphone) to a PC or Laptop for use with VOIP applications, such as Skype or chat programs, MSN Mesenger, Yahoo, Google Voice etc (NOT for Apple Earphones or BEATS headset). [Strong Braided Exterior]：With soft cotton braided for maximum protection，anti-slip grab design, yet gentle touch feeling. The jack itself has additional insulation which helps in the durability of the product during multiple plug-in and plug-out maneuvers and keeps the interference from other electrical devices in the car to minimum. [Universal Compatibility]: Universal 3.5mm CTIA to OMTP Earphone jack adapter. Solve the problem of incompatible cell phone headset. Compatible with any PC computer with 3.5mm (1/8") jacks - Works with Blackberry/Droid 3.5mm stereo headset. [What You Get]：CableCreation Headset Splitter Adapter x 1pack with 2-years of warranty and lifetime friendly customer service.',
 "Soundcore Wireless Earbuds, Anker Liberty Lite Bluetooth 5.0 True Wireless Earbuds, Easy-Pair Sports Sweatproof Mini Bluetooth Headphones with Graphene-Enhanced Drivers, Stereo Calls and Built-in MicBreathtaking Sound: Exceptional clarity delivered via Graphene drivers with deep, resonant bass. Smaller & Lighter: Incredible comfort and seamless sound that sits effortlessly in your ears. 12-Hour Playtime: Get 3.5 hours' playtime from a single charge and 9 extra hours in the compact charging case. Ultra-Fast Pairing: PUSH AND GO Technology simplifies the setup process so the last-paired device automatically connects on startup. IPX5 Protection: Resists liquids for workouts in the sun or songs in the rain.",
 'Phanteks Universal Extension Cables Kit - PH-CB-CMBO_WG,White/GreyConductive resistance: 0.01 Ωmax. Type: 24pin ATX, 8pin (4+4) eps, 8pin (6+2) PCI-e extension. Color: white/grey. Sleeve tube: pp material Connector: 24(2x12) pin/male to 24(2x12) pin/female, 4(2x2) + 4(2x2)/male to 8(2x4) pin/female , 2(2x1) + 6(2x3)/male to 8(2x4)pin/female Construction AWG: 18awg, ø2.1mm (Rohs). Cable length: 19.68 Inch (500mm)',
 "XO Vision IR630P Universal IR Wireless Foldable Headphones - Pink Wireless Bluetooth-Enabled Lightweight Portable for iPhone, Car, Kids Wireless Headphones for Universal Car Entertainment SystemEasy pair - Compatible with most in car infrared transmitters. Gain instant access to your vehicles DVD player system and connect for wireless audio playback. Easy to use - User friendly on and off switch as well as volume control that is easily accessible on the headphones for personalized control and comfort. Perfect for kids to use on any length trip! Custom fit comfort - enjoy your movie while listening in comfort with the extra foam cushioning and adjustable headband that provides a completely custom and comfortable fit while wearing for kids and adults. Easy to store - the convenient foldable ear cup design provides effortless storage options. Keep your vehicle clutter free when they're not being used and pack them away! Connectivity technology: Wired",
 'CAGOS Compatible with Airpods Case,Cute Airpods Protective Hard Case Cover with Fur Ball Keychain for Airpods 2/1 Charging Case - PinkPERFECT FIT: CAGOS compatible with AirPods case protective covers are made of imported high quality hard TPU material with unique prints, which is specially designed for Apple AirPods 1 & AirPods 2 Charging Case. Come with cute Artificial Fur ball keychain with nice soft touching, perfect airpods accessories. It is a perfect gift for any occasion FULL PROTECTION: Fully covered design protects your Apple AirPods. Keeps your device safe from damage and scratches, Features a smooth finish that won\'t come off with day-to-day use. Full Access: Precise cutout offers a free access to the charging port.Fits snugly over the charging case. EASY TO CARRY: Keychain easily attaches to your purse or belt loop, It enables you to have your AirPods handy at all times, without fear of setting them down and losing them. Take along Airpods for any outdoor activities ( running,riding, fishing,etc ) even on a heavy rainy or snowy day. PERFECT GIFTS : If you choose this marble airpods case for your daughter/girlfriend/wife/best friends as a gift, they will be surprise how cute it is and fall in love with their airpods 2/1 all over again! Need more assistance, please contact CAGOS via your Amazon order page and click "Contact Seller", we\'ll make it right for you.',
 'Semeving Compatible with Airpods 3 Case 2021/Airpods 3 Generation Case,Silicone Cartoon Anime Cover Case for AirPods 3rd Generation Charging Case(Shark Bag)【Perfectly Fit For Airpods 3 2021】The Airpods 3 Case is Only Fit For AirPods 3rd Gen (2021 release). NOT Fit For Airpods 1/2 Or Airpods Pro 【PREMIUM SIILICONE Material/Airpods 3 Case】The Airpods 3 Case Is Made Of PREMIUM SIILICONE material,it Can protects your Airpods 3 Earphone from drops, dirts, and oils from daily use - keep the Airpods 3 Case LOOKING Always NEW! 【3D Cartoon Design/Airpods 3 Case】The Airpods 3 Case is Design With Cartoon Style.It Can Fit For Men/Women/Girls/Boys And Kids.It Also Can be As Great for BIRTHDAY PRESENTS for loved ones and gifts during the holiday season – ESPECIALLY CHRISTMAS FOR STOCKING STUFFERS! 【Full Body Protection/Airpods 3 Case】Premium TPU case and compact design provides all-round protection compatible with AirPods 3 case which against drops, fingerprints and scratches. 【Best Service/Airpods 3 Case】We promise To Offer Best Quality Airpods 3 Case To Every Customer,But If there is any problem the case, then please contact with us firstly',
 "Retevis Acoustic Tube Walkie Talkie Earpiece 2 Pin, Compatible RT22 RT21 H-777 RT68 RT22S H-777S Baofeng UV-5R Kenwood pxton Walkie Talkie, Security 2 Way Radio Headset with Mic(5 Pack)Acoustic tube earpiece for walkie talkie; make your communication more private and protect your health from radio electromagnetic wave radiation Ergonomic earplug design; suitable for left and right ears; with a variety of different wearing styles; choose the one that suits you better Sensitive built in mic with ptt; allows you communicate smoothly with your partners; ideal for military police; security; bodyguards; warehouses; paintball rides; etc Stainless steel clip; you can clip it to your collar to adjust the mic close to your mouth and push to talk for hands free calls; make communication easier K head plug 2 pin; compatible with Retevis RT22 RT21 H-777 RT27 RT28; compatible with Baofeng Kenwood Arcshell pxton etc; can't compatible with any Motorola and Midland radios",

In [31]:
embeddings = get_embeddings_batch(text_to_embed)

Processed 100 of 1000
Processed 200 of 1000
Processed 300 of 1000
Processed 400 of 1000
Processed 500 of 1000
Processed 600 of 1000
Processed 700 of 1000
Processed 800 of 1000
Processed 900 of 1000
Processed 1000 of 1000

In [32]:
len(embeddings)

1000

In [33]:
point_structs = []
i  = 1
for embedding, data in zip(embeddings, data_to_embed_dict):
    point_structs.append(
                            PointStruct
                                (id=i,
                                vector={
                                    "text-embedding-3-small": embedding,
                                    "bm25": Document(
                                        text = data["preprocessed_description"],
                                        model="qdrant/bm25"
                                    )
                                    },
                                    payload = data
                                ) 
                        )
    i += 1

In [34]:
point_structs[0].vector

{'text-embedding-3-small': [0.00567626953125,
  0.02691650390625,
  -0.01230621337890625,
  -0.01708984375,
  -0.01873779296875,
  -0.024017333984375,
  -0.035919189453125,
  0.02459716796875,
  0.01070404052734375,
  -0.026275634765625,
  -0.032073974609375,
  0.034881591796875,
  -0.09027099609375,
  0.040283203125,
  0.044952392578125,
  0.0236663818359375,
  -0.0154876708984375,
  -0.01467132568359375,
  -0.001983642578125,
  0.0035533905029296875,
  -0.003879547119140625,
  0.039154052734375,
  0.020660400390625,
  -0.02252197265625,
  0.00495147705078125,
  -0.00768280029296875,
  0.021820068359375,
  -0.034759521484375,
  0.0192108154296875,
  0.0018215179443359375,
  -0.01052093505859375,
  -0.02374267578125,
  0.025787353515625,
  -0.054931640625,
  0.003185272216796875,
  -0.012298583984375,
  0.0271148681640625,
  -0.0538330078125,
  0.01180267333984375,
  -0.035675048828125,
  -0.032196044921875,
  -0.01062774658203125,
  0.042694091796875,
  0.001007080078125,
  0.016815185546875,
  -0.007129669189453125,
  0.0034046173095703125,
  0.017578125,
  0.04132080078125,
  0.0171661376953125,
  -0.0247802734375,
  0.03228759765625,
  0.00569915771484375,
  0.05615234375,
  -0.0066375732421875,
  0.01032257080078125,
  0.038330078125,
  -0.0014324188232421875,
  0.029632568359375,
  0.0113677978515625,
  -0.0186614990234375,
  -0.01708984375,
  0.04583740234375,
  0.05535888671875,
  -0.0104522705078125,
  0.0343017578125,
  -0.05328369140625,
  0.062744140625,
  -0.021270751953125,
  -0.061614990234375,
  -0.0019588470458984375,
  -0.03875732421875,
  -0.037872314453125,
  -0.0036945343017578125,
  0.07342529296875,
  0.00896453857421875,
  0.02069091796875,
  0.0029964447021484375,
  -0.031646728515625,
  0.04656982421875,
  -0.04205322265625,
  0.025726318359375,
  -0.062164306640625,
  -0.006122589111328125,
  -0.03033447265625,
  0.00787353515625,
  -0.08795166015625,
  0.0016117095947265625,
  -0.09197998046875,
  -0.00794219970703125,
  -0.001949310302734375,
  -0.088623046875,
  0.0023899078369140625,
  -0.0021724700927734375,
  0.01499176025390625,
  0.0113372802734375,
  0.0107879638671875,
  -0.02606201171875,
  -0.0169830322265625,
  0.03912353515625,
  0.04052734375,
  -0.01520538330078125,
  -0.01486968994140625,
  -0.007259368896484375,
  -0.016448974609375,
  0.01378631591796875,
  0.0035037994384765625,
  -0.01107025146484375,
  -0.02178955078125,
  0.037750244140625,
  -0.0096893310546875,
  -0.0213623046875,
  -0.007625579833984375,
  0.027496337890625,
  -0.0113525390625,
  -0.0195159912109375,
  0.0180511474609375,
  0.006931304931640625,
  0.010345458984375,
  -0.0352783203125,
  -0.0219268798828125,
  0.0179595947265625,
  0.056915283203125,
  -0.0040283203125,
  -0.0193023681640625,
  -0.030242919921875,
  -0.030303955078125,
  -0.0106201171875,
  -0.005382537841796875,
  -0.0265960693359375,
  0.043853759765625,
  -0.003246307373046875,
  0.031494140625,
  -0.034912109375,
  -0.018310546875,
  0.01080322265625,
  -0.0034732818603515625,
  0.01458740234375,
  -0.016326904296875,
  0.003215789794921875,
  0.0095672607421875,
  -0.0246124267578125,
  0.00405120849609375,
  0.0233917236328125,
  -0.049652099609375,
  0.02386474609375,
  0.0204010009765625,
  0.0156402587890625,
  -0.01390838623046875,
  0.039031982421875,
  0.05950927734375,
  -0.04986572265625,
  0.006999969482421875,
  0.0238494873046875,
  -0.00022351741790771484,
  0.006931304931640625,
  0.06524658203125,
  0.06280517578125,
  -0.040313720703125,
  -0.0467529296875,
  -0.0225982666015625,
  0.01325225830078125,
  -0.0283050537109375,
  -0.051513671875,
  0.0004949569702148438,
  0.05426025390625,
  0.01129150390625,
  -0.01325225830078125,
  -0.052154541015625,
  0.04888916015625,
  0.03173828125,
  -0.006458282470703125,
  0.00415802001953125,
  0.0221710205078125,
  -0.007167816162109375,
  -0.0260009765625,
  0.04974365234375,
  -0.0004897117614746094,
  -0.045562744140625,
  0.030975341796875,
  -0.025970458984375,
  -0.0088653564453125,
  0.021728515625,
  -0.0052490234375,
  -0.0088348388671875,
  -0.0299530029296875,
  -0.035614013671875,
  -0.0175628662109375,
  0.0014982223510742188,
  -0.031707763671875,
  -0.0032901763916015625,
  0.0205078125,
  -0.038330078125,
  0.049652099609375,
  -0.0128936767578125,
  0.029876708984375,
  0.0078125,
  -0.0272979736328125,
  -0.04193115234375,
  -0.05255126953125,
  -0.01287078857421875,
  0.019927978515625,
  0.0123138427734375,
  0.0121002197265625,
  -0.01551055908203125,
  -0.021759033203125,
  0.01416015625,
  -0.00803375244140625,
  0.044830322265625,
  -0.0220489501953125,
  0.03424072265625,
  -0.0230712890625,
  0.01275634765625,
  -0.06060791015625,
  -0.0175628662109375,
  0.03729248046875,
  0.044525146484375,
  0.0067596435546875,
  0.03692626953125,
  0.016845703125,
  -0.006824493408203125,
  -0.0292510986328125,
  0.05157470703125,
  0.0019197463989257812,
  -0.0009889602661132812,
  -0.033203125,
  0.0087432861328125,
  -0.052520751953125,
  -0.003620147705078125,
  -0.0650634765625,
  0.024993896484375,
  -0.008941650390625,
  -0.03753662109375,
  0.0074005126953125,
  0.0394287109375,
  -0.004451751708984375,
  -0.016815185546875,
  -0.021514892578125,
  -0.0058441162109375,
  0.0213775634765625,
  -0.052947998046875,
  -0.0190887451171875,
  -0.046051025390625,
  -0.0026702880859375,
  -0.02032470703125,
  -0.01499176025390625,
  -0.045196533203125,
  -0.03277587890625,
  0.023712158203125,
  -0.01303863525390625,
  0.054351806640625,
  0.038604736328125,
  0.0625,
  -0.01190948486328125,
  0.0170135498046875,
  0.008270263671875,
  -0.0304412841796875,
  0.005748748779296875,
  0.0277099609375,
  -0.007312774658203125,
  -0.0457763671875,
  -0.006893157958984375,
  0.0199432373046875,
  0.00127410888671875,
  0.011932373046875,
  -0.0230712890625,
  -0.0005469322204589844,
  0.01509857177734375,
  -0.0034770965576171875,
  0.0275115966796875,
  0.013824462890625,
  0.022003173828125,
  -0.028564453125,
  0.0450439453125,
  -0.01177215576171875,
  0.041595458984375,
  -0.0232391357421875,
  -0.01541900634765625,
  -0.0301971435546875,
  -0.026275634765625,
  -0.0108795166015625,
  0.00616455078125,
  0.054779052734375,
  -0.047332763671875,
  -0.03839111328125,
  0.0245208740234375,
  -0.002704620361328125,
  0.03277587890625,
  0.0084075927734375,
  -0.02008056640625,
  0.03826904296875,
  0.00376129150390625,
  0.00855255126953125,
  -0.002368927001953125,
  0.044921875,
  -0.0116729736328125,
  -0.0160980224609375,
  0.01441192626953125,
  -0.049102783203125,
  -0.028350830078125,
  0.032135009765625,
  0.02642822265625,
  0.015380859375,
  -0.008941650390625,
  -0.0374755859375,
  0.043914794921875,
  -0.054718017578125,
  -0.035430908203125,
  -0.0200347900390625,
  -0.0225677490234375,
  -0.042205810546875,
  0.0384521484375,
  0.025909423828125,
  -0.032318115234375,
  0.0018529891967773438,
  -0.00846099853515625,
  -0.0178070068359375,
  0.004150390625,
  -0.0013513565063476562,
  -0.06512451171875,
  0.032501220703125,
  0.0164947509765625,
  0.0273895263671875,
  0.041229248046875,
  0.018798828125,
  -0.022796630859375,
  -0.0034694671630859375,
  0.0187835693359375,
  0.001094818115234375,
  -0.0111083984375,
  0.01247406005859375,
  0.0244903564453125,
  0.0057373046875,
  0.009521484375,
  0.00577545166015625,
  -0.0254364013671875,
  -0.0275421142578125,
  -0.0150146484375,
  -0.04144287109375,
  0.0269622802734375,
  0.01068115234375,
  -0.0277252197265625,
  -0.06109619140625,
  0.053802490234375,
  0.01308441162109375,
  0.0286712646484375,
  -0.0127716064453125,
  -0.01262664794921875,
  0.055755615234375,
  0.04998779296875,
  0.0191650390625,
  0.025146484375,
  0.00667572021484375,
  -0.0255126953125,
  0.018402099609375,
  -0.031158447265625,
  0.0205841064453125,
  -0.0170745849609375,
  -0.035125732421875,
  0.045379638671875,
  0.027923583984375,
  0.0240325927734375,
  0.0251007080078125,
  -0.0263671875,
  -0.0024662017822265625,
  -0.032562255859375,
  -0.055145263671875,
  -0.006084442138671875,
  -0.0672607421875,
  -0.010406494140625,
  0.046478271484375,
  0.0202484130859375,
  0.005222320556640625,
  0.0100555419921875,
  -0.02508544921875,
  -0.004711151123046875,
  0.01174163818359375,
  -0.0244140625,
  -0.0158843994140625,
  -0.0230712890625,
  -0.0277557373046875,
  -0.0159912109375,
  0.0085906982421875,
  -0.04150390625,
  -0.03424072265625,
  0.0215301513671875,
  -0.0311431884765625,
  -0.032928466796875,
  0.0251922607421875,
  -0.01308441162109375,
  0.03997802734375,
  -0.018463134765625,
  0.0301666259765625,
  -0.0143585205078125,
  0.054168701171875,
  0.0654296875,
  0.002384185791015625,
  0.02825927734375,
  0.007732391357421875,
  -0.0208282470703125,
  0.0232391357421875,
  -0.06109619140625,
  -0.0195770263671875,
  0.061187744140625,
  -0.0374755859375,
  -0.03399658203125,
  0.03656005859375,
  0.0179443359375,
  0.0204620361328125,
  0.03216552734375,
  0.0221710205078125,
  -0.053955078125,
  0.00444793701171875,
  0.0156402587890625,
  0.01151275634765625,
  0.00012099742889404297,
  -0.0609130859375,
  0.01355743408203125,
  0.0758056640625,
  -0.035797119140625,
  -0.019012451171875,
  -0.036163330078125,
  -0.0183868408203125,
  0.040435791015625,
  -0.0087738037109375,
  0.050628662109375,
  -0.0155792236328125,
  -0.031463623046875,
  -0.0091705322265625,
  -0.09796142578125,
  -0.0224761962890625,
  -0.006206512451171875,
  -0.00885772705078125,
  0.038909912109375,
  -0.04290771484375,
  -0.025970458984375,
  -0.05926513671875,
  -0.0217437744140625,
  0.00484466552734375,
  -0.02606201171875,
  0.004047393798828125,
  -0.0008873939514160156,
  -0.0142059326171875,
  -0.0213623046875,
  0.00557708740234375,
  0.0211944580078125,
  -0.0640869140625,
  0.0771484375,
  -0.0025177001953125,
  -0.00555419921875,
  -0.0283660888671875,
  -0.00537109375,
  0.02294921875,
  0.05523681640625,
  0.0027675628662109375,
  0.02252197265625,
  0.046478271484375,
  -0.04833984375,
  -0.0090179443359375,
  -0.0140533447265625,
  0.01227569580078125,
  -0.006244659423828125,
  0.004878997802734375,
  -0.0055084228515625,
  0.0219573974609375,
  -0.01499176025390625,
  0.0286407470703125,
  0.0460205078125,
  0.04168701171875,
  -0.0285797119140625,
  0.00466156005859375,
  -0.01076507568359375,
  -0.0443115234375,
  0.05572509765625,
  0.0236663818359375,
  0.005214691162109375,
  0.042877197265625,
  0.0201873779296875,
  -0.01251220703125,
  -0.00823211669921875,
  -0.0003542900085449219,
  -0.011871337890625,
  -0.0281982421875,
  -0.0467529296875,
  0.00922393798828125,
  0.01265716552734375,
  0.078369140625,
  0.022003173828125,
  -0.043212890625,
  0.0097808837890625,
  0.0019054412841796875,
  -0.024169921875,
  0.024810791015625,
  -0.006740570068359375,
  0.00902557373046875,
  -0.00457763671875,
  -0.03546142578125,
  -0.005130767822265625,
  -0.039947509765625,
  -0.006420135498046875,
  0.033477783203125,
  0.03118896484375,
  -0.02337646484375,
  0.04803466796875,
  0.0031223297119140625,
  0.01092529296875,
  0.04547119140625,
  -0.042022705078125,
  -0.039337158203125,
  -0.0255126953125,
  0.0288543701171875,
  -0.03515625,
  0.0030651092529296875,
  0.01016998291015625,
  0.01293182373046875,
  0.0286407470703125,
  0.0309906005859375,
  0.034149169921875,
  -0.0164337158203125,
  -0.0103759765625,
  0.006336212158203125,
  0.016204833984375,
  0.04229736328125,
  0.013397216796875,
  -0.011077880859375,
  0.0173797607421875,
  -0.018951416015625,
  -0.079345703125,
  -0.06341552734375,
  -0.045928955078125,
  -0.03131103515625,
  -0.004772186279296875,
  -0.03289794921875,
  -0.00513458251953125,
  -0.0081329345703125,
  0.004428863525390625,
  -0.0081939697265625,
  -0.019134521484375,
  0.0016164779663085938,
  0.0028209686279296875,
  0.03033447265625,
  -0.009033203125,
  0.01351165771484375,
  -0.036468505859375,
  -0.0234222412109375,
  0.00034308433532714844,
  -0.0027141571044921875,
  0.004791259765625,
  -0.01482391357421875,
  -0.0156402587890625,
  0.035980224609375,
  0.00611114501953125,
  0.0184326171875,
  -0.02685546875,
  -0.0010061264038085938,
  0.024078369140625,
  0.0101470947265625,
  0.0195770263671875,
  0.023223876953125,
  -0.006473541259765625,
  -0.0083160400390625,
  -0.0269775390625,
  -0.0067138671875,
  0.025054931640625,
  -0.00901031494140625,
  -0.007293701171875,
  0.004169464111328125,
  0.0305938720703125,
  -0.0284576416015625,
  -0.023223876953125,
  0.00012886524200439453,
  0.01378631591796875,
  0.0202178955078125,
  -0.0178680419921875,
  -0.00907135009765625,
  0.03399658203125,
  -0.001483917236328125,
  -0.03790283203125,
  -0.054779052734375,
  0.0390625,
  -0.01214599609375,
  0.01152801513671875,
  -0.002353668212890625,
  0.0253143310546875,
  -0.04034423828125,
  -0.025787353515625,
  0.0091705322265625,
  -0.01407623291015625,
  0.0034332275390625,
  0.0217132568359375,
  -0.00978851318359375,
  -0.018341064453125,
  -0.0467529296875,
  0.00534820556640625,
  -0.0194854736328125,
  0.050933837890625,
  0.0078887939453125,
  0.0268096923828125,
  -0.004039764404296875,
  -0.0058746337890625,
  -0.01386260986328125,
  -0.03277587890625,
  -0.022918701171875,
  0.017913818359375,
  -0.0281829833984375,
  0.002750396728515625,
  0.048583984375,
  -0.05181884765625,
  0.01373291015625,
  0.0191802978515625,
  -0.045074462890625,
  0.0227508544921875,
  -0.005794525146484375,
  0.005855560302734375,
  -0.0286865234375,
  -0.00438690185546875,
  0.0167083740234375,
  0.01776123046875,
  0.01441192626953125,
  0.0309295654296875,
  -0.054656982421875,
  -0.0115814208984375,
  0.00843048095703125,
  -0.0034427642822265625,
  0.004421234130859375,
  -0.0057220458984375,
  -0.005252838134765625,
  -0.020172119140625,
  -0.0143585205078125,
  -0.0275115966796875,
  0.0030689239501953125,
  -0.0163421630859375,
  0.0249786376953125,
  0.0174713134765625,
  -0.0246124267578125,
  -0.0023288726806640625,
  0.025543212890625,
  0.0092926025390625,
  -0.0104827880859375,
  -0.0209503173828125,
  0.0006165504455566406,
  0.005748748779296875,
  0.024658203125,
  -0.02996826171875,
  -0.0223541259765625,
  0.015655517578125,
  -0.0210723876953125,
  -0.030120849609375,
  -0.005527496337890625,
  0.0022125244140625,
  0.03973388671875,
  0.0204925537109375,
  0.040863037109375,
  -0.004150390625,
  0.004486083984375,
  0.034423828125,
  -0.02996826171875,
  0.017425537109375,
  0.004688262939453125,
  -0.0182647705078125,
  -0.004917144775390625,
  -0.00907135009765625,
  -0.0272979736328125,
  -0.00015056133270263672,
  -0.0308380126953125,
  0.0321044921875,
  0.032928466796875,
  0.0196380615234375,
  0.006839752197265625,
  -0.01332855224609375,
  0.020233154296875,
  0.016693115234375,
  -0.0167083740234375,
  0.0008406639099121094,
  -0.00302886962890625,
  -0.0042877197265625,
  0.04083251953125,
  -0.036041259765625,
  0.0120391845703125,
  0.0302886962890625,
  0.00870513916015625,
  0.0056304931640625,
  -0.04296875,
  -0.03460693359375,
  0.0008516311645507812,
  0.005916595458984375,
  -0.034637451171875,
  -0.0260162353515625,
  0.02435302734375,
  0.0138397216796875,
  0.0258636474609375,
  0.0011034011840820312,
  0.0325927734375,
  -0.01227569580078125,
  -0.0238189697265625,
  -0.0265350341796875,
  0.037445068359375,
  -0.0218963623046875,
  -0.042694091796875,
  -0.0064849853515625,
  0.004024505615234375,
  -0.00426483154296875,
  -0.024017333984375,
  0.0168914794921875,
  -0.046112060546875,
  -0.0325927734375,
  -0.02783203125,
  -0.0187530517578125,
  0.002368927001953125,
  0.01372528076171875,
  -0.0010881423950195312,
  -0.0026073455810546875,
  0.0069580078125,
  -0.0278167724609375,
  0.035675048828125,
  -0.0187835693359375,
  -0.00934600830078125,
  0.038238525390625,
  -0.0222015380859375,
  -0.0258026123046875,
  0.0133819580078125,
  0.01032257080078125,
  0.03863525390625,
  0.004932403564453125,
  0.032135009765625,
  -0.0240936279296875,
  -0.004764556884765625,
  -0.0281524658203125,
  -0.009307861328125,
  0.006381988525390625,
  -0.003490447998046875,
  -0.01233673095703125,
  0.00711822509765625,
  0.0009446144104003906,
  -0.00665283203125,
  -0.002658843994140625,
  0.0215301513671875,
  0.004283905029296875,
  -0.01373291015625,
  -0.015838623046875,
  0.002216339111328125,
  0.002552032470703125,
  -0.036407470703125,
  -0.0006055831909179688,
  -0.004436492919921875,
  0.0114288330078125,
  0.004932403564453125,
  -0.0233306884765625,
  0.003879547119140625,
  -0.0059967041015625,
  0.00628662109375,
  0.004993438720703125,
  -0.00885009765625,
  0.01398468017578125,
  0.0163421630859375,
  -0.03192138671875,
  -0.00481414794921875,
  0.01020050048828125,
  -0.025299072265625,
  -0.0307159423828125,
  -0.0162811279296875,
  0.023773193359375,
  -0.04888916015625,
  0.045806884765625,
  0.0018014907836914062,
  -0.026153564453125,
  -0.0445556640625,
  -0.025482177734375,
  -0.01500701904296875,
  0.0282135009765625,
  0.039794921875,
  -0.044189453125,
  -0.0081939697265625,
  0.0163116455078125,
  0.0273590087890625,
  -0.01163482666015625,
  -0.03070068359375,
  -0.01788330078125,
  0.03228759765625,
  -0.01800537109375,
  0.0284271240234375,
  -0.0253753662109375,
  0.03179931640625,
  0.0253143310546875,
  0.0196380615234375,
  -0.047943115234375,
  0.0113525390625,
  0.0023708343505859375,
  -0.0027179718017578125,
  -0.0032520294189453125,
  -0.0007486343383789062,
  -0.0189056396484375,
  -0.00464630126953125,
  -0.0307769775390625,
  -0.0174407958984375,
  0.0255126953125,
  -0.0154571533203125,
  -0.0343017578125,
  0.05609130859375,
  0.005901336669921875,
  -0.023345947265625,
  -0.032196044921875,
  0.03167724609375,
  -0.003292083740234375,
  0.044097900390625,
  0.000804901123046875,
  0.026611328125,
  0.0147705078125,
  -0.0151214599609375,
  -0.0024204254150390625,
  -0.0022068023681640625,
  -0.0019168853759765625,
  0.0010957717895507812,
  0.0260467529296875,
  -0.004459381103515625,
  0.04205322265625,
  0.0160980224609375,
  -0.0068359375,
  0.0277099609375,
  -0.011260986328125,
  -0.0201568603515625,
  -0.0176544189453125,
  0.0291595458984375,
  0.002964019775390625,
  0.0227508544921875,
  -0.009368896484375,
  0.01369476318359375,
  0.0248870849609375,
  -0.01134490966796875,
  -0.0247802734375,
  -0.0301666259765625,
  0.042083740234375,
  0.017730712890625,
  0.0044708251953125,
  -0.0034332275390625,
  0.037933349609375,
  0.031463623046875,
  0.0177764892578125,
  -0.01538848876953125,
  -0.042999267578125,
  0.0126190185546875,
  0.016387939453125,
  -0.0171051025390625,
  -0.03607177734375,
  -0.017669677734375,
  0.0109405517578125,
  0.0102691650390625,
  0.01444244384765625,
  0.0095062255859375,
  -0.0010328292846679688,
  -0.01334381103515625,
  -0.007160186767578125,
  -0.003055572509765625,
  0.04541015625,
  0.0239715576171875,
  -0.0183258056640625,
  0.05255126953125,
  -0.0249176025390625,
  0.01824951171875,
  -0.0272979736328125,
  -0.061553955078125,
  -0.005901336669921875,
  -0.031524658203125,
  -0.01227569580078125,
  0.0023021697998046875,
  -0.004100799560546875,
  -0.05487060546875,
  0.0264739990234375,
  0.01885986328125,
  -0.004665374755859375,
  0.0219573974609375,
  0.035888671875,
  -0.0146026611328125,
  0.016876220703125,
  0.002468109130859375,
  0.015960693359375,
  0.011138916015625,
  0.0255126953125,
  0.020477294921875,
  -0.003238677978515625,
  0.001598358154296875,
  0.006862640380859375,
  0.0256195068359375,
  -0.005214691162109375,
  0.0101165771484375,
  0.01369476318359375,
  -0.035247802734375,
  0.0190582275390625,
  0.031951904296875,
  -0.0029621124267578125,
  -0.0194854736328125,
  -0.014984130859375,
  0.035064697265625,
  -0.005779266357421875,
  0.043304443359375,
  0.00457000732421875,
  0.005565643310546875,
  0.019989013671875,
  -0.0215911865234375,
  -0.029205322265625,
  -0.0271148681640625,
  0.00470733642578125,
  -0.0033969879150390625,
  -0.007144927978515625,
  -0.0115509033203125,
  0.00396728515625,

In [35]:
qdrant_client.upsert(collection_name = collection_name,
points = point_structs[0:500],
wait=True
)

UpdateResult(operation_id=3, status=<UpdateStatus.COMPLETED: 'completed'>)

In [36]:
qdrant_client.upsert(collection_name = collection_name,
points = point_structs[500:],
wait=True
)

UpdateResult(operation_id=4, status=<UpdateStatus.COMPLETED: 'completed'>)

### Hybrid Retrieval

In [39]:
def retrieve_context(query, k=5):
    query_embedding = get_embedding(query)

    results = qdrant_client.query_points(
        collection_name=collection_name, 
        prefetch = [
            Prefetch(query = query_embedding, using = "text-embedding-3-small", limit = 20),
            Prefetch(query = Document(text=query, model = "qdrant/bm25"), using = "bm25", limit = 20)
        ],
        query=FusionQuery(fusion="rrf"), 
        limit=k)

    context_ids = []
    context = []
    scores = []
    ratings = []

    print(results)
    for pt in results.points:
        context_ids.append(pt.payload['parent_asin'])
        context.append(pt.payload['preprocessed_description'])
        scores.append(pt.score)
        ratings.append(pt.payload['average_rating'])
        
    return {
        'retrieved_context_ids': context_ids,
        'retrieved_context': context,
        'similarity_scores': scores,
        'retrieved_context_ratings': ratings
    }

In [48]:
results = retrieve_context("do you have any 4k webcams ?", k = 20)

points=[ScoredPoint(id=826, version=4, score=0.75, payload={'preprocessed_description': 'DEPSTECH Webcam with Microphone, 2K HD Web Camera with Auto Light Correction, Plug and Play USB Webcam and 90° View Angle for Desktop/Streaming/Video Calling Recording/Meeting/Online Teaching【2K QHD Webcam】The HD camera with a 1/2.9”CMOS image sensor delivers sharp and crystal clear video up to a 2560 x 1440 resolution video at a fluid 30 FPS, specially suitable for professional live streaming or recording like detailed makeup tutorials or other online teaching. 【Webcam with Microphone】This web camera built-in microphone with automatic noise reduction make the recording sound clearer, more natural under some noise environments, providing better sound recognition and smooth transmission. 【Smooth Live Streaming Webcam】With automatic low light correction tech, the USB camera captures excellent 2K QHD video at a widescreen angle of up to 90 degrees, even in dimly environment. It also support faster data transfer via USB 3.0/2.0 interface and ensure a smooth live streaming. 【Easy to Operate & Wide Compatible】No additional driver or software required, just connect the PC webcam to a computer USB port and start play. Compatible with most software and operating systems including Windows XP and Mac OS, Smart TV. 【Adjustable Position】The webcam for desktop supports 360°horizontal rotation, 180 degree adjustment in vertical direction and even support installation on tripod or pan tilt head, easy to adjust for suitable record position. To protect the privacy, you can turn the camera to a safe direction when it is not in use.', 'image': 'https://m.media-amazon.com/images/I/31msF7N7bWL._AC_.jpg', 'rating_number': 520, 'price': None, 'average_rating': 3.9, 'parent_asin': 'B08CMV4GF6'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=993, version=4, score=0.6666667, payload={'preprocessed_description': "Acetaken Webcam Mount - Flexible Gooseneck Arm Clamp Stand Tripod for Logitech Webcam C920s C920 C930e C922x C930 C922 C925e C615 Brio - 25 inchesWebcam Mount head: Ball-Head adapter with 1/4'' Screw Thread to Connect Your webcam's 1/4'' Screw Hole; Webcam Gooseneck: Extend to the max approx.64cm / 25 inches, Easy to Adjust any angle as your request; Webcam Mount Compatible for Logitech Webcam C920s C920 C925e C922x C922 C930e C930 C615, Brio 4K; Webcam Clamp fit the Desk,Table,Sideboard,Bed Max thickness 5.5cm(2 inches); Better work than webcam Tripod; Webcam Arm max Load 1.5 LBS (0.7kg); Not for heavy Camera and devices; (Webcam NOT included Packing)", 'image': 'https://m.media-amazon.com/images/I/31nFW8uQ3iL._AC_.jpg', 'rating_number': 207, 'price': 19.99, 'average_rating': 4.4, 'parent_asin': 'B082HQJ1JX'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=976, version=4, score=0.4761905, payload={'preprocessed_description': 'Webcam Cover, Camera Cover Slide, Privacy Covers, 0.02-Inch Ultra-Thin Webcam Cover for Laptop, PC, Phone, Protect Your Privacy and Security (Leopard Texture -3 Pack)[Full Pattern] Different from other classical Black webcam covers, our unique full pattern can decorate your laptop/iPad, making your device look different. [Guard Your Privacy] Our Webcam Cover Slide efficiently protects your privacy and prevents unwanted hacking attacks. It also protects your webcam from dirt and dust. [Fits For Most Devices] Compatible with MacBook Pro, MacBook Air, Mac, laptops, Microsoft Surface, iPad, Android tablet, PC, computer, all-in-one desktop, iPhone and other Android smart phone. It does not interfere with webcam usage or web signal and will not damage your device in any way. [Easy To Use] Simply align to your webcam, attach and press firmly for 15 seconds for a strong. And if you want to change other webcam covers, the adhesive can be easily applied and removed from the device without leaving any traces. [What You Get] 3 X Leopard texture Webcam Cover, 1 X installation guide, and our worry-free 18 Month and friendly customer service. If the product has any question, please contact us we will try our best to help you.', 'image': 'https://m.media-amazon.com/images/I/51qkPf4KD5L._AC_.jpg', 'rating_number': 269, 'price': 6.99, 'average_rating': 4.2, 'parent_asin': 'B08R9GPKRH'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=724, version=4, score=0.45833334, payload={'preprocessed_description': 'Webcam 1080P Full HD Auto Focus Web Camera with Microphone Widescreen USB Computer Camera for PC Laptop Desktop Mac Streaming Video Calling Recording Video Conference Online Teaching Business GamingBuilt-in digital stereo MIC with automatic noise reduction and echo-canceling technology makes the sound purer, clearer and more natural. It can pick up your voice even at 10ft distance. Everyone hears the real you. 5 Million pixels auto focus: Getting rid of tedious focusing process. Our web camera is with 1080P high-definition camera and true color images. Plug And Play: USB 2.0 connector, no need to download or install complicated driver software. It means you needn’t set up any specific driver or software. Our Webcam can plug and play, easy and convenient. Fits for multiple operations including Windows 2000/XP/7/8/10 and above, Mac OS, Android 5.0 or higher version. Works when you need HD video,clear and smooth video conference and video meeting. Works with many video conferencing software applications such as Zoom, Google Meet, Skype For Business, Microsoft Teams and WebEx. Free return for refund or replacement if you are not satisfied with our products. If there are any questions, please feel free to contact us. We are always here to serve you. Also, welcome to share your opinions, we may take your advice to the next design.', 'image': 'https://m.media-amazon.com/images/I/415FK9xNRTL._AC_.jpg', 'rating_number': 310, 'price': None, 'average_rating': 4.1, 'parent_asin': 'B087986YPY'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=584, version=4, score=0.45, payload={'preprocessed_description': 'HD 1080P Webcam with Microphone, USB(2.0/3.0) Computer Camera for Live Streaming Webcam,110 Degrees Wide-Angle 30fps for Laptop, Noise Reduction Desktop, Conferencing, Video ChattingReads Smart Cards and Military Common Access Cards (CAC) Compatible with Microsoft Windows XP/Vista/7/10 Not recommended for Mac OS 10.7 and newer USB Connection', 'image': 'https://m.media-amazon.com/images/I/4199jghCXoL._AC_.jpg', 'rating_number': 321, 'price': None, 'average_rating': 4.4, 'parent_asin': 'B002XJG71M'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=238, version=3, score=0.36666667, payload={'preprocessed_description': 'ELECOM Facial Recognition Webcam, Windows Hello Full HD 1080P 30FPS, Streaming, Compatible with Windows 11, Windows 10, Easy Login for Desktop & Laptop (UCAM-CF20FBBK)📷《FACIAL RECOGNITION: WINDOWS 11 10 HELLO FACE》 Compatible with Windows 11 10 Hello Face, which enables you to log into Windows 11 10 just by turning your face to the camera, easy, speedy login without typing password. 📷《FULL HD 1080P USB WEBCAM》 80° wide angle lens captures high definition image and video at Full HD 1080P. Perfect for streaming on social media live such as Twitch, YouTube, Xbox one, Streamlabs OBS, Xsplit, Mixer, Facebook and Vloging. The camera weight is only 3oz, easy to carry with you anywhere. 📷《PLUG & PLAY; NO DRIVERS REQUIRED》 This is a plug & play webcam camera, it is easy to be used by just plugging it with the USB 2.0 cable to the computer, then it can display excellent video in time, no need to install any driver to make this webcam work. Perfect for streaming on social media and gaming. 📷《BUILT-IN HIGH QUALITY MICROPHONE & NOISE REDUCTION》 The built-in microphone offers a super clear communication, available to capture audio. The microphone is designed with echo and noise reduction technology, which allows the communication to be clear enough, just like you are talking to someone face to face. Great for Zoom / Facetime / Video Calling / OBS / Twitch / Facebook/ YouTube/ Xbox one/ Conferencing / Gaming / Streaming / Recording / Online School. 📷《PRODUCT DETAILS》 Features up to a 1080P resolution (up to 1920 x 1080 pixels) at 30 fps. Effective pixel count: Approx. 2.0 megapixels. Works with USB 2.0, NO additional drivers required. View angle is 80° wide. Supports Windows 11 10. Product size: H3.9"(100mm) X W2.5"(64mm) X H1"(26.5mm). USB cable length:4 inch (100mm). Product weight: 3oz(85g).', 'image': 'https://m.media-amazon.com/images/I/31c-s1NyYTL._AC_.jpg', 'rating_number': 464, 'price': 45.99, 'average_rating': 4.2, 'parent_asin': 'B0B7QT2KXY'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=527, version=4, score=0.14285715, payload={'preprocessed_description': 'Video Conference Lighting,6.3" Selfie Ring Light with Clamp Mount for Video Conferencing,Webcam Light with 3 Light Modes&6 Level Dimmable for Laptop/PC Monitor/Desk/Bed/Office/Makeup/YouTube/TIK Tok', 'image': 'https://m.media-amazon.com/images/I/411nXo1UisS._AC_.jpg', 'rating_number': 702, 'price': None, 'average_rating': 4.2, 'parent_asin': 'B08PYY2TCC'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=479, version=3, score=0.125, payload={'preprocessed_description': "FHH Security Camera 2K Cameras for Home Security with Night Vision, Two-Way Audio,Motion Detection, Phone APP,Remote Contol Indoor WiFi Camera,Ideal for Baby Monitor/Pet Camera2K LIVE STEAM from ANYWHERE: Home security cameras with super clear 2K UHD provide high-quality video right in the palm of your hand. Swipe up, down, left, and right on your phone to rotate and set your baby camera's point of view in real time. CLEAR NIGHT VISION and REMOTE PAN&TILT: The infrared night vision function ensures clear, vivid pictures and stunning surveillance both during the day and at night. The camera can track up to 355° Horizontal & 110° Vertical rotation range to create a complete 360°coverage. SMART MOTION DETECTION & ALARM WITH RECORDING: FHH indoor camera is fitted with an advanced detection algorithm that automatically captures snapshots and videos when it detects movements and immediately sends a real-time notification to your smartphone via FHH App. Features motion sensibility adjustment, accurate and smart motion detection to reduce false alarm. TWO-WAY AUDIO & LOCAL STORAGE: This wifi camera is fitted with microphones and speaker that lets you talk or listen to family member, friends, pets or chase away intruders in a distance. Enjoy storing up to 128GB of SD (NO SD card is INCLUDED). Store and record daily events and keep your home and loved ones safe. Enhanced FHH App :A lot of home security cameras require complex configuration before use, considering customers' needs, our camera is however such amazingly easy to configure. FHH pet cameras with app are basically a three step installation process, install an App, log into your WiFi, and scan a QR code, it really is that simple.(This indoor surveillance camera must be connected with 2.4Ghz WiFi when the first time connect.", 'image': 'https://m.media-amazon.com/images/I/41jhvH52fkL._AC_.jpg', 'rating_number': 1163, 'price': None, 'average_rating': 3.8, 'parent_asin': 'B09YRZ8VDV'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=214, version=3, score=0.11111111, payload={'preprocessed_description': "ENSTER 2.4/5GHz Dual Band WiFi Camera,24/7 Recording Security Camera Outdoor,Wide Angle Surveillance Camera, 1080P Home Security Camera,Two-Way Audio,4X Zoom,Motion Detection,Waterproof,Night Vision【2.4Ghz AND 5Ghz DUAL BAND】Worried that cameras for home security cannot be used with the wifi at home? This surveillance camera can connect 2.4ghz and 5ghz wifi. Avoid crowded 2.4ghz wifi and quickly access videos. Once connected, you can view the video at any time on the android and ios phone camhi app anywhere. You can choose to install the camera outside with wired connection, such as gate, front door, garden, backyard, garage, corridor, kitchen, living room, etc. 【1080P 110°WIDE ANGLE & LONG RANGE SIGNAL】Wide angle outdoor camera with high resolution images in 1080p at 25 frames per second, combined with a 110° lens and universal ball mount delivers clarity in every direction. A wider angle than equivalent high definition cctv camera. Two 5db paddle antennas, than the others exterior home security camera of 3db circular antenna, more powerful, more stable signal, monitoring picture will be more smooth. 【MOTION DETECTION & TWO WAY AUDIO】 The 5g security camera with motion sensor picks up your kids when they are in the backyard. The app notifies you when there is human movement. After the motion detection is triggered, the SD card will automatically record(support 24/7 recording), push notification to the mobile phone, receive push email and FTP upload. At the same time, you can use two-way audio to talk to your child anywhere. 【IP66 WATERPROOF & 100FT NIGHT VISION】The weatherproof outdoor camera adopts high-quality casing which is sturdy and durable, waterproof and strong enough to withstand severe weather such as typhoon and heavy rain (-10°C~55°C), ensuring excellent performance when used for outdoor monitoring. No matter how dark the night is, you will not let go of everyone's small actions, you can sleep peacefully. Infrared video in 100FT is recorded in SD card. 【24/7 RECORD & WARRANTY】The 5ghz wifi camera outdoor supports 24/7 recording. The video will be saved in the SD card and be viewed directly on the mobile phone. Maximum support 128g memory card, up to 90 days of video. If you have any questions please contact us through your order on Amazon, or send email to us, we will offer solutions to make you satisfied with our 5g security camera! Please rest assured to buy.", 'image': 'https://m.media-amazon.com/images/I/31e2+uRndyL._AC_.jpg', 'rating_number': 544, 'price': None, 'average_rating': 3.8, 'parent_asin': 'B07SFFT6TQ'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=597, version=4, score=0.11111111, payload={'preprocessed_description': 'Amazon Basics DisplayPort to HDMI Display Cable, Uni-Directional, 4K@60Hz, 1920x1200, 1080p, Gold-Plated Plugs, 6 Foot, BlackIN THE BOX: (1) 6 foot DisplayPort HDMI display cable for transmitting high-def audio and video from DisplayPort enabled computers to HDMI displays SUPPORTS 4K VIDEO: Supports 4K@60Hz for enhanced gaming or streaming video to a home theater, projector, or monitor with 4K high resolution EASY TO CONNECT: Connect and configure monitors for dual screen or mirrored display CRYSTAL CLEAR TRANSMISSION: Gold-plated connectors deliver crystal clear audio and video; durable cable housing for longevity PLUG & PLAY DESIGN: does not require drivers or software UNI-DIRECTIONAL: This is a uni-directional cable that supports DisplayPort to HDMI only; does not support HDMI to DisplayPort (not bi-directional)', 'image': 'https://m.media-amazon.com/images/I/41BWJaN9BTL._AC_.jpg', 'rating_number': 659, 'price': 12.09, 'average_rating': 4.5, 'parent_asin': 'B08FBZ6SS3'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=460, version=3, score=0.1, payload={'preprocessed_description': 'Lenovo IdeaPad 3 15 Intel i3-10110U 8GB 256GB SSD 15.6-inch Touch Screen Laptop10th Gen Intel Core i3-10110U Dual-Core Processor 2.1GHz processor 4.1 GHz Turbo / 8GB DDR4 2666 SDRAM / 256GB NVMe Solid State Drive 15.6-inch LED Touch Screen Display (1366 x 768) / Integrated Intel UHD Graphics Dolby Audio with 2 x 1.5W Speakers / 802.11ac Wi-Fi + Bluetooth / Media Card reader / Webcam with Microphone 2 USB 3.0 Ports / 1 USB 2.0 Port / 1 HDMI Out 2 Cell Lithium-polymer Battery / 45W AC Adapter / Windows 10 Home in S mode / Color: Abyss Blue', 'image': 'https://m.media-amazon.com/images/I/41HAq6TYYKS._AC_.jpg', 'rating_number': 325, 'price': 400.0, 'average_rating': 4.4, 'parent_asin': 'B0C58RYFHW'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=759, version=4, score=0.1, payload={'preprocessed_description': 'Samsung Gear 360 Degree Spherical Camera (SM-C200) for Galaxy S7, S7 Edge, S6, S6 Edge, S6 Edge Plus, Note 5 (International Version - No Warranty)Immersive 360 Cam High-Res Video and Photo F2.0 Dual Lenses Clear in Low Light / High Resolution 3840x1920 Video Time-Lapse Video Real 360 Event Logging MicroSD card is required for shooting.', 'image': 'https://m.media-amazon.com/images/I/31LF9wcJrgL._AC_.jpg', 'rating_number': 338, 'price': None, 'average_rating': 3.9, 'parent_asin': 'B01M4J53CO'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=190, version=3, score=0.09090909, payload={'preprocessed_description': 'Full HD 1080P Home WiFi Camera, 360 Degree Panoramic Wireless Security IP Camera for Home Baby Pet Monitor Remote Viewing Camera Night Vision Motion Detection Wireless Camera 2.4GHz【360° View Angle &1080P Full HD Cam】Tired of the blind area of traditional dome or bullet camera? this cameras come with FULL HD 1080P resolution.Built in 1.44mm Fish-Eye Lens, this camera will provide you with 360 degree panoramic viewing angle without blind area! You can monitor the whole room (up to 400 square foot) with 1 single camera! 【Motion Detection & Alarm Function】: Alert notification will be pushed to your smartphone when motion is detected by security camera,So you don’t need to worry the thief break into your house when you are outside, which makes your place safer. 【Wireless Connection & Work with iCSee】Panoramic camera only supports 2.4G Wi-Fi (doesn’t support 5G Wi-Fi).Follow the steps of the instruction manual,connect camera to your 2.4G wifi router.You can monitor it via iCSee APP anywhere anytime after connection to router,it is conveniencw and practically for your life. 【Comes with AP Spots】Each panoramic camera owns a unique available hotspot,the available hotspot only can assist you to connect to the 2.4G WiFi router.Even if you are not on wifi environment,you can connect to it easily. 【Please Note Before Use】It can be directly installed normally,just make sure that place in 2.4Ghz wifi range.If you can’t connect, please check if your router’s firewall is turned off and wifi is 2.4GHZ,(As some routers are 5G and 2.4G 2-in-1,it may take longer to connect during the wifi automatic switching process,pls wait patiently), you can also reconnect by resetting the camera.', 'image': 'https://m.media-amazon.com/images/I/31PrOgEi9-L._AC_.jpg', 'rating_number': 1687, 'price': None, 'average_rating': 3.3, 'parent_asin': 'B07M9Q2PL4'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=812, version=4, score=0.09090909, payload={'preprocessed_description': 'Monoprice HDMI High Speed Cable - 4 Feet - Black, 4K@60Hz, HDR, 10.2 Gbps, 36AWG, YUV 4:2:0 - Ultra Slim SeriesSupports 4k UHD High Resolution HDTVs Connects HDMI-enabled devices, including PS4, PS3, Xbox, Apple TV, Roku, Blu-Ray players and computers to HDMI-enabled displays, A/V receivers and more Supports Ethernet, 3D, 4K, Audio Return Channel, FHD, Deep Color, HDMI-CEC and HDCP', 'image': 'https://m.media-amazon.com/images/I/31cqP-YUcpL.jpg', 'rating_number': 372, 'price': 10.49, 'average_rating': 4.6, 'parent_asin': 'B078L3Q89G'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=691, version=4, score=0.083333336, payload={'preprocessed_description': "Bysameyee HD 2MP 2K USB Microscope, 40X to 1000X Magnification Digital Microscope Camera Inspection Endoscope with Carrying Case, Compatible with Windows 7 8 10, Mac, Linux, OTG Android PhonesReal HD 2MP Microscope Camera: 1080P HD 2MP Camera with 8 adjustable LED lights, provide excellent detail and optimal clarity. It is good for any inspection environment and ensures the magnified images are clear and bright. 40X more magnification can meet your daily needs. Capture, Record & Measure: Connected this handheld microscope to devices, you can capture screenshot images by the SNAP button and record a video with installed software/App. Please not

In [49]:
results

{'retrieved_context_ids': ['B08CMV4GF6',
  'B082HQJ1JX',
  'B08R9GPKRH',
  'B087986YPY',
  'B002XJG71M',
  'B0B7QT2KXY',
  'B08PYY2TCC',
  'B09YRZ8VDV',
  'B07SFFT6TQ',
  'B08FBZ6SS3',
  'B0C58RYFHW',
  'B01M4J53CO',
  'B07M9Q2PL4',
  'B078L3Q89G',
  'B08XXQCBSZ',
  'B014RONV5K',
  'B0B5LRMSQX',
  'B0B7BHY16V',
  'B075NFX24N',
  'B0B4Z7V3XG'],
 'retrieved_context': ['DEPSTECH Webcam with Microphone, 2K HD Web Camera with Auto Light Correction, Plug and Play USB Webcam and 90° View Angle for Desktop/Streaming/Video Calling Recording/Meeting/Online Teaching【2K QHD Webcam】The HD camera with a 1/2.9”CMOS image sensor delivers sharp and crystal clear video up to a 2560 x 1440 resolution video at a fluid 30 FPS, specially suitable for professional live streaming or recording like detailed makeup tutorials or other online teaching. 【Webcam with Microphone】This web camera built-in microphone with automatic noise reduction make the recording sound clearer, more natural under some noise environments, providing better sound recognition and smooth transmission. 【Smooth Live Streaming Webcam】With automatic low light correction tech, the USB camera captures excellent 2K QHD video at a widescreen angle of up to 90 degrees, even in dimly environment. It also support faster data transfer via USB 3.0/2.0 interface and ensure a smooth live streaming. 【Easy to Operate & Wide Compatible】No additional driver or software required, just connect the PC webcam to a computer USB port and start play. Compatible with most software and operating systems including Windows XP and Mac OS, Smart TV. 【Adjustable Position】The webcam for desktop supports 360°horizontal rotation, 180 degree adjustment in vertical direction and even support installation on tripod or pan tilt head, easy to adjust for suitable record position. To protect the privacy, you can turn the camera to a safe direction when it is not in use.',
  "Acetaken Webcam Mount - Flexible Gooseneck Arm Clamp Stand Tripod for Logitech Webcam C920s C920 C930e C922x C930 C922 C925e C615 Brio - 25 inchesWebcam Mount head: Ball-Head adapter with 1/4'' Screw Thread to Connect Your webcam's 1/4'' Screw Hole; Webcam Gooseneck: Extend to the max approx.64cm / 25 inches, Easy to Adjust any angle as your request; Webcam Mount Compatible for Logitech Webcam C920s C920 C925e C922x C922 C930e C930 C615, Brio 4K; Webcam Clamp fit the Desk,Table,Sideboard,Bed Max thickness 5.5cm(2 inches); Better work than webcam Tripod; Webcam Arm max Load 1.5 LBS (0.7kg); Not for heavy Camera and devices; (Webcam NOT included Packing)",
  'Webcam Cover, Camera Cover Slide, Privacy Covers, 0.02-Inch Ultra-Thin Webcam Cover for Laptop, PC, Phone, Protect Your Privacy and Security (Leopard Texture -3 Pack)[Full Pattern] Different from other classical Black webcam covers, our unique full pattern can decorate your laptop/iPad, making your device look different. [Guard Your Privacy] Our Webcam Cover Slide efficiently protects your privacy and prevents unwanted hacking attacks. It also protects your webcam from dirt and dust. [Fits For Most Devices] Compatible with MacBook Pro, MacBook Air, Mac, laptops, Microsoft Surface, iPad, Android tablet, PC, computer, all-in-one desktop, iPhone and other Android smart phone. It does not interfere with webcam usage or web signal and will not damage your device in any way. [Easy To Use] Simply align to your webcam, attach and press firmly for 15 seconds for a strong. And if you want to change other webcam covers, the adhesive can be easily applied and removed from the device without leaving any traces. [What You Get] 3 X Leopard texture Webcam Cover, 1 X installation guide, and our worry-free 18 Month and friendly customer service. If the product has any question, please contact us we will try our best to help you.',
  'Webcam 1080P Full HD Auto Focus Web Camera with Microphone Widescreen USB Computer Camera for PC Laptop Desktop Mac Streaming Video Calling Recording Video Conference Online Teaching Business GamingBuilt-in digital stereo MIC with automatic noise reduction and echo-canceling technology makes the sound purer, clearer and more natural. It can pick up your voice even at 10ft distance. Everyone hears the real you. 5 Million pixels auto focus: Getting rid of tedious focusing process. Our web camera is with 1080P high-definition camera and true color images. Plug And Play: USB 2.0 connector, no need to download or install complicated driver software. It means you needn’t set up any specific driver or software. Our Webcam can plug and play, easy and convenient. Fits for multiple operations including Windows 2000/XP/7/8/10 and above, Mac OS, Android 5.0 or higher version. Works when you need HD video,clear and smooth video conference and video meeting. Works with many video conferencing software applications such as Zoom, Google Meet, Skype For Business, Microsoft Teams and WebEx. Free return for refund or replacement if you are not satisfied with our products. If there are any questions, please feel free to contact us. We are always here to serve you. Also, welcome to share your opinions, we may take your advice to the next design.',
  'HD 1080P Webcam with Microphone, USB(2.0/3.0) Computer Camera for Live Streaming Webcam,110 Degrees Wide-Angle 30fps for Laptop, Noise Reduction Desktop, Conferencing, Video ChattingReads Smart Cards and Military Common Access Cards (CAC) Compatible with Microsoft Windows XP/Vista/7/10 Not recommended for Mac OS 10.7 and newer USB Connection',
  'ELECOM Facial Recognition Webcam, Windows Hello Full HD 1080P 30FPS, Streaming, Compatible with Windows 11, Windows 10, Easy Login for Desktop & Laptop (UCAM-CF20FBBK)📷《FACIAL RECOGNITION: WINDOWS 11 10 HELLO FACE》 Compatible with Windows 11 10 Hello Face, which enables you to log into Windows 11 10 just by turning your face to the camera, easy, speedy login without typing password. 📷《FULL HD 1080P USB WEBCAM》 80° wide angle lens captures high definition image and video at Full HD 1080P. Perfect for streaming on social media live such as Twitch, YouTube, Xbox one, Streamlabs OBS, Xsplit, Mixer, Facebook and Vloging. The camera weight is only 3oz, easy to carry with you anywhere. 📷《PLUG & PLAY; NO DRIVERS REQUIRED》 This is a plug & play webcam camera, it is easy to be used by just plugging it with the USB 2.0 cable to the computer, then it can display excellent video in time, no need to install any driver to make this webcam work. Perfect for streaming on social media and gaming. 📷《BUILT-IN HIGH QUALITY MICROPHONE & NOISE REDUCTION》 The built-in microphone offers a super clear communication, available to capture audio. The microphone is designed with echo and noise reduction technology, which allows the communication to be clear enough, just like you are talking to someone face to face. Great for Zoom / Facetime / Video Calling / OBS / Twitch / Facebook/ YouTube/ Xbox one/ Conferencing / Gaming / Streaming / Recording / Online School. 📷《PRODUCT DETAILS》 Features up to a 1080P resolution (up to 1920 x 1080 pixels) at 30 fps. Effective pixel count: Approx. 2.0 megapixels. Works with USB 2.0, NO additional drivers required. View angle is 80° wide. Supports Windows 11 10. Product size: H3.9"(100mm) X W2.5"(64mm) X H1"(26.5mm). USB cable length:4 inch (100mm). Product weight: 3oz(85g).',
  'Video Conference Lighting,6.3" Selfie Ring Light with Clamp Mount for Video Conferencing,Webcam Light with 3 Light Modes&6 Level Dimmable for Laptop/PC Monitor/Desk/Bed/Office/Makeup/YouTube/TIK Tok',
  "FHH Security Camera 2K Cameras for Home Security with Night Vision, Two-Way Audio,Motion Detection, Phone APP,Remote Contol Indoor WiFi Camera,Ideal for Baby Monitor/Pet Camera2K LIVE STEAM from ANYWHERE: Home security cameras with super clear 2K UHD provide high-quality video right in the palm of your hand. Swipe up, down, left, and right on your phone to rotate and set your baby camera's point of view in real time. CLEAR NIGHT VISION and REMOTE PAN&TILT: The infrared night vision function ensures clear, vivid pictures and stunning surveillance both during the day and at night. The camera can track up to 355° Horizontal & 110° Vertical rotation range to create a complete 360°coverage. SMART MOTION DETECTION & ALARM WITH RECORDING: FHH indoor camera is fitted with an advanced detection algorithm that automatically captures snapshots and videos when it detects movements and immediately sends a real-time notification to your smartphone via FHH App. Features motion sensibility adjustment, accurate and smart motion detection to reduce false alarm. TWO-WAY AUDIO & LOCAL STORAGE: This wifi camera is fitted with microphones and speaker that lets you talk or listen to family member, friends, pets or chase away intruders in a distance. Enjoy storing up to 128GB of SD (NO SD card is INCLUDED). Store and record daily events and keep your home and loved ones safe. Enhanced FHH App :A lot of home security cameras require complex configuration before use, considering customers' needs, our camera is however such amazingly easy to configure. FHH pet cameras with app are basically a three step installation process, install an App, log into your WiFi, and scan a QR code, it really is that simple.(This indoor surveillance camera must be connected with 2.4Ghz WiFi when the first time connect.",
  "ENSTER 2.4/5GHz Dual Band WiFi Camera,24/7 Recording Security Camera Outdoor,Wide Angle Surveillance Camera, 1080P Home Security Camera,Two-Way Audio,4X Zoom,Motion Detection,Waterproof,Night Vision【2.4Ghz AND 5Ghz DUAL BAND】Worried that cameras for home security cannot be used with the wifi at home? This surveillance camera can connect 2.4ghz and 5ghz wifi. Avoid crowded 2.4ghz wifi and quickly access videos. Once connected, you can view the video at any time on the android and ios phone camhi app anywhere. You can choose to install the camera outside with wired connection, such as gate, front door, garden, backyard, garage, corridor, kitchen, living room, etc. 【1080P 110°WIDE ANGLE & LONG RANGE SIGNAL】Wide angle outdoor camera with high resolution images in 1080p at 25 frames per second, combined with a 110° lens and universal ball mount delivers clarity in every direction. A wider angle than equivalent high definition cctv camera. Two 5db paddle antennas, than the others exterior home security camera of 3db circular antenna, more powerful, more stable signal, monitoring picture will be more smooth. 【MOTION DETECTION & TWO WAY AUDIO】 The 5g security camera with motion sensor picks up your kids when they are in the backyard. The app notifies you when there is human movement. After the motion detection is triggered, the SD card will automatically record(support 24/7 recording), push notification to the mobile phone, receive push email and FTP upload. At the same time, you can use two-way audio to talk to your child anywhere. 【IP66 WATERPROOF & 100FT NIGHT VISION】The weatherproof outdoor camera adopts high-quality casing which is sturdy and durable, waterproof and strong enough to withstand severe weather such as typhoon and heavy rain (-10°C~55°C), ensuring excellent performance when used for outdoor monitoring. No matter how dark the night is, you will not let go of everyone's small actions, you can sleep peacefully. Infrared video in 100FT is recorded in SD card. 【24/7 RECORD & WARRANTY】The 5ghz wifi camera outdoor supports 24/7 recording. The video will be saved in the SD card and be viewed directly on the mobile phone. Maximum support 128g memory card, up to 90 days of video. If you have any questions please contact us through your order on Amazon, or send email to us, we will offer solutions to make you satisfied with our 5g security camera! Please rest assured to buy.",
  'Amazon Basics DisplayPort to HDMI Display Cable, Uni-Directional, 4K@60Hz, 1920x1200, 1080p, Gold-Plated Plugs, 6 Foot, BlackIN THE BOX: (1) 6 foot DisplayPort HDMI display cable for transmitting high-def audio and video from DisplayPort enabled computers to HDMI displays SUPPORTS 4K VIDEO: Supports 4K@60Hz for enhanced gaming or streaming video to a home theater, projector, or monitor with 4K high resolution EASY TO CONNECT: Connect and configure monitors for dual screen or mirrored display CRYSTAL CLEAR TRANSMISSION: Gold-plated connectors deliver crystal clear audio and video; durable cable housing for longevity PLUG & PLAY DESIGN: does not require drivers or software UNI-DIRECTIONAL: This is a uni-directional cable that supports DisplayPort to HDMI only; does not support HDMI to DisplayPort (not bi-directional)',
  'Lenovo IdeaPad 3 15 Intel i3-10110U 8GB 256GB SSD 15.6-inch Touch Screen Laptop10th Gen Intel Core i3-10110U Dual-Core Processor 2.1GHz processor 4.1 GHz Turbo / 8GB DDR4 2666 SDRAM / 256GB NVMe Solid State Drive 15.6-inch LED Touch Screen Display (1366 x 768) / Integrated Intel UHD Graphics Dolby Audio with 2 x 1.5W Speakers / 802.11ac Wi-Fi + Bluetooth / Media Card reader / Webcam with Microphone 2 USB 3.0 Ports / 1 USB 2.0 Port / 1 HDMI Out 2 Cell Lithium-polymer Battery / 45W AC Adapter / Windows 10 Home in S mode / Color: Abyss Blue',
  'Samsung Gear 360 Degree Spherical Camera (SM-C200) for Galaxy S7, S7 Edge, S6, S6 Edge, S6 Edge Plus, Note 5 (International Version - No Warranty)Immersive 360 Cam High-Res Video and Photo F2.0 Dual Lenses Clear in Low Light / High Resolution 3840x1920 Video Time-Lapse Video Real 360 Event Logging MicroSD card is required for shooting.',
  'Full HD 1080P Home WiFi Camera, 360 Degree Panoramic Wireless Security IP Camera for Home Baby Pet Monitor Remote Viewing Camera Night Vision Motion Detection Wireless Camera 2.4GHz【360° View Angle &1080P Full HD Cam】Tired of the blind area of traditional dome or bullet camera? this cameras come with FULL HD 1080P resolution.Built in 1.44mm Fish-Eye Lens, this camera will provide you with 360 degree panoramic viewing angle without blind area! You can monitor the whole room (up to 400 square foot) with 1 single camera! 【Motion Detection & Alarm Function】: Alert notification will be pushed to your smartphone when motion is detected by security camera,So you don’t need to worry the thief break into your house when you are outside, which makes your place safer. 【Wireless Connection & Work with iCSee】Panoramic camera only supports 2.4G Wi-Fi (doesn’t support 5G Wi-Fi).Follow the steps of the instruction manual,connect camera to your 2.4G wifi router.You can monitor it via iCSee APP anywhere anytime after connection to router,it is conveniencw and practically for your life. 【Comes with AP Spots】Each panoramic camera owns a unique available hotspot,the available hotspot only can assist you to connect to the 2.4G WiFi router.Even if you are not on wifi environment,you can connect to it easily. 【Please Note Before Use】It can be directly installed normally,just make sure that place in 2.4Ghz wifi range.If you can’t connect, please check if your router’s firewall is turned off and wifi is 2.4GHZ,(As some routers are 5G and 2.4G 2-in-1,it may take longer to connect during the wifi automatic switching process,pls wait patiently), you can also reconnect by resetting the camera.',
  'Monoprice HDMI High Speed Cable - 4 Feet - Black, 4K@60Hz, HDR, 10.2 Gbps, 36AWG, YUV 4:2:0 - Ultra Slim SeriesSupports 4k UHD High Resolution HDTVs Connects HDMI-enabled devices, including PS4, PS3, Xbox, Apple TV, Roku, Blu-Ray players and computers to HDMI-enabled displays, A/V receivers and more Supports Ethernet, 3D, 4K, Audio Return Channel, FHD, Deep Color, HDMI-CEC and HDCP',
  "Bysameyee HD 2MP 2K USB Microscope, 40X to 1000X Magnification Digital Microscope Camera Inspection Endoscope with Carrying Case, Compatible with Windows 7 8 10, Mac, Linux, OTG Android PhonesReal HD 2MP Microscope Camera: 1080P HD 2MP Camera with 8 adjustable LED lights, provide excellent detail and optimal clarity. It is good for any inspection environment and ensures the magnified images are clear and bright. 40X more magnification can meet your daily needs. Capture, Record & Measure: Connected this handheld microscope to devices, you can capture screenshot images by the SNAP button and record a video with installed software/App. Please note that the measurement software only works for WINDOWS users. Where It Can Be Used: This is a digital microscope, not a traditional microscope, Not suitable for professional serious biologists! Perfect for learning and exploration, skin examination, hair examination, plant dissection/examination, textile inspection, jewelry inspection, collections/coin inspection, printing inspection, PCB or PCBA inspection, and so on. Broad Compatibility: Support Windows 7 8 10, Mac OS and OS X, Linux, Chrome OS, and Smart Android phones (with OTG function). Select Android devices may not work, and it's up to the device manufacturer to support external cameras. Easy to Use & Carry: Install the software, plug it into your device, now you can explore the microscopic world with this microscope camera. Univeral bracket, 2 OTG adapters, ruler, driver & carrying case are provided for multi-purpose application. The portable carrying bag is really a bonus for outdoor use.",
  'Monoprice HDMI High Speed Cable - 1 Feet - Black, 4K@60Hz, HDR, 18Gbps, 36AWG, YUV 4:4:4 - Ultra Slim SeriesSupports 4k UHD High Resolution HDTVs Ultra Slim 36AWG cable Connects HDMI-enabled devices, including PS4, PS3, Xbox, Apple TV, Roku, Blu-Ray players and computers to HDMI-enabled displays, A/V receivers and more Supports Ethernet, 3D, 4K, Audio Return Channel, FHD, Deep Color, HDMI-CEC and HDCP Lifetime Warranty on All Cables',
  'Sony 75 Inch 4K Ultra HD TV X85K Series: LED Smart Google TV with Dolby Vision HDR and Native 120HZ Refresh Rate KD75X85K- Latest ModelINTELLIGENT TV PROCESSING– The 4K HDR Processor X1 delivers a picture that is smooth and clear, full of rich colors and detailed contrast. INTELLIGENT MOTION HANDLING – See blur-free picture quality in fast-moving sports and action-packed movies with native 120Hz refresh rate and Motionflow XR technology. WIDE SPECTRUM OF COLORS- Reproduces over a billion accurate colors resulting in picture quality that is natural and precise, and closer than ever to real life, enhanced by TRILUMINOS Pro. PREMIUM SMART TV– Google TV with Google Assistant organizes your favorite content all in one place. Stream from Prime Video, Netflix, Disney+, Apple TV, HBO Max, Peacock and many more. Also, stream from your Apple device with AirPlay 2 support. ENHANCED ENTERTAINMENT– Experience immersive and engaging cinematic content as the creator intended with support for Dolby Vision & Atmos. WORKS WITH ALEXA – Through an Alexa enabled device, ask Alexa to change channels, adjust volume, and turn your TV on/off. ENHANCED GAMING PICTURE QUALITY– Enhance your gaming experience with exclusive features for the PlayStation 5 to improve gaming picture quality. FEATURES SPECIFIED IN HDMI 2.1 – Get the advantage in high-performance gaming with HDMI 2.1 features such as 4K/120,4 VRR, and ALLM. UPSCALE ALL YOUR CONTENT– Bring back lost texture and detail and see all your content upscaled to near-4K resolution with 4K XR-Reality PRO. FLUSH SURFACE DESIGN– Your eyes naturally focus on the immersive big picture with a flush surface narrow bezel design',

### Hybrid Search with weighted RRF

In [43]:
def retrieve_context_weighted(query, k=5):
    query_embedding = get_embedding(query)

    results = qdrant_client.query_points(
        collection_name=collection_name, 
        prefetch = [
            Prefetch(query = query_embedding, using = "text-embedding-3-small", limit = 20),
            Prefetch(query = Document(text=query, model = "qdrant/bm25"), using = "bm25", limit = 20)
        ],
        query=models.RrfQuery(rrf = models.Rrf(weights=[3,1])),
        limit=k)

    context_ids = []
    context = []
    scores = []
    ratings = []

    print(results)
    for pt in results.points:
        context_ids.append(pt.payload['parent_asin'])
        context.append(pt.payload['preprocessed_description'])
        scores.append(pt.score)
        ratings.append(pt.payload['average_rating'])
        
    return {
        'retrieved_context_ids': context_ids,
        'retrieved_context': context,
        'similarity_scores': scores,
        'retrieved_context_ratings': ratings
    }

In [46]:
results = retrieve_context_weighted("do you have any 4k webcams ?", k = 20)

points=[ScoredPoint(id=826, version=4, score=1.0, payload={'preprocessed_description': 'DEPSTECH Webcam with Microphone, 2K HD Web Camera with Auto Light Correction, Plug and Play USB Webcam and 90° View Angle for Desktop/Streaming/Video Calling Recording/Meeting/Online Teaching【2K QHD Webcam】The HD camera with a 1/2.9”CMOS image sensor delivers sharp and crystal clear video up to a 2560 x 1440 resolution video at a fluid 30 FPS, specially suitable for professional live streaming or recording like detailed makeup tutorials or other online teaching. 【Webcam with Microphone】This web camera built-in microphone with automatic noise reduction make the recording sound clearer, more natural under some noise environments, providing better sound recognition and smooth transmission. 【Smooth Live Streaming Webcam】With automatic low light correction tech, the USB camera captures excellent 2K QHD video at a widescreen angle of up to 90 degrees, even in dimly environment. It also support faster data transfer via USB 3.0/2.0 interface and ensure a smooth live streaming. 【Easy to Operate & Wide Compatible】No additional driver or software required, just connect the PC webcam to a computer USB port and start play. Compatible with most software and operating systems including Windows XP and Mac OS, Smart TV. 【Adjustable Position】The webcam for desktop supports 360°horizontal rotation, 180 degree adjustment in vertical direction and even support installation on tripod or pan tilt head, easy to adjust for suitable record position. To protect the privacy, you can turn the camera to a safe direction when it is not in use.', 'image': 'https://m.media-amazon.com/images/I/31msF7N7bWL._AC_.jpg', 'rating_number': 520, 'price': None, 'average_rating': 3.9, 'parent_asin': 'B08CMV4GF6'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=993, version=4, score=0.875, payload={'preprocessed_description': "Acetaken Webcam Mount - Flexible Gooseneck Arm Clamp Stand Tripod for Logitech Webcam C920s C920 C930e C922x C930 C922 C925e C615 Brio - 25 inchesWebcam Mount head: Ball-Head adapter with 1/4'' Screw Thread to Connect Your webcam's 1/4'' Screw Hole; Webcam Gooseneck: Extend to the max approx.64cm / 25 inches, Easy to Adjust any angle as your request; Webcam Mount Compatible for Logitech Webcam C920s C920 C925e C922x C922 C930e C930 C615, Brio 4K; Webcam Clamp fit the Desk,Table,Sideboard,Bed Max thickness 5.5cm(2 inches); Better work than webcam Tripod; Webcam Arm max Load 1.5 LBS (0.7kg); Not for heavy Camera and devices; (Webcam NOT included Packing)", 'image': 'https://m.media-amazon.com/images/I/31nFW8uQ3iL._AC_.jpg', 'rating_number': 207, 'price': 19.99, 'average_rating': 4.4, 'parent_asin': 'B082HQJ1JX'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=724, version=4, score=0.72499996, payload={'preprocessed_description': 'Webcam 1080P Full HD Auto Focus Web Camera with Microphone Widescreen USB Computer Camera for PC Laptop Desktop Mac Streaming Video Calling Recording Video Conference Online Teaching Business GamingBuilt-in digital stereo MIC with automatic noise reduction and echo-canceling technology makes the sound purer, clearer and more natural. It can pick up your voice even at 10ft distance. Everyone hears the real you. 5 Million pixels auto focus: Getting rid of tedious focusing process. Our web camera is with 1080P high-definition camera and true color images. Plug And Play: USB 2.0 connector, no need to download or install complicated driver software. It means you needn’t set up any specific driver or software. Our Webcam can plug and play, easy and convenient. Fits for multiple operations including Windows 2000/XP/7/8/10 and above, Mac OS, Android 5.0 or higher version. Works when you need HD video,clear and smooth video conference and video meeting. Works with many video conferencing software applications such as Zoom, Google Meet, Skype For Business, Microsoft Teams and WebEx. Free return for refund or replacement if you are not satisfied with our products. If there are any questions, please feel free to contact us. We are always here to serve you. Also, welcome to share your opinions, we may take your advice to the next design.', 'image': 'https://m.media-amazon.com/images/I/415FK9xNRTL._AC_.jpg', 'rating_number': 310, 'price': None, 'average_rating': 4.1, 'parent_asin': 'B087986YPY'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=584, version=4, score=0.7, payload={'preprocessed_description': 'HD 1080P Webcam with Microphone, USB(2.0/3.0) Computer Camera for Live Streaming Webcam,110 Degrees Wide-Angle 30fps for Laptop, Noise Reduction Desktop, Conferencing, Video ChattingReads Smart Cards and Military Common Access Cards (CAC) Compatible with Microsoft Windows XP/Vista/7/10 Not recommended for Mac OS 10.7 and newer USB Connection', 'image': 'https://m.media-amazon.com/images/I/4199jghCXoL._AC_.jpg', 'rating_number': 321, 'price': None, 'average_rating': 4.4, 'parent_asin': 'B002XJG71M'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=976, version=4, score=0.6666667, payload={'preprocessed_description': 'Webcam Cover, Camera Cover Slide, Privacy Covers, 0.02-Inch Ultra-Thin Webcam Cover for Laptop, PC, Phone, Protect Your Privacy and Security (Leopard Texture -3 Pack)[Full Pattern] Different from other classical Black webcam covers, our unique full pattern can decorate your laptop/iPad, making your device look different. [Guard Your Privacy] Our Webcam Cover Slide efficiently protects your privacy and prevents unwanted hacking attacks. It also protects your webcam from dirt and dust. [Fits For Most Devices] Compatible with MacBook Pro, MacBook Air, Mac, laptops, Microsoft Surface, iPad, Android tablet, PC, computer, all-in-one desktop, iPhone and other Android smart phone. It does not interfere with webcam usage or web signal and will not damage your device in any way. [Easy To Use] Simply align to your webcam, attach and press firmly for 15 seconds for a strong. And if you want to change other webcam covers, the adhesive can be easily applied and removed from the device without leaving any traces. [What You Get] 3 X Leopard texture Webcam Cover, 1 X installation guide, and our worry-free 18 Month and friendly customer service. If the product has any question, please contact us we will try our best to help you.', 'image': 'https://m.media-amazon.com/images/I/51qkPf4KD5L._AC_.jpg', 'rating_number': 269, 'price': 6.99, 'average_rating': 4.2, 'parent_asin': 'B08R9GPKRH'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=238, version=3, score=0.5952381, payload={'preprocessed_description': 'ELECOM Facial Recognition Webcam, Windows Hello Full HD 1080P 30FPS, Streaming, Compatible with Windows 11, Windows 10, Easy Login for Desktop & Laptop (UCAM-CF20FBBK)📷《FACIAL RECOGNITION: WINDOWS 11 10 HELLO FACE》 Compatible with Windows 11 10 Hello Face, which enables you to log into Windows 11 10 just by turning your face to the camera, easy, speedy login without typing password. 📷《FULL HD 1080P USB WEBCAM》 80° wide angle lens captures high definition image and video at Full HD 1080P. Perfect for streaming on social media live such as Twitch, YouTube, Xbox one, Streamlabs OBS, Xsplit, Mixer, Facebook and Vloging. The camera weight is only 3oz, easy to carry with you anywhere. 📷《PLUG & PLAY; NO DRIVERS REQUIRED》 This is a plug & play webcam camera, it is easy to be used by just plugging it with the USB 2.0 cable to the computer, then it can display excellent video in time, no need to install any driver to make this webcam work. Perfect for streaming on social media and gaming. 📷《BUILT-IN HIGH QUALITY MICROPHONE & NOISE REDUCTION》 The built-in microphone offers a super clear communication, available to capture audio. The microphone is designed with echo and noise reduction technology, which allows the communication to be clear enough, just like you are talking to someone face to face. Great for Zoom / Facetime / Video Calling / OBS / Twitch / Facebook/ YouTube/ Xbox one/ Conferencing / Gaming / Streaming / Recording / Online School. 📷《PRODUCT DETAILS》 Features up to a 1080P resolution (up to 1920 x 1080 pixels) at 30 fps. Effective pixel count: Approx. 2.0 megapixels. Works with USB 2.0, NO additional drivers required. View angle is 80° wide. Supports Windows 11 10. Product size: H3.9"(100mm) X W2.5"(64mm) X H1"(26.5mm). USB cable length:4 inch (100mm). Product weight: 3oz(85g).', 'image': 'https://m.media-amazon.com/images/I/31c-s1NyYTL._AC_.jpg', 'rating_number': 464, 'price': 45.99, 'average_rating': 4.2, 'parent_asin': 'B0B7QT2KXY'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=479, version=3, score=0.30000004, payload={'preprocessed_description': "FHH Security Camera 2K Cameras for Home Security with Night Vision, Two-Way Audio,Motion Detection, Phone APP,Remote Contol Indoor WiFi Camera,Ideal for Baby Monitor/Pet Camera2K LIVE STEAM from ANYWHERE: Home security cameras with super clear 2K UHD provide high-quality video right in the palm of your hand. Swipe up, down, left, and right on your phone to rotate and set your baby camera's point of view in real time. CLEAR NIGHT VISION and REMOTE PAN&TILT: The infrared night vision function ensures clear, vivid pictures and stunning surveillance both during the day and at night. The camera can track up to 355° Horizontal & 110° Vertical rotation range to create a complete 360°coverage. SMART MOTION DETECTION & ALARM WITH RECORDING: FHH indoor camera is fitted with an advanced detection algorithm that automatically captures snapshots and videos when it detects movements and immediately sends a real-time notification to your smartphone via FHH App. Features motion sensibility adjustment, accurate and smart motion detection to reduce false alarm. TWO-WAY AUDIO & LOCAL STORAGE: This wifi camera is fitted with microphones and speaker that lets you talk or listen to family member, friends, pets or chase away intruders in a distance. Enjoy storing up to 128GB of SD (NO SD card is INCLUDED). Store and record daily events and keep your home and loved ones safe. Enhanced FHH App :A lot of home security cameras require complex configuration before use, considering customers' needs, our camera is however such amazingly easy to configure. FHH pet cameras with app are basically a three step installation process, install an App, log into your WiFi, and scan a QR code, it really is that simple.(This indoor surveillance camera must be connected with 2.4Ghz WiFi when the first time connect.", 'image': 'https://m.media-amazon.com/images/I/41jhvH52fkL._AC_.jpg', 'rating_number': 1163, 'price': None, 'average_rating': 3.8, 'parent_asin': 'B09YRZ8VDV'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=214, version=3, score=0.27272725, payload={'preprocessed_description': "ENSTER 2.4/5GHz Dual Band WiFi Camera,24/7 Recording Security Camera Outdoor,Wide Angle Surveillance Camera, 1080P Home Security Camera,Two-Way Audio,4X Zoom,Motion Detection,Waterproof,Night Vision【2.4Ghz AND 5Ghz DUAL BAND】Worried that cameras for home security cannot be used with the wifi at home? This surveillance camera can connect 2.4ghz and 5ghz wifi. Avoid crowded 2.4ghz wifi and quickly access videos. Once connected, you can view the video at any time on the android and ios phone camhi app anywhere. You can choose to install the camera outside with wired connection, such as gate, front door, garden, backyard, garage, corridor, kitchen, living room, etc. 【1080P 110°WIDE ANGLE & LONG RANGE SIGNAL】Wide angle outdoor camera with high resolution images in 1080p at 25 frames per second, combined with a 110° lens and universal ball mount delivers clarity in every direction. A wider angle than equivalent high definition cctv camera. Two 5db paddle antennas, than the others exterior home security camera of 3db circular antenna, more powerful, more stable signal, monitoring picture will be more smooth. 【MOTION DETECTION & TWO WAY AUDIO】 The 5g security camera with motion sensor picks up your kids when they are in the backyard. The app notifies you when there is human movement. After the motion detection is triggered, the SD card will automatically record(support 24/7 recording), push notification to the mobile phone, receive push email and FTP upload. At the same time, you can use two-way audio to talk to your child anywhere. 【IP66 WATERPROOF & 100FT NIGHT VISION】The weatherproof outdoor camera adopts high-quality casing which is sturdy and durable, waterproof and strong enough to withstand severe weather such as typhoon and heavy rain (-10°C~55°C), ensuring excellent performance when used for outdoor monitoring. No matter how dark the night is, you will not let go of everyone's small actions, you can sleep peacefully. Infrared video in 100FT is recorded in SD card. 【24/7 RECORD & WARRANTY】The 5ghz wifi camera outdoor supports 24/7 recording. The video will be saved in the SD card and be viewed directly on the mobile phone. Maximum support 128g memory card, up to 90 days of video. If you have any questions please contact us through your order on Amazon, or send email to us, we will offer solutions to make you satisfied with our 5g security camera! Please rest assured to buy.", 'image': 'https://m.media-amazon.com/images/I/31e2+uRndyL._AC_.jpg', 'rating_number': 544, 'price': None, 'average_rating': 3.8, 'parent_asin': 'B07SFFT6TQ'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=759, version=4, score=0.25, payload={'preprocessed_description': 'Samsung Gear 360 Degree Spherical Camera (SM-C200) for Galaxy S7, S7 Edge, S6, S6 Edge, S6 Edge Plus, Note 5 (International Version - No Warranty)Immersive 360 Cam High-Res Video and Photo F2.0 Dual Lenses Clear in Low Light / High Resolution 3840x1920 Video Time-Lapse Video Real 360 Event Logging MicroSD card is required for shooting.', 'image': 'https://m.media-amazon.com/images/I/31LF9wcJrgL._AC_.jpg', 'rating_number': 338, 'price': None, 'average_rating': 3.9, 'parent_asin': 'B01M4J53CO'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=190, version=3, score=0.23076925, payload={'preprocessed_description': 'Full HD 1080P Home WiFi Camera, 360 Degree Panoramic Wireless Security IP Camera for Home Baby Pet Monitor Remote Viewing Camera Night Vision Motion Detection Wireless Camera 2.4GHz【360° View Angle &1080P Full HD Cam】Tired of the blind area of traditional dome or bullet camera? this cameras come with FULL HD 1080P resolution.Built in 1.44mm Fish-Eye Lens, this camera will provide you with 360 degree panoramic viewing angle without blind area! You can monitor the whole room (up to 400 square foot) with 1 single camera! 【Motion Detection & Alarm Function】: Alert notification will be pushed to your smartphone when motion is detected by security camera,So you don’t need to worry the thief break into your house when you are outside, which makes your place safer. 【Wireless Connection & Work with iCSee】Panoramic camera only supports 2.4G Wi-Fi (doesn’t support 5G Wi-Fi).Follow the steps of the instruction manual,connect camera to your 2.4G wifi router.You can monitor it via iCSee APP anywhere anytime after connection to router,it is conveniencw and practically for your life. 【Comes with AP Spots】Each panoramic camera owns a unique available hotspot,the available hotspot only can assist you to connect to the 2.4G WiFi router.Even if you are not on wifi environment,you can connect to it easily. 【Please Note Before Use】It can be directly installed normally,just make sure that place in 2.4Ghz wifi range.If you can’t connect, please check if your router’s firewall is turned off and wifi is 2.4GHZ,(As some routers are 5G and 2.4G 2-in-1,it may take longer to connect during the wifi automatic switching process,pls wait patiently), you can also reconnect by resetting the camera.', 'image': 'https://m.media-amazon.com/images/I/31PrOgEi9-L._AC_.jpg', 'rating_number': 1687, 'price': None, 'average_rating': 3.3, 'parent_asin': 'B07M9Q2PL4'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=691, version=4, score=0.2142857, payload={'preprocessed_description': "Bysameyee HD 2MP 2K USB Microscope, 40X to 1000X Magnification Digital Microscope Camera Inspection Endoscope with Carrying Case, Compatible with Windows 7 8 10, Mac, Linux, OTG Android PhonesReal HD 2MP Microscope Camera: 1080P HD 2MP Camera with 8 adjustable LED lights, provide excellent detail and optimal clarity. It is good for any inspection environment and ensures the magnified images are clear and bright. 40X more magnification can meet your daily needs. Capture, Record & Measure: Connected this handheld microscope to devices, you can capture screenshot images by the SNAP button and record a video with installed software/App. Please note that the measurement software only works for WINDOWS users. Where It Can Be Used: This is a digital microscope, not a traditional microscope, Not suitable for professional serious biologists! Perfect for learning and exploration, skin examination, hair examination, plant dissection/examination, textile inspection, jewelry inspection, collections/coin inspection, printing inspection, PCB or PCBA inspection, and so on. Broad Compatibility: Support Windows 7 8 10, Mac OS and OS X, Linux, Chrome OS, and Smart Android phones (with OTG function). Select Android devices may not work, and it's up to the device manufacturer to support external cameras. Easy to Use & Carry: Install the software, plug it into your device, now you can explore the microscopic world with this microscope camera. Univeral bracket, 2 OTG adapters, ruler, driver & carrying case are provided for multi-purpose application. The portable carrying bag is really a bonus for outdoor use.", 'image': 'https://m.media-amazon.com/images/I/511wF9+W8cL._AC_.jpg', 'rating_number': 249, 'price': 27.99, 'average_rating': 3.9, 'parent_asin': 'B08XXQCBSZ'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=728, version=4, score=0.2, payload={'preprocessed_description': 'Wireless Light Bulb Camera, 360°Panoramic Security Camera, 2.4GHz WiFi Smart 1080P Outdoor Surveillance Camera with Night Vision Motion Detection Alarm Two-Way-Talk Phone Remote View Indoor E27【1080P FULL HD & CLEAR NIGHT VISION】1080P Full HD security camera provides clear smooth live video and recordings. It also has clear night vision ,You can view clear images even in complete darkness. 【MOTION DETECTION & REAL-TIME ALERTS】 Build-in highly sensitive motion sensor detect moving object,moving picture will be save at the same time.If someone breaks into your home,The camera will follow him , sound an alarm and switch strong white light to scare away invading characters. 【360 Degree Viewing】 Automatically sense 360-degree pan/tilt panorama tracking indoors and outdoors, horizontal rotation 360 ° and vertical rotation 180 °, no need to worry about the blind area, protect family and personal property safety. Take care of elderly parents, children, pets.', 'image': 'https://m.media-amazon.com/images/I/31pk8kEzeFL._AC_.jpg', 'rating_number': 262, 'price': None, 'average_rating': 3.1, 'parent_asin': 'B0B7BHY16V'}, vector=None, shard_key=None, order_value=None), ScoredPoint(id=486, version=3, score=0.1875, payload={'preprocessed_description': 'SYMYNELEC Light Bulb Camera WiFi Outdoor, Wireless PTZ Security IP Camera, 2K Super FHD Smart Home Surveillance Cam with Human Motion Detection Alarm Night Vision Two Way Talk (2.4GHz Only)💡【Fast Installation & Setup】- As easy as replacing a light bulb to install the light bulb camera, and set up via your smart phone within 3 minutes. No drill, no wiring, no power cable. Simple to control, and a breeze to maintain. Compatible with 2.4GHz WiFI network. 5GHz NOT SUPPORTED. Download "Tuya Smart" app from App Store or Google Play. The maximum WiFi signal reception range of the bulb camera is 12 meters. Please install it

In [47]:
results

{'retrieved_context_ids': ['B08CMV4GF6',
  'B082HQJ1JX',
  'B087986YPY',
  'B002XJG71M',
  'B08R9GPKRH',
  'B0B7QT2KXY',
  'B09YRZ8VDV',
  'B07SFFT6TQ',
  'B01M4J53CO',
  'B07M9Q2PL4',
  'B08XXQCBSZ',
  'B0B7BHY16V',
  'B0B4Z7V3XG',
  'B00PC73NQY',
  'B00HGJQUVG',
  'B016F3M7OM',
  'B07QS5NCB3',
  'B08PYY2TCC',
  'B01FFQEP6I',
  'B08N44NZT3'],
 'retrieved_context': ['DEPSTECH Webcam with Microphone, 2K HD Web Camera with Auto Light Correction, Plug and Play USB Webcam and 90° View Angle for Desktop/Streaming/Video Calling Recording/Meeting/Online Teaching【2K QHD Webcam】The HD camera with a 1/2.9”CMOS image sensor delivers sharp and crystal clear video up to a 2560 x 1440 resolution video at a fluid 30 FPS, specially suitable for professional live streaming or recording like detailed makeup tutorials or other online teaching. 【Webcam with Microphone】This web camera built-in microphone with automatic noise reduction make the recording sound clearer, more natural under some noise environments, providing better sound recognition and smooth transmission. 【Smooth Live Streaming Webcam】With automatic low light correction tech, the USB camera captures excellent 2K QHD video at a widescreen angle of up to 90 degrees, even in dimly environment. It also support faster data transfer via USB 3.0/2.0 interface and ensure a smooth live streaming. 【Easy to Operate & Wide Compatible】No additional driver or software required, just connect the PC webcam to a computer USB port and start play. Compatible with most software and operating systems including Windows XP and Mac OS, Smart TV. 【Adjustable Position】The webcam for desktop supports 360°horizontal rotation, 180 degree adjustment in vertical direction and even support installation on tripod or pan tilt head, easy to adjust for suitable record position. To protect the privacy, you can turn the camera to a safe direction when it is not in use.',
  "Acetaken Webcam Mount - Flexible Gooseneck Arm Clamp Stand Tripod for Logitech Webcam C920s C920 C930e C922x C930 C922 C925e C615 Brio - 25 inchesWebcam Mount head: Ball-Head adapter with 1/4'' Screw Thread to Connect Your webcam's 1/4'' Screw Hole; Webcam Gooseneck: Extend to the max approx.64cm / 25 inches, Easy to Adjust any angle as your request; Webcam Mount Compatible for Logitech Webcam C920s C920 C925e C922x C922 C930e C930 C615, Brio 4K; Webcam Clamp fit the Desk,Table,Sideboard,Bed Max thickness 5.5cm(2 inches); Better work than webcam Tripod; Webcam Arm max Load 1.5 LBS (0.7kg); Not for heavy Camera and devices; (Webcam NOT included Packing)",
  'Webcam 1080P Full HD Auto Focus Web Camera with Microphone Widescreen USB Computer Camera for PC Laptop Desktop Mac Streaming Video Calling Recording Video Conference Online Teaching Business GamingBuilt-in digital stereo MIC with automatic noise reduction and echo-canceling technology makes the sound purer, clearer and more natural. It can pick up your voice even at 10ft distance. Everyone hears the real you. 5 Million pixels auto focus: Getting rid of tedious focusing process. Our web camera is with 1080P high-definition camera and true color images. Plug And Play: USB 2.0 connector, no need to download or install complicated driver software. It means you needn’t set up any specific driver or software. Our Webcam can plug and play, easy and convenient. Fits for multiple operations including Windows 2000/XP/7/8/10 and above, Mac OS, Android 5.0 or higher version. Works when you need HD video,clear and smooth video conference and video meeting. Works with many video conferencing software applications such as Zoom, Google Meet, Skype For Business, Microsoft Teams and WebEx. Free return for refund or replacement if you are not satisfied with our products. If there are any questions, please feel free to contact us. We are always here to serve you. Also, welcome to share your opinions, we may take your advice to the next design.',
  'HD 1080P Webcam with Microphone, USB(2.0/3.0) Computer Camera for Live Streaming Webcam,110 Degrees Wide-Angle 30fps for Laptop, Noise Reduction Desktop, Conferencing, Video ChattingReads Smart Cards and Military Common Access Cards (CAC) Compatible with Microsoft Windows XP/Vista/7/10 Not recommended for Mac OS 10.7 and newer USB Connection',
  'Webcam Cover, Camera Cover Slide, Privacy Covers, 0.02-Inch Ultra-Thin Webcam Cover for Laptop, PC, Phone, Protect Your Privacy and Security (Leopard Texture -3 Pack)[Full Pattern] Different from other classical Black webcam covers, our unique full pattern can decorate your laptop/iPad, making your device look different. [Guard Your Privacy] Our Webcam Cover Slide efficiently protects your privacy and prevents unwanted hacking attacks. It also protects your webcam from dirt and dust. [Fits For Most Devices] Compatible with MacBook Pro, MacBook Air, Mac, laptops, Microsoft Surface, iPad, Android tablet, PC, computer, all-in-one desktop, iPhone and other Android smart phone. It does not interfere with webcam usage or web signal and will not damage your device in any way. [Easy To Use] Simply align to your webcam, attach and press firmly for 15 seconds for a strong. And if you want to change other webcam covers, the adhesive can be easily applied and removed from the device without leaving any traces. [What You Get] 3 X Leopard texture Webcam Cover, 1 X installation guide, and our worry-free 18 Month and friendly customer service. If the product has any question, please contact us we will try our best to help you.',
  'ELECOM Facial Recognition Webcam, Windows Hello Full HD 1080P 30FPS, Streaming, Compatible with Windows 11, Windows 10, Easy Login for Desktop & Laptop (UCAM-CF20FBBK)📷《FACIAL RECOGNITION: WINDOWS 11 10 HELLO FACE》 Compatible with Windows 11 10 Hello Face, which enables you to log into Windows 11 10 just by turning your face to the camera, easy, speedy login without typing password. 📷《FULL HD 1080P USB WEBCAM》 80° wide angle lens captures high definition image and video at Full HD 1080P. Perfect for streaming on social media live such as Twitch, YouTube, Xbox one, Streamlabs OBS, Xsplit, Mixer, Facebook and Vloging. The camera weight is only 3oz, easy to carry with you anywhere. 📷《PLUG & PLAY; NO DRIVERS REQUIRED》 This is a plug & play webcam camera, it is easy to be used by just plugging it with the USB 2.0 cable to the computer, then it can display excellent video in time, no need to install any driver to make this webcam work. Perfect for streaming on social media and gaming. 📷《BUILT-IN HIGH QUALITY MICROPHONE & NOISE REDUCTION》 The built-in microphone offers a super clear communication, available to capture audio. The microphone is designed with echo and noise reduction technology, which allows the communication to be clear enough, just like you are talking to someone face to face. Great for Zoom / Facetime / Video Calling / OBS / Twitch / Facebook/ YouTube/ Xbox one/ Conferencing / Gaming / Streaming / Recording / Online School. 📷《PRODUCT DETAILS》 Features up to a 1080P resolution (up to 1920 x 1080 pixels) at 30 fps. Effective pixel count: Approx. 2.0 megapixels. Works with USB 2.0, NO additional drivers required. View angle is 80° wide. Supports Windows 11 10. Product size: H3.9"(100mm) X W2.5"(64mm) X H1"(26.5mm). USB cable length:4 inch (100mm). Product weight: 3oz(85g).',
  "FHH Security Camera 2K Cameras for Home Security with Night Vision, Two-Way Audio,Motion Detection, Phone APP,Remote Contol Indoor WiFi Camera,Ideal for Baby Monitor/Pet Camera2K LIVE STEAM from ANYWHERE: Home security cameras with super clear 2K UHD provide high-quality video right in the palm of your hand. Swipe up, down, left, and right on your phone to rotate and set your baby camera's point of view in real time. CLEAR NIGHT VISION and REMOTE PAN&TILT: The infrared night vision function ensures clear, vivid pictures and stunning surveillance both during the day and at night. The camera can track up to 355° Horizontal & 110° Vertical rotation range to create a complete 360°coverage. SMART MOTION DETECTION & ALARM WITH RECORDING: FHH indoor camera is fitted with an advanced detection algorithm that automatically captures snapshots and videos when it detects movements and immediately sends a real-time notification to your smartphone via FHH App. Features motion sensibility adjustment, accurate and smart motion detection to reduce false alarm. TWO-WAY AUDIO & LOCAL STORAGE: This wifi camera is fitted with microphones and speaker that lets you talk or listen to family member, friends, pets or chase away intruders in a distance. Enjoy storing up to 128GB of SD (NO SD card is INCLUDED). Store and record daily events and keep your home and loved ones safe. Enhanced FHH App :A lot of home security cameras require complex configuration before use, considering customers' needs, our camera is however such amazingly easy to configure. FHH pet cameras with app are basically a three step installation process, install an App, log into your WiFi, and scan a QR code, it really is that simple.(This indoor surveillance camera must be connected with 2.4Ghz WiFi when the first time connect.",
  "ENSTER 2.4/5GHz Dual Band WiFi Camera,24/7 Recording Security Camera Outdoor,Wide Angle Surveillance Camera, 1080P Home Security Camera,Two-Way Audio,4X Zoom,Motion Detection,Waterproof,Night Vision【2.4Ghz AND 5Ghz DUAL BAND】Worried that cameras for home security cannot be used with the wifi at home? This surveillance camera can connect 2.4ghz and 5ghz wifi. Avoid crowded 2.4ghz wifi and quickly access videos. Once connected, you can view the video at any time on the android and ios phone camhi app anywhere. You can choose to install the camera outside with wired connection, such as gate, front door, garden, backyard, garage, corridor, kitchen, living room, etc. 【1080P 110°WIDE ANGLE & LONG RANGE SIGNAL】Wide angle outdoor camera with high resolution images in 1080p at 25 frames per second, combined with a 110° lens and universal ball mount delivers clarity in every direction. A wider angle than equivalent high definition cctv camera. Two 5db paddle antennas, than the others exterior home security camera of 3db circular antenna, more powerful, more stable signal, monitoring picture will be more smooth. 【MOTION DETECTION & TWO WAY AUDIO】 The 5g security camera with motion sensor picks up your kids when they are in the backyard. The app notifies you when there is human movement. After the motion detection is triggered, the SD card will automatically record(support 24/7 recording), push notification to the mobile phone, receive push email and FTP upload. At the same time, you can use two-way audio to talk to your child anywhere. 【IP66 WATERPROOF & 100FT NIGHT VISION】The weatherproof outdoor camera adopts high-quality casing which is sturdy and durable, waterproof and strong enough to withstand severe weather such as typhoon and heavy rain (-10°C~55°C), ensuring excellent performance when used for outdoor monitoring. No matter how dark the night is, you will not let go of everyone's small actions, you can sleep peacefully. Infrared video in 100FT is recorded in SD card. 【24/7 RECORD & WARRANTY】The 5ghz wifi camera outdoor supports 24/7 recording. The video will be saved in the SD card and be viewed directly on the mobile phone. Maximum support 128g memory card, up to 90 days of video. If you have any questions please contact us through your order on Amazon, or send email to us, we will offer solutions to make you satisfied with our 5g security camera! Please rest assured to buy.",
  'Samsung Gear 360 Degree Spherical Camera (SM-C200) for Galaxy S7, S7 Edge, S6, S6 Edge, S6 Edge Plus, Note 5 (International Version - No Warranty)Immersive 360 Cam High-Res Video and Photo F2.0 Dual Lenses Clear in Low Light / High Resolution 3840x1920 Video Time-Lapse Video Real 360 Event Logging MicroSD card is required for shooting.',
  'Full HD 1080P Home WiFi Camera, 360 Degree Panoramic Wireless Security IP Camera for Home Baby Pet Monitor Remote Viewing Camera Night Vision Motion Detection Wireless Camera 2.4GHz【360° View Angle &1080P Full HD Cam】Tired of the blind area of traditional dome or bullet camera? this cameras come with FULL HD 1080P resolution.Built in 1.44mm Fish-Eye Lens, this camera will provide you with 360 degree panoramic viewing angle without blind area! You can monitor the whole room (up to 400 square foot) with 1 single camera! 【Motion Detection & Alarm Function】: Alert notification will be pushed to your smartphone when motion is detected by security camera,So you don’t need to worry the thief break into your house when you are outside, which makes your place safer. 【Wireless Connection & Work with iCSee】Panoramic camera only supports 2.4G Wi-Fi (doesn’t support 5G Wi-Fi).Follow the steps of the instruction manual,connect camera to your 2.4G wifi router.You can monitor it via iCSee APP anywhere anytime after connection to router,it is conveniencw and practically for your life. 【Comes with AP Spots】Each panoramic camera owns a unique available hotspot,the available hotspot only can assist you to connect to the 2.4G WiFi router.Even if you are not on wifi environment,you can connect to it easily. 【Please Note Before Use】It can be directly installed normally,just make sure that place in 2.4Ghz wifi range.If you can’t connect, please check if your router’s firewall is turned off and wifi is 2.4GHZ,(As some routers are 5G and 2.4G 2-in-1,it may take longer to connect during the wifi automatic switching process,pls wait patiently), you can also reconnect by resetting the camera.',
  "Bysameyee HD 2MP 2K USB Microscope, 40X to 1000X Magnification Digital Microscope Camera Inspection Endoscope with Carrying Case, Compatible with Windows 7 8 10, Mac, Linux, OTG Android PhonesReal HD 2MP Microscope Camera: 1080P HD 2MP Camera with 8 adjustable LED lights, provide excellent detail and optimal clarity. It is good for any inspection environment and ensures the magnified images are clear and bright. 40X more magnification can meet your daily needs. Capture, Record & Measure: Connected this handheld microscope to devices, you can capture screenshot images by the SNAP button and record a video with installed software/App. Please note that the measurement software only works for WINDOWS users. Where It Can Be Used: This is a digital microscope, not a traditional microscope, Not suitable for professional serious biologists! Perfect for learning and exploration, skin examination, hair examination, plant dissection/examination, textile inspection, jewelry inspection, collections/coin inspection, printing inspection, PCB or PCBA inspection, and so on. Broad Compatibility: Support Windows 7 8 10, Mac OS and OS X, Linux, Chrome OS, and Smart Android phones (with OTG function). Select Android devices may not work, and it's up to the device manufacturer to support external cameras. Easy to Use & Carry: Install the software, plug it into your device, now you can explore the microscopic world with this microscope camera. Univeral bracket, 2 OTG adapters, ruler, driver & carrying case are provided for multi-purpose application. The portable carrying bag is really a bonus for outdoor use.",
  'Wireless Light Bulb Camera, 360°Panoramic Security Camera, 2.4GHz WiFi Smart 1080P Outdoor Surveillance Camera with Night Vision Motion Detection Alarm Two-Way-Talk Phone Remote View Indoor E27【1080P FULL HD & CLEAR NIGHT VISION】1080P Full HD security camera provides clear smooth live video and recordings. It also has clear night vision ,You can view clear images even in complete darkness. 【MOTION DETECTION & REAL-TIME ALERTS】 Build-in highly sensitive motion sensor detect moving object,moving picture will be save at the same time.If someone breaks into your home,The camera will follow him , sound an alarm and switch strong white light to scare away invading characters. 【360 Degree Viewing】 Automatically sense 360-degree pan/tilt panorama tracking indoors and outdoors, horizontal rotation 360 ° and vertical rotation 180 °, no need to worry about the blind area, protect family and personal property safety. Take care of elderly parents, children, pets.',
  'SYMYNELEC Light Bulb Camera WiFi Outdoor, Wireless PTZ Security IP Camera, 2K Super FHD Smart Home Surveillance Cam with Human Motion Detection Alarm Night Vision Two Way Talk (2.4GHz Only)💡【Fast Installation & Setup】- As easy as replacing a light bulb to install the light bulb camera, and set up via your smart phone within 3 minutes. No drill, no wiring, no power cable. Simple to control, and a breeze to maintain. Compatible with 2.4GHz WiFI network. 5GHz NOT SUPPORTED. Download "Tuya Smart" app from App Store or Google Play. The maximum WiFi signal reception range of the bulb camera is 12 meters. Please install it as close to the WiFi router as possible. 💡【4MP FHD Video & Color Night Vision】- 2K 4MP Full HD security camera provides crystal clear videos and recordings. Quality infrared LEDs & Sensor extend the range of night vision reach up to 66ft, lets you see everything clearly even in the dark. Light does not penetrate through the glass. Do not install the bulb camera inside the glass fixture as it may affect its night vision. 💡【Multi-device Sharing & Multi-view】- You can share your cameras with family, friends and other devices so that you can all access them simultaneously. Up to 16 views can be viewed concurrently, ensuring that no detail is overlooked. Compatible with Alexa and Google Assistant to free up your hands. 💡【350° Human Auto Motion Detection】- Automatically human recognition senses and detect the action in your indoor/outdoor in 350°. SYMYNELEC Security Cam has wide field of view - rotates 350° horizontally and 120° vertically. Pan/Tilt/Zoom/Light/Talk/Playback easily with the Tuya App, whenever and wherever. Please note: The maximum horizontal rotation angle of the bulb security camera is 350 degrees, not 360 degrees cyclically. 💡【Real-time Alert & 2-Way Talk】- Motion alerts will be sent to your device while you\'re out to keep you informed of every potential danger at your home. You can work with peace of mind by bulb camera WiFi outdoor, which allows you to keep in touch with your family or pets anywhere anytime with built-in speaker. 💡【Video Privacy Guarantee】- Video and Accounts are encrypted using a unique encryption technology to save video on micro SD card (Not included) or Cloud. Even if your camera light bulb or SD card is stolen, the video files in the SD card can only be accessed in your own account. Maintain the security of your home and keep your data and privacy secure. 💡【Large Bulb Camera Size: 8.1*4.4inches. Please check if it fits in your socket】- Any questions about connection, installation, functionality or more, please feel free to contact us. We sincerely provide you with lifetime technical support and service.',
  'digitsea(TM) 2.7" 1080P HD TFT screen car DVR vehicle camera video recorder camcorder road dash cam gs8000 with HDMI interface wide-angle night vision and motion detection',
  'D-Link DCS-5020L Pan and Tilt Day/Night Network CameraD-link Dcs-5020l Network Camera - Color, Monochrome - 640 X 480 - Cmos - Wireless, Cable - Wi-fi - Fast Ethernet',